import Foundation

// 20 Social Science Olympiad papers. Split into this per-subject
// file so no single registry file approaches the 600-LOC Big-Sur
// Swift-5.5 type-checker ceiling (a 69-element array literal in one
// file both broke the file-size gate and risked a slow type-check).

extension OlympiadPaperRegistry {
    static let socialSciencePapers: [OlympiadPaper] = [
        OlympiadPaper(
            id: "olympiad_socialscience_ssch01",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 1,
            chapterTitle: "Geographical Diversity of India",
            displayTitle: "Geographical Diversity of India — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch01_GeographicalDiversityOfIndia_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch01_GeographicalDiversityOfIndia_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch01_GeographicalDiversityOfIndia.html",
            questionPaperPDF: "SocialScience_Ssch01_GeographicalDiversityOfIndia.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch01_GeographicalDiversityOfIndia_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch02",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 2,
            chapterTitle: "Understanding the Weather",
            displayTitle: "Understanding the Weather — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch02_UnderstandingTheWeather_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch02_UnderstandingTheWeather_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch02_UnderstandingTheWeather.html",
            questionPaperPDF: "SocialScience_Ssch02_UnderstandingTheWeather.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch02_UnderstandingTheWeather_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch03",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 3,
            chapterTitle: "Climates of India",
            displayTitle: "Climates of India — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch03_ClimatesOfIndia_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch03_ClimatesOfIndia_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch03_ClimatesOfIndia.html",
            questionPaperPDF: "SocialScience_Ssch03_ClimatesOfIndia.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch03_ClimatesOfIndia_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch04",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 4,
            chapterTitle: "New Beginnings: Cities and States",
            displayTitle: "New Beginnings: Cities and States — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch04_NewBeginningsCitiesAndStates_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch04_NewBeginningsCitiesAndStates_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch04_NewBeginningsCitiesAndStates.html",
            questionPaperPDF: "SocialScience_Ssch04_NewBeginningsCitiesAndStates.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch04_NewBeginningsCitiesAndStates_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch05",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 5,
            chapterTitle: "The Rise of Empires",
            displayTitle: "The Rise of Empires — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch05_TheRiseOfEmpires_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch05_TheRiseOfEmpires_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch05_TheRiseOfEmpires.html",
            questionPaperPDF: "SocialScience_Ssch05_TheRiseOfEmpires.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch05_TheRiseOfEmpires_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch06",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 6,
            chapterTitle: "The Age of Reorganisation",
            displayTitle: "The Age of Reorganisation — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch06_TheAgeOfReorganisation_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch06_TheAgeOfReorganisation_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch06_TheAgeOfReorganisation.html",
            questionPaperPDF: "SocialScience_Ssch06_TheAgeOfReorganisation.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch06_TheAgeOfReorganisation_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch07",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 7,
            chapterTitle: "The Gupta Era: An Age of Tireless Creativity",
            displayTitle: "The Gupta Era: An Age of Tireless Creativity — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch07_TheGuptaEra_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch07_TheGuptaEra_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch07_TheGuptaEra.html",
            questionPaperPDF: "SocialScience_Ssch07_TheGuptaEra.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch07_TheGuptaEra_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch08",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 8,
            chapterTitle: "How the Land Becomes Sacred",
            displayTitle: "How the Land Becomes Sacred — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch08_HowTheLandBecomesSacred_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch08_HowTheLandBecomesSacred_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch08_HowTheLandBecomesSacred.html",
            questionPaperPDF: "SocialScience_Ssch08_HowTheLandBecomesSacred.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch08_HowTheLandBecomesSacred_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch09",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 9,
            chapterTitle: "From the Rulers to the Ruled: Types of Governments",
            displayTitle: "From the Rulers to the Ruled: Types of Governments — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch09_TypesOfGovernments_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch09_TypesOfGovernments_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch09_TypesOfGovernments.html",
            questionPaperPDF: "SocialScience_Ssch09_TypesOfGovernments.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch09_TypesOfGovernments_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch10",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 10,
            chapterTitle: "The Constitution of India — An Introduction",
            displayTitle: "The Constitution of India — An Introduction — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch10_TheConstitutionOfIndia_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch10_TheConstitutionOfIndia_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch10_TheConstitutionOfIndia.html",
            questionPaperPDF: "SocialScience_Ssch10_TheConstitutionOfIndia.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch10_TheConstitutionOfIndia_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch11",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 11,
            chapterTitle: "From Barter to Money",
            displayTitle: "From Barter to Money — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch11_FromBarterToMoney_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch11_FromBarterToMoney_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch11_FromBarterToMoney.html",
            questionPaperPDF: "SocialScience_Ssch11_FromBarterToMoney.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch11_FromBarterToMoney_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch12",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 12,
            chapterTitle: "Understanding Markets",
            displayTitle: "Understanding Markets — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch12_UnderstandingMarkets_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch12_UnderstandingMarkets_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch12_UnderstandingMarkets.html",
            questionPaperPDF: "SocialScience_Ssch12_UnderstandingMarkets.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch12_UnderstandingMarkets_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch13",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 13,
            chapterTitle: "The Story of Indian Farming",
            displayTitle: "The Story of Indian Farming — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch13_TheStoryOfIndianFarming_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch13_TheStoryOfIndianFarming_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch13_TheStoryOfIndianFarming.html",
            questionPaperPDF: "SocialScience_Ssch13_TheStoryOfIndianFarming.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch13_TheStoryOfIndianFarming_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch14",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 14,
            chapterTitle: "India and Her Neighbours",
            displayTitle: "India and Her Neighbours — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch14_IndiaAndHerNeighbours_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch14_IndiaAndHerNeighbours_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch14_IndiaAndHerNeighbours.html",
            questionPaperPDF: "SocialScience_Ssch14_IndiaAndHerNeighbours.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch14_IndiaAndHerNeighbours_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch15",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 15,
            chapterTitle: "Empires and Kingdoms: 6th to 10th Centuries",
            displayTitle: "Empires and Kingdoms: 6th to 10th Centuries — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch15_EmpiresAndKingdoms6thTo10thCenturies_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch15_EmpiresAndKingdoms6thTo10thCenturies_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch15_EmpiresAndKingdoms6thTo10thCenturies.html",
            questionPaperPDF: "SocialScience_Ssch15_EmpiresAndKingdoms6thTo10thCenturies.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch15_EmpiresAndKingdoms6thTo10thCenturies_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch16",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 16,
            chapterTitle: "Turning Tides: 11th and 12th Centuries",
            displayTitle: "Turning Tides: 11th and 12th Centuries — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch16_TurningTides11thAnd12thCenturies_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch16_TurningTides11thAnd12thCenturies_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch16_TurningTides11thAnd12thCenturies.html",
            questionPaperPDF: "SocialScience_Ssch16_TurningTides11thAnd12thCenturies.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch16_TurningTides11thAnd12thCenturies_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch17",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 17,
            chapterTitle: "India, a Home to Many",
            displayTitle: "India, a Home to Many — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch17_IndiaAHomeToMany_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch17_IndiaAHomeToMany_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch17_IndiaAHomeToMany.html",
            questionPaperPDF: "SocialScience_Ssch17_IndiaAHomeToMany.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch17_IndiaAHomeToMany_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch18",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 18,
            chapterTitle: "The State, the Government, and You",
            displayTitle: "The State, the Government, and You — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch18_TheStateTheGovernmentAndYou_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch18_TheStateTheGovernmentAndYou_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch18_TheStateTheGovernmentAndYou.html",
            questionPaperPDF: "SocialScience_Ssch18_TheStateTheGovernmentAndYou.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch18_TheStateTheGovernmentAndYou_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch19",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 19,
            chapterTitle: "Infrastructure: Engine of India's Development",
            displayTitle: "Infrastructure: Engine of India's Development — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch19_Infrastructure_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch19_Infrastructure_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch19_Infrastructure.html",
            questionPaperPDF: "SocialScience_Ssch19_Infrastructure.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch19_Infrastructure_SolvedGuide.html"
        ),
        OlympiadPaper(
            id: "olympiad_socialscience_ssch20",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 20,
            chapterTitle: "Banks and the Magic of Finance",
            displayTitle: "Banks and the Magic of Finance — 60 MCQ Olympiad",
            questionPaperMD: "SocialScience_Ssch20_BanksAndTheMagicOfFinance_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch20_BanksAndTheMagicOfFinance_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch20_BanksAndTheMagicOfFinance.html",
            questionPaperPDF: "SocialScience_Ssch20_BanksAndTheMagicOfFinance.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch20_BanksAndTheMagicOfFinance_SolvedGuide.html"
        ),
        // ── Advanced (Paper 2) entry authored in the v8 rollout. Reuses
        //    Paper 1's printable HTML + PDF; tier=.advanced marks the row,
        //    and solvedGuideHTML points at the Advanced guide rendered by
        //    scripts/make_solved_guide.py.
        OlympiadPaper(
            id: "olympiad_socialscience_ssch01_advanced",
            subjectId: "socialscience_class7",
            subjectName: "Social Science",
            chapterNumber: 1,
            chapterTitle: "Geographical Diversity of India",
            displayTitle: "Geographical Diversity of India — Paper 2 (Advanced)",
            questionPaperMD: "SocialScience_Ssch01_GeographicalDiversityOfIndia_Advanced_QuestionPaper.md",
            solutionsMD: "SocialScience_Ssch01_GeographicalDiversityOfIndia_Advanced_Solutions.md",
            questionPaperHTML: "SocialScience_Ssch01_GeographicalDiversityOfIndia.html",
            questionPaperPDF: "SocialScience_Ssch01_GeographicalDiversityOfIndia.pdf",
            suggestedTimeMinutes: 90,
            solvedGuideHTML: "SocialScience_Ssch01_GeographicalDiversityOfIndia_Advanced_SolvedGuide.html",
            tier: .advanced
        )
    ]
}
