import Foundation

// Maths (NCERT Class 7 "Ganita Prakash") article registrations. Split out of
// ArticleIndex.entries so Maths content edits stay disjoint from Science.
// Keys carry the `mch` prefix; merged into ArticleIndex.entries in ArticleIndex.swift.
extension ArticleIndex {
    static let mathsEntries: [String: ArticleEntry] = [
        // ── Maths (Class 7) articles — keys carry the m-prefix (mch01…) ──
        "mch01_mistakes": ArticleEntry(id: "mch01_mistakes", filename: "mch01_mistakes.html", title: "Common Mistakes — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 5),
        "mch01_glossary": ArticleEntry(id: "mch01_glossary", filename: "mch01_glossary.html", title: "Vocabulary Deck — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 4),
        "mch01_ncert_qa": ArticleEntry(id: "mch01_ncert_qa", filename: "mch01_ncert_qa.html", title: "NCERT Q&A — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 6),
        "mch01_beyond": ArticleEntry(id: "mch01_beyond", filename: "mch01_beyond.html", title: "Beyond the Book — How Big Is Big?", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 6),
        "mch02_mistakes": ArticleEntry(id: "mch02_mistakes", filename: "mch02_mistakes.html", title: "Common Mistakes — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 5),
        "mch02_glossary": ArticleEntry(id: "mch02_glossary", filename: "mch02_glossary.html", title: "Vocabulary Deck — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 4),
        "mch02_ncert_qa": ArticleEntry(id: "mch02_ncert_qa", filename: "mch02_ncert_qa.html", title: "NCERT Q&A — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 6),
        "mch02_beyond": ArticleEntry(id: "mch02_beyond", filename: "mch02_beyond.html", title: "Beyond the Book — Who Invented the Signs?", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 6),
        "mch03_mistakes": ArticleEntry(id: "mch03_mistakes", filename: "mch03_mistakes.html", title: "Common Mistakes — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 5),
        "mch03_glossary": ArticleEntry(id: "mch03_glossary", filename: "mch03_glossary.html", title: "Vocabulary Deck — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 4),
        "mch03_ncert_qa": ArticleEntry(id: "mch03_ncert_qa", filename: "mch03_ncert_qa.html", title: "NCERT Q&A — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 6),
        "mch03_beyond": ArticleEntry(id: "mch03_beyond", filename: "mch03_beyond.html", title: "Beyond the Book — The Tiny Dot That Changed Counting", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 6),
        "mch04_mistakes": ArticleEntry(id: "mch04_mistakes", filename: "mch04_mistakes.html", title: "Common Mistakes — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 5),
        "mch04_glossary": ArticleEntry(id: "mch04_glossary", filename: "mch04_glossary.html", title: "Vocabulary Deck — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 4),
        "mch04_ncert_qa": ArticleEntry(id: "mch04_ncert_qa", filename: "mch04_ncert_qa.html", title: "NCERT Q&A — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 6),
        "mch04_beyond": ArticleEntry(id: "mch04_beyond", filename: "mch04_beyond.html", title: "Beyond the Book — The Day Letters Became Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 6),
        "mch05_mistakes": ArticleEntry(id: "mch05_mistakes", filename: "mch05_mistakes.html", title: "Common Mistakes — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 5),
        "mch05_glossary": ArticleEntry(id: "mch05_glossary", filename: "mch05_glossary.html", title: "Vocabulary Deck — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 4),
        "mch05_ncert_qa": ArticleEntry(id: "mch05_ncert_qa", filename: "mch05_ncert_qa.html", title: "NCERT Q&A — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 6),
        "mch05_beyond": ArticleEntry(id: "mch05_beyond", filename: "mch05_beyond.html", title: "Beyond the Book — The Lines That Never Meet", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 6),
        "mch06_mistakes": ArticleEntry(id: "mch06_mistakes", filename: "mch06_mistakes.html", title: "Common Mistakes — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 5),
        "mch06_glossary": ArticleEntry(id: "mch06_glossary", filename: "mch06_glossary.html", title: "Vocabulary Deck — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 4),
        "mch06_ncert_qa": ArticleEntry(id: "mch06_ncert_qa", filename: "mch06_ncert_qa.html", title: "NCERT Q&A — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 6),
        "mch06_beyond": ArticleEntry(id: "mch06_beyond", filename: "mch06_beyond.html", title: "Beyond the Book — A Sequence Born in Sanskrit Poetry", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 6),
        "mch07_mistakes": ArticleEntry(id: "mch07_mistakes", filename: "mch07_mistakes.html", title: "Common Mistakes — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 5),
        "mch07_glossary": ArticleEntry(id: "mch07_glossary", filename: "mch07_glossary.html", title: "Vocabulary Deck — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 4),
        "mch07_ncert_qa": ArticleEntry(id: "mch07_ncert_qa", filename: "mch07_ncert_qa.html", title: "NCERT Q&A — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 6),
        "mch07_beyond": ArticleEntry(id: "mch07_beyond", filename: "mch07_beyond.html", title: "Beyond the Book — Why the World Is Built on Triangles", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 6),
        "mch08_mistakes": ArticleEntry(id: "mch08_mistakes", filename: "mch08_mistakes.html", title: "Common Mistakes — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 5),
        "mch08_glossary": ArticleEntry(id: "mch08_glossary", filename: "mch08_glossary.html", title: "Vocabulary Deck — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 4),
        "mch08_ncert_qa": ArticleEntry(id: "mch08_ncert_qa", filename: "mch08_ncert_qa.html", title: "NCERT Q&A — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 6),
        "mch08_beyond": ArticleEntry(id: "mch08_beyond", filename: "mch08_beyond.html", title: "Beyond the Book — How Ancient Egypt Did Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 6),
        "mch09_mistakes": ArticleEntry(id: "mch09_mistakes", filename: "mch09_mistakes.html", title: "Common Mistakes — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 5),
        "mch09_glossary": ArticleEntry(id: "mch09_glossary", filename: "mch09_glossary.html", title: "Vocabulary Deck — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 4),
        "mch09_ncert_qa": ArticleEntry(id: "mch09_ncert_qa", filename: "mch09_ncert_qa.html", title: "NCERT Q&A — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 6),
        "mch09_beyond": ArticleEntry(id: "mch09_beyond", filename: "mch09_beyond.html", title: "Beyond the Book — When Same Shape Built the Modern World", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 6),
        "mch10_mistakes": ArticleEntry(id: "mch10_mistakes", filename: "mch10_mistakes.html", title: "Common Mistakes — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 5),
        "mch10_glossary": ArticleEntry(id: "mch10_glossary", filename: "mch10_glossary.html", title: "Vocabulary Deck — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 4),
        "mch10_ncert_qa": ArticleEntry(id: "mch10_ncert_qa", filename: "mch10_ncert_qa.html", title: "NCERT Q&A — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 6),
        "mch10_beyond": ArticleEntry(id: "mch10_beyond", filename: "mch10_beyond.html", title: "Beyond the Book — When Numbers Went Negative", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 6),
        "mch11_mistakes": ArticleEntry(id: "mch11_mistakes", filename: "mch11_mistakes.html", title: "Common Mistakes — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 5),
        "mch11_glossary": ArticleEntry(id: "mch11_glossary", filename: "mch11_glossary.html", title: "Vocabulary Deck — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 4),
        "mch11_ncert_qa": ArticleEntry(id: "mch11_ncert_qa", filename: "mch11_ncert_qa.html", title: "NCERT Q&A — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 6),
        "mch11_beyond": ArticleEntry(id: "mch11_beyond", filename: "mch11_beyond.html", title: "Beyond the Book — The Cleverest Old Trick for Common Factors", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 6),
        "mch12_mistakes": ArticleEntry(id: "mch12_mistakes", filename: "mch12_mistakes.html", title: "Common Mistakes — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 5),
        "mch12_glossary": ArticleEntry(id: "mch12_glossary", filename: "mch12_glossary.html", title: "Vocabulary Deck — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 4),
        "mch12_ncert_qa": ArticleEntry(id: "mch12_ncert_qa", filename: "mch12_ncert_qa.html", title: "NCERT Q&A — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 6),
        "mch12_beyond": ArticleEntry(id: "mch12_beyond", filename: "mch12_beyond.html", title: "Beyond the Book — Why the Whole World Counts in Tens", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 6),
        "mch13_mistakes": ArticleEntry(id: "mch13_mistakes", filename: "mch13_mistakes.html", title: "Common Mistakes — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 5),
        "mch13_glossary": ArticleEntry(id: "mch13_glossary", filename: "mch13_glossary.html", title: "Vocabulary Deck — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 4),
        "mch13_ncert_qa": ArticleEntry(id: "mch13_ncert_qa", filename: "mch13_ncert_qa.html", title: "NCERT Q&A — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 6),
        "mch13_beyond": ArticleEntry(id: "mch13_beyond", filename: "mch13_beyond.html", title: "Beyond the Book — How One Average Can Fool You", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 6),
        "mch14_mistakes": ArticleEntry(id: "mch14_mistakes", filename: "mch14_mistakes.html", title: "Common Mistakes — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 5),
        "mch14_glossary": ArticleEntry(id: "mch14_glossary", filename: "mch14_glossary.html", title: "Vocabulary Deck — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 4),
        "mch14_ncert_qa": ArticleEntry(id: "mch14_ncert_qa", filename: "mch14_ncert_qa.html", title: "NCERT Q&A — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 6),
        "mch14_beyond": ArticleEntry(id: "mch14_beyond", filename: "mch14_beyond.html", title: "Beyond the Book — A Compass, a Ruler, and Three Impossible Puzzles", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 6),
        "mch15_mistakes": ArticleEntry(id: "mch15_mistakes", filename: "mch15_mistakes.html", title: "Common Mistakes — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 5),
        "mch15_glossary": ArticleEntry(id: "mch15_glossary", filename: "mch15_glossary.html", title: "Vocabulary Deck — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 4),
        "mch15_ncert_qa": ArticleEntry(id: "mch15_ncert_qa", filename: "mch15_ncert_qa.html", title: "NCERT Q&A — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 6),
        "mch15_beyond": ArticleEntry(id: "mch15_beyond", filename: "mch15_beyond.html", title: "Beyond the Book — The Balance That Solves for x", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 6),
        "mch01_miniproject": ArticleEntry(id: "mch01_miniproject", filename: "mch01_miniproject.html", title: "Mini Project — Lakh and Crore Around Me", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 60),
        "mch01_selfcheck": ArticleEntry(id: "mch01_selfcheck", filename: "mch01_selfcheck.html", title: "Self-Check — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 5),
        "mch01_storymode": ArticleEntry(id: "mch01_storymode", filename: "mch01_storymode.html", title: "Story Mode — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 6),
        "mch02_miniproject": ArticleEntry(id: "mch02_miniproject", filename: "mch02_miniproject.html", title: "Mini Project — Expression Storyteller", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 30),
        "mch02_selfcheck": ArticleEntry(id: "mch02_selfcheck", filename: "mch02_selfcheck.html", title: "Self-Check — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 5),
        "mch02_storymode": ArticleEntry(id: "mch02_storymode", filename: "mch02_storymode.html", title: "Story Mode — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 6),
        "mch03_miniproject": ArticleEntry(id: "mch03_miniproject", filename: "mch03_miniproject.html", title: "Mini Project — Make Your Own Tenths Ruler", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 40),
        "mch03_selfcheck": ArticleEntry(id: "mch03_selfcheck", filename: "mch03_selfcheck.html", title: "Self-Check — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 5),
        "mch03_storymode": ArticleEntry(id: "mch03_storymode", filename: "mch03_storymode.html", title: "Story Mode — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 6),
        "mch04_miniproject": ArticleEntry(id: "mch04_miniproject", filename: "mch04_miniproject.html", title: "Mini Project — Letter-Number Detective", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 35),
        "mch04_selfcheck": ArticleEntry(id: "mch04_selfcheck", filename: "mch04_selfcheck.html", title: "Self-Check — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 5),
        "mch04_storymode": ArticleEntry(id: "mch04_storymode", filename: "mch04_storymode.html", title: "Story Mode — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 6),
        "mch05_miniproject": ArticleEntry(id: "mch05_miniproject", filename: "mch05_miniproject.html", title: "Mini Project — Paper-Fold Parallel & Perpendicular Hunt", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 40),
        "mch05_selfcheck": ArticleEntry(id: "mch05_selfcheck", filename: "mch05_selfcheck.html", title: "Self-Check — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 5),
        "mch05_storymode": ArticleEntry(id: "mch05_storymode", filename: "mch05_storymode.html", title: "Story Mode — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 6),
        "mch06_miniproject": ArticleEntry(id: "mch06_miniproject", filename: "mch06_miniproject.html", title: "Mini Project — Parity Detective", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 30),
        "mch06_selfcheck": ArticleEntry(id: "mch06_selfcheck", filename: "mch06_selfcheck.html", title: "Self-Check — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 5),
        "mch06_storymode": ArticleEntry(id: "mch06_storymode", filename: "mch06_storymode.html", title: "Story Mode — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 6),
        "mch07_miniproject": ArticleEntry(id: "mch07_miniproject", filename: "mch07_miniproject.html", title: "Mini Project — Triangle or Not? The Straw Test", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 40),
        "mch07_selfcheck": ArticleEntry(id: "mch07_selfcheck", filename: "mch07_selfcheck.html", title: "Self-Check — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 5),
        "mch07_storymode": ArticleEntry(id: "mch07_storymode", filename: "mch07_storymode.html", title: "Story Mode — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 6),
        "mch08_miniproject": ArticleEntry(id: "mch08_miniproject", filename: "mch08_miniproject.html", title: "Mini Project — Chocolate-Bar Fraction Lab", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 35),
        "mch08_selfcheck": ArticleEntry(id: "mch08_selfcheck", filename: "mch08_selfcheck.html", title: "Self-Check — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 5),
        "mch08_storymode": ArticleEntry(id: "mch08_storymode", filename: "mch08_storymode.html", title: "Story Mode — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 6),
        "mch09_miniproject": ArticleEntry(id: "mch09_miniproject", filename: "mch09_miniproject.html", title: "Mini Project — Congruence by Cut-and-Fold", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 35),
        "mch09_selfcheck": ArticleEntry(id: "mch09_selfcheck", filename: "mch09_selfcheck.html", title: "Self-Check — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 5),
        "mch09_storymode": ArticleEntry(id: "mch09_storymode", filename: "mch09_storymode.html", title: "Story Mode — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 6),
        "mch10_miniproject": ArticleEntry(id: "mch10_miniproject", filename: "mch10_miniproject.html", title: "Mini Project — Token-Bag Integer Machine", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 35),
        "mch10_selfcheck": ArticleEntry(id: "mch10_selfcheck", filename: "mch10_selfcheck.html", title: "Self-Check — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 5),
        "mch10_storymode": ArticleEntry(id: "mch10_storymode", filename: "mch10_storymode.html", title: "Story Mode — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 6),
        "mch11_miniproject": ArticleEntry(id: "mch11_miniproject", filename: "mch11_miniproject.html", title: "Mini Project — Tile the Room (HCF) & Sync the Bells (LCM)", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 40),
        "mch11_selfcheck": ArticleEntry(id: "mch11_selfcheck", filename: "mch11_selfcheck.html", title: "Self-Check — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 5),
        "mch11_storymode": ArticleEntry(id: "mch11_storymode", filename: "mch11_storymode.html", title: "Story Mode — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 6),
        "mch12_miniproject": ArticleEntry(id: "mch12_miniproject", filename: "mch12_miniproject.html", title: "Mini Project — Decimal Shopping Check", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 30),
        "mch12_selfcheck": ArticleEntry(id: "mch12_selfcheck", filename: "mch12_selfcheck.html", title: "Self-Check — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 5),
        "mch12_storymode": ArticleEntry(id: "mch12_storymode", filename: "mch12_storymode.html", title: "Story Mode — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 6),
        "mch13_miniproject": ArticleEntry(id: "mch13_miniproject", filename: "mch13_miniproject.html", title: "Mini Project — Class Data Detective", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 45),
        "mch13_selfcheck": ArticleEntry(id: "mch13_selfcheck", filename: "mch13_selfcheck.html", title: "Self-Check — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 5),
        "mch13_storymode": ArticleEntry(id: "mch13_storymode", filename: "mch13_storymode.html", title: "Story Mode — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 6),
        "mch14_miniproject": ArticleEntry(id: "mch14_miniproject", filename: "mch14_miniproject.html", title: "Mini Project — Construct & Tile", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 45),
        "mch14_selfcheck": ArticleEntry(id: "mch14_selfcheck", filename: "mch14_selfcheck.html", title: "Self-Check — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 5),
        "mch14_storymode": ArticleEntry(id: "mch14_storymode", filename: "mch14_storymode.html", title: "Story Mode — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 6),
        "mch15_miniproject": ArticleEntry(id: "mch15_miniproject", filename: "mch15_miniproject.html", title: "Mini Project — Build a Balance, Solve an Equation", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 40),
        "mch15_selfcheck": ArticleEntry(id: "mch15_selfcheck", filename: "mch15_selfcheck.html", title: "Self-Check — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 5),
        "mch15_storymode": ArticleEntry(id: "mch15_storymode", filename: "mch15_storymode.html", title: "Story Mode — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 6),
        "mch01_scientists": ArticleEntry(id: "mch01_scientists", filename: "mch01_scientists.html", title: "Scientist Spotlight — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 7),
        "mch02_scientists": ArticleEntry(id: "mch02_scientists", filename: "mch02_scientists.html", title: "Scientist Spotlight — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 7),
        "mch03_scientists": ArticleEntry(id: "mch03_scientists", filename: "mch03_scientists.html", title: "Scientist Spotlight — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 7),
        "mch04_scientists": ArticleEntry(id: "mch04_scientists", filename: "mch04_scientists.html", title: "Scientist Spotlight — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 7),
        "mch05_scientists": ArticleEntry(id: "mch05_scientists", filename: "mch05_scientists.html", title: "Scientist Spotlight — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 7),
        "mch06_scientists": ArticleEntry(id: "mch06_scientists", filename: "mch06_scientists.html", title: "Scientist Spotlight — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 7),
        "mch07_scientists": ArticleEntry(id: "mch07_scientists", filename: "mch07_scientists.html", title: "Scientist Spotlight — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 7),
        "mch08_scientists": ArticleEntry(id: "mch08_scientists", filename: "mch08_scientists.html", title: "Scientist Spotlight — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 7),
        "mch09_scientists": ArticleEntry(id: "mch09_scientists", filename: "mch09_scientists.html", title: "Scientist Spotlight — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 7),
        "mch10_scientists": ArticleEntry(id: "mch10_scientists", filename: "mch10_scientists.html", title: "Scientist Spotlight — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 7),
        "mch11_scientists": ArticleEntry(id: "mch11_scientists", filename: "mch11_scientists.html", title: "Scientist Spotlight — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 7),
        "mch12_scientists": ArticleEntry(id: "mch12_scientists", filename: "mch12_scientists.html", title: "Scientist Spotlight — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 7),
        "mch13_scientists": ArticleEntry(id: "mch13_scientists", filename: "mch13_scientists.html", title: "Scientist Spotlight — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 7),
        "mch14_scientists": ArticleEntry(id: "mch14_scientists", filename: "mch14_scientists.html", title: "Scientist Spotlight — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 7),
        "mch15_scientists": ArticleEntry(id: "mch15_scientists", filename: "mch15_scientists.html", title: "Scientist Spotlight — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 7),
        "mch01_whatif": ArticleEntry(id: "mch01_whatif", filename: "mch01_whatif.html", title: "What If? — Large Numbers Around Us", chapterFolder: "Articles/MathsChapter1", estimatedMinutes: 7),
        "mch02_whatif": ArticleEntry(id: "mch02_whatif", filename: "mch02_whatif.html", title: "What If? — Arithmetic Expressions", chapterFolder: "Articles/MathsChapter2", estimatedMinutes: 7),
        "mch03_whatif": ArticleEntry(id: "mch03_whatif", filename: "mch03_whatif.html", title: "What If? — A Peek Beyond the Point", chapterFolder: "Articles/MathsChapter3", estimatedMinutes: 7),
        "mch04_whatif": ArticleEntry(id: "mch04_whatif", filename: "mch04_whatif.html", title: "What If? — Expressions Using Letter-Numbers", chapterFolder: "Articles/MathsChapter4", estimatedMinutes: 7),
        "mch05_whatif": ArticleEntry(id: "mch05_whatif", filename: "mch05_whatif.html", title: "What If? — Parallel and Intersecting Lines", chapterFolder: "Articles/MathsChapter5", estimatedMinutes: 7),
        "mch06_whatif": ArticleEntry(id: "mch06_whatif", filename: "mch06_whatif.html", title: "What If? — Number Play", chapterFolder: "Articles/MathsChapter6", estimatedMinutes: 7),
        "mch07_whatif": ArticleEntry(id: "mch07_whatif", filename: "mch07_whatif.html", title: "What If? — A Tale of Three Intersecting Lines", chapterFolder: "Articles/MathsChapter7", estimatedMinutes: 7),
        "mch08_whatif": ArticleEntry(id: "mch08_whatif", filename: "mch08_whatif.html", title: "What If? — Working with Fractions", chapterFolder: "Articles/MathsChapter8", estimatedMinutes: 7),
        "mch09_whatif": ArticleEntry(id: "mch09_whatif", filename: "mch09_whatif.html", title: "What If? — Geometric Twins", chapterFolder: "Articles/MathsChapter9", estimatedMinutes: 7),
        "mch10_whatif": ArticleEntry(id: "mch10_whatif", filename: "mch10_whatif.html", title: "What If? — Operations with Integers", chapterFolder: "Articles/MathsChapter10", estimatedMinutes: 7),
        "mch11_whatif": ArticleEntry(id: "mch11_whatif", filename: "mch11_whatif.html", title: "What If? — Finding Common Ground", chapterFolder: "Articles/MathsChapter11", estimatedMinutes: 7),
        "mch12_whatif": ArticleEntry(id: "mch12_whatif", filename: "mch12_whatif.html", title: "What If? — Another Peek Beyond the Point", chapterFolder: "Articles/MathsChapter12", estimatedMinutes: 7),
        "mch13_whatif": ArticleEntry(id: "mch13_whatif", filename: "mch13_whatif.html", title: "What If? — Connecting the Dots", chapterFolder: "Articles/MathsChapter13", estimatedMinutes: 7),
        "mch14_whatif": ArticleEntry(id: "mch14_whatif", filename: "mch14_whatif.html", title: "What If? — Constructions and Tilings", chapterFolder: "Articles/MathsChapter14", estimatedMinutes: 7),
        "mch15_whatif": ArticleEntry(id: "mch15_whatif", filename: "mch15_whatif.html", title: "What If? — Finding the Unknown", chapterFolder: "Articles/MathsChapter15", estimatedMinutes: 7),
    ]
}
