import Foundation

// Science (NCERT Class 7) article registrations, part 4 (ch06–ch19).
// Split out of the monolithic ArticleIndex.entries literal so per-subject
// content edits stay disjoint and each partial stays under the 600-LOC ceiling.
// Merged into ArticleIndex.entries in ArticleIndex.swift.
extension ArticleIndex {
    static let scienceEntries4: [String: ArticleEntry] = [
        "ch06_glossary": ArticleEntry(id: "ch06_glossary", filename: "ch06_glossary.html",
            title: "A Class 7 Physical and Chemical Changes Dictionary",
            chapterFolder: chapter6Folder, estimatedMinutes: 5),
        "ch07_glossary": ArticleEntry(id: "ch07_glossary", filename: "ch07_glossary.html",
            title: "A Class 7 Weather, Climate and Adaptations Dictionary",
            chapterFolder: chapter7Folder, estimatedMinutes: 5),
        "ch08_glossary": ArticleEntry(id: "ch08_glossary", filename: "ch08_glossary.html",
            title: "A Class 7 Winds, Storms and Cyclones Dictionary",
            chapterFolder: chapter8Folder, estimatedMinutes: 5),
        "ch09_glossary": ArticleEntry(id: "ch09_glossary", filename: "ch09_glossary.html",
            title: "A Class 7 Soil Dictionary",
            chapterFolder: chapter9Folder, estimatedMinutes: 5),
        "ch10_glossary": ArticleEntry(id: "ch10_glossary", filename: "ch10_glossary.html",
            title: "A Class 7 Respiration in Organisms Dictionary",
            chapterFolder: chapter10Folder, estimatedMinutes: 5),
        "ch11_glossary": ArticleEntry(id: "ch11_glossary", filename: "ch11_glossary.html",
            title: "A Class 7 Transportation in Animals and Plants Dictionary",
            chapterFolder: chapter11Folder, estimatedMinutes: 5),
        "ch12_glossary": ArticleEntry(id: "ch12_glossary", filename: "ch12_glossary.html",
            title: "A Class 7 Reproduction in Plants Dictionary",
            chapterFolder: chapter12Folder, estimatedMinutes: 5),
        "ch13_glossary": ArticleEntry(id: "ch13_glossary", filename: "ch13_glossary.html",
            title: "A Class 7 Motion and Time Dictionary",
            chapterFolder: chapter13Folder, estimatedMinutes: 5),
        "ch14_glossary": ArticleEntry(id: "ch14_glossary", filename: "ch14_glossary.html",
            title: "A Class 7 Electric Current and its Effect Dictionary",
            chapterFolder: chapter14Folder, estimatedMinutes: 5),
        "ch15_glossary": ArticleEntry(id: "ch15_glossary", filename: "ch15_glossary.html",
            title: "A Class 7 Light Dictionary",
            chapterFolder: chapter15Folder, estimatedMinutes: 5),
        "ch16_glossary": ArticleEntry(id: "ch16_glossary", filename: "ch16_glossary.html",
            title: "A Class 7 Water: A Precious Resource Dictionary",
            chapterFolder: chapter16Folder, estimatedMinutes: 5),
        "ch17_glossary": ArticleEntry(id: "ch17_glossary", filename: "ch17_glossary.html",
            title: "A Class 7 Forest: Our Lifeline Dictionary",
            chapterFolder: chapter17Folder, estimatedMinutes: 5),
        "ch18_glossary": ArticleEntry(id: "ch18_glossary", filename: "ch18_glossary.html",
            title: "A Class 7 Wastewater Story Dictionary",
            chapterFolder: chapter18Folder, estimatedMinutes: 5),
        "ch19_glossary": ArticleEntry(id: "ch19_glossary", filename: "ch19_glossary.html",
            title: "A Class 7 Earth, Moon and the Sun Dictionary",
            chapterFolder: chapter19Folder, estimatedMinutes: 5),

        // NCERT Q&A — exam-prep articles for Ch.2-19, generated
        // 2026-05-26 by scripts/generate_ncert_qa_articles.py from
        // chapter.ncertQA JSON. Ch.1 has a bespoke 8-Q entry above.
        "ch02_ncert_qa": ArticleEntry(id: "ch02_ncert_qa", filename: "ch02_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 2",
            chapterFolder: chapter2Folder, estimatedMinutes: 12),
        "ch03_ncert_qa": ArticleEntry(id: "ch03_ncert_qa", filename: "ch03_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 3",
            chapterFolder: chapter3Folder, estimatedMinutes: 12),
        "ch04_ncert_qa": ArticleEntry(id: "ch04_ncert_qa", filename: "ch04_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 4",
            chapterFolder: chapter4Folder, estimatedMinutes: 12),
        "ch05_ncert_qa": ArticleEntry(id: "ch05_ncert_qa", filename: "ch05_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 5",
            chapterFolder: chapter5Folder, estimatedMinutes: 12),
        "ch06_ncert_qa": ArticleEntry(id: "ch06_ncert_qa", filename: "ch06_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 6",
            chapterFolder: chapter6Folder, estimatedMinutes: 12),
        "ch07_ncert_qa": ArticleEntry(id: "ch07_ncert_qa", filename: "ch07_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 7",
            chapterFolder: chapter7Folder, estimatedMinutes: 12),
        "ch08_ncert_qa": ArticleEntry(id: "ch08_ncert_qa", filename: "ch08_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 8",
            chapterFolder: chapter8Folder, estimatedMinutes: 12),
        "ch09_ncert_qa": ArticleEntry(id: "ch09_ncert_qa", filename: "ch09_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 9",
            chapterFolder: chapter9Folder, estimatedMinutes: 12),
        "ch10_ncert_qa": ArticleEntry(id: "ch10_ncert_qa", filename: "ch10_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 10",
            chapterFolder: chapter10Folder, estimatedMinutes: 12),
        "ch11_ncert_qa": ArticleEntry(id: "ch11_ncert_qa", filename: "ch11_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 11",
            chapterFolder: chapter11Folder, estimatedMinutes: 12),
        "ch12_ncert_qa": ArticleEntry(id: "ch12_ncert_qa", filename: "ch12_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 12",
            chapterFolder: chapter12Folder, estimatedMinutes: 12),
        "ch13_ncert_qa": ArticleEntry(id: "ch13_ncert_qa", filename: "ch13_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 13",
            chapterFolder: chapter13Folder, estimatedMinutes: 12),
        "ch14_ncert_qa": ArticleEntry(id: "ch14_ncert_qa", filename: "ch14_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 14",
            chapterFolder: chapter14Folder, estimatedMinutes: 12),
        "ch15_ncert_qa": ArticleEntry(id: "ch15_ncert_qa", filename: "ch15_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 15",
            chapterFolder: chapter15Folder, estimatedMinutes: 12),
        "ch16_ncert_qa": ArticleEntry(id: "ch16_ncert_qa", filename: "ch16_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 16",
            chapterFolder: chapter16Folder, estimatedMinutes: 12),
        "ch17_ncert_qa": ArticleEntry(id: "ch17_ncert_qa", filename: "ch17_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 17",
            chapterFolder: chapter17Folder, estimatedMinutes: 12),
        "ch18_ncert_qa": ArticleEntry(id: "ch18_ncert_qa", filename: "ch18_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 18",
            chapterFolder: chapter18Folder, estimatedMinutes: 12),
        "ch19_ncert_qa": ArticleEntry(id: "ch19_ncert_qa", filename: "ch19_ncert_qa.html",
            title: "NCERT Exercise Q&A — Chapter 19",
            chapterFolder: chapter19Folder, estimatedMinutes: 12),

        // Scientist Spotlight (biography articles) — Ch.2-19 generated
        // 2026-05-26 by scripts/generate_scientists_articles.py from
        // chapter.scientists JSON (1 entry per chapter). Ch.1 has a
        // bespoke 5-scientist anchor with an SVG timeline; this
        // surface complements that by giving every chapter exactly
        // one tightly-focused biography page.
        "ch02_scientists": ArticleEntry(id: "ch02_scientists", filename: "ch02_scientists.html",
            title: "Scientist Spotlight — Chapter 2",
            chapterFolder: chapter2Folder, estimatedMinutes: 4),
        "ch03_scientists": ArticleEntry(id: "ch03_scientists", filename: "ch03_scientists.html",
            title: "Scientist Spotlight — Chapter 3",
            chapterFolder: chapter3Folder, estimatedMinutes: 4),
        "ch04_scientists": ArticleEntry(id: "ch04_scientists", filename: "ch04_scientists.html",
            title: "Scientist Spotlight — Chapter 4",
            chapterFolder: chapter4Folder, estimatedMinutes: 4),
        "ch05_scientists": ArticleEntry(id: "ch05_scientists", filename: "ch05_scientists.html",
            title: "Scientist Spotlight — Chapter 5",
            chapterFolder: chapter5Folder, estimatedMinutes: 4),
        "ch06_scientists": ArticleEntry(id: "ch06_scientists", filename: "ch06_scientists.html",
            title: "Scientist Spotlight — Chapter 6",
            chapterFolder: chapter6Folder, estimatedMinutes: 4),
        "ch07_scientists": ArticleEntry(id: "ch07_scientists", filename: "ch07_scientists.html",
            title: "Scientist Spotlight — Chapter 7",
            chapterFolder: chapter7Folder, estimatedMinutes: 4),
        "ch08_scientists": ArticleEntry(id: "ch08_scientists", filename: "ch08_scientists.html",
            title: "Scientist Spotlight — Chapter 8",
            chapterFolder: chapter8Folder, estimatedMinutes: 4),
        "ch09_scientists": ArticleEntry(id: "ch09_scientists", filename: "ch09_scientists.html",
            title: "Scientist Spotlight — Chapter 9",
            chapterFolder: chapter9Folder, estimatedMinutes: 4),
        "ch10_scientists": ArticleEntry(id: "ch10_scientists", filename: "ch10_scientists.html",
            title: "Scientist Spotlight — Chapter 10",
            chapterFolder: chapter10Folder, estimatedMinutes: 4),
        "ch11_scientists": ArticleEntry(id: "ch11_scientists", filename: "ch11_scientists.html",
            title: "Scientist Spotlight — Chapter 11",
            chapterFolder: chapter11Folder, estimatedMinutes: 4),
        "ch12_scientists": ArticleEntry(id: "ch12_scientists", filename: "ch12_scientists.html",
            title: "Scientist Spotlight — Chapter 12",
            chapterFolder: chapter12Folder, estimatedMinutes: 4),
        "ch13_scientists": ArticleEntry(id: "ch13_scientists", filename: "ch13_scientists.html",
            title: "Scientist Spotlight — Chapter 13",
            chapterFolder: chapter13Folder, estimatedMinutes: 4),
        "ch14_scientists": ArticleEntry(id: "ch14_scientists", filename: "ch14_scientists.html",
            title: "Scientist Spotlight — Chapter 14",
            chapterFolder: chapter14Folder, estimatedMinutes: 4),
        "ch15_scientists": ArticleEntry(id: "ch15_scientists", filename: "ch15_scientists.html",
            title: "Scientist Spotlight — Chapter 15",
            chapterFolder: chapter15Folder, estimatedMinutes: 4),
        "ch16_scientists": ArticleEntry(id: "ch16_scientists", filename: "ch16_scientists.html",
            title: "Scientist Spotlight — Chapter 16",
            chapterFolder: chapter16Folder, estimatedMinutes: 4),
        "ch17_scientists": ArticleEntry(id: "ch17_scientists", filename: "ch17_scientists.html",
            title: "Scientist Spotlight — Chapter 17",
            chapterFolder: chapter17Folder, estimatedMinutes: 4),
        "ch18_scientists": ArticleEntry(id: "ch18_scientists", filename: "ch18_scientists.html",
            title: "Scientist Spotlight — Chapter 18",
            chapterFolder: chapter18Folder, estimatedMinutes: 4),
        "ch19_scientists": ArticleEntry(id: "ch19_scientists", filename: "ch19_scientists.html",
            title: "Scientist Spotlight — Chapter 19",
            chapterFolder: chapter19Folder, estimatedMinutes: 4),

        // What If? (thought-experiment articles) — Ch.2-19 generated
        // 2026-05-26 by scripts/generate_whatif_articles.py from
        // chapter.whatIfs JSON (3 entries per chapter; 54 total).
        // Ch.1 has a bespoke 5-scenario anchor entry above.
        "ch02_whatif": ArticleEntry(id: "ch02_whatif", filename: "ch02_whatif.html",
            title: "What If? — Chapter 2", chapterFolder: chapter2Folder, estimatedMinutes: 7),
        "ch03_whatif": ArticleEntry(id: "ch03_whatif", filename: "ch03_whatif.html",
            title: "What If? — Chapter 3", chapterFolder: chapter3Folder, estimatedMinutes: 7),
        "ch04_whatif": ArticleEntry(id: "ch04_whatif", filename: "ch04_whatif.html",
            title: "What If? — Chapter 4", chapterFolder: chapter4Folder, estimatedMinutes: 7),
        "ch05_whatif": ArticleEntry(id: "ch05_whatif", filename: "ch05_whatif.html",
            title: "What If? — Chapter 5", chapterFolder: chapter5Folder, estimatedMinutes: 7),
        "ch06_whatif": ArticleEntry(id: "ch06_whatif", filename: "ch06_whatif.html",
            title: "What If? — Chapter 6", chapterFolder: chapter6Folder, estimatedMinutes: 7),
        "ch07_whatif": ArticleEntry(id: "ch07_whatif", filename: "ch07_whatif.html",
            title: "What If? — Chapter 7", chapterFolder: chapter7Folder, estimatedMinutes: 7),
        "ch08_whatif": ArticleEntry(id: "ch08_whatif", filename: "ch08_whatif.html",
            title: "What If? — Chapter 8", chapterFolder: chapter8Folder, estimatedMinutes: 7),
        "ch09_whatif": ArticleEntry(id: "ch09_whatif", filename: "ch09_whatif.html",
            title: "What If? — Chapter 9", chapterFolder: chapter9Folder, estimatedMinutes: 7),
        "ch10_whatif": ArticleEntry(id: "ch10_whatif", filename: "ch10_whatif.html",
            title: "What If? — Chapter 10", chapterFolder: chapter10Folder, estimatedMinutes: 7),
        "ch11_whatif": ArticleEntry(id: "ch11_whatif", filename: "ch11_whatif.html",
            title: "What If? — Chapter 11", chapterFolder: chapter11Folder, estimatedMinutes: 7),
        "ch12_whatif": ArticleEntry(id: "ch12_whatif", filename: "ch12_whatif.html",
            title: "What If? — Chapter 12", chapterFolder: chapter12Folder, estimatedMinutes: 7),
        "ch13_whatif": ArticleEntry(id: "ch13_whatif", filename: "ch13_whatif.html",
            title: "What If? — Chapter 13", chapterFolder: chapter13Folder, estimatedMinutes: 7),
        "ch14_whatif": ArticleEntry(id: "ch14_whatif", filename: "ch14_whatif.html",
            title: "What If? — Chapter 14", chapterFolder: chapter14Folder, estimatedMinutes: 7),
        "ch15_whatif": ArticleEntry(id: "ch15_whatif", filename: "ch15_whatif.html",
            title: "What If? — Chapter 15", chapterFolder: chapter15Folder, estimatedMinutes: 7),
        "ch16_whatif": ArticleEntry(id: "ch16_whatif", filename: "ch16_whatif.html",
            title: "What If? — Chapter 16", chapterFolder: chapter16Folder, estimatedMinutes: 7),
        "ch17_whatif": ArticleEntry(id: "ch17_whatif", filename: "ch17_whatif.html",
            title: "What If? — Chapter 17", chapterFolder: chapter17Folder, estimatedMinutes: 7),
        "ch18_whatif": ArticleEntry(id: "ch18_whatif", filename: "ch18_whatif.html",
            title: "What If? — Chapter 18", chapterFolder: chapter18Folder, estimatedMinutes: 7),
        "ch19_whatif": ArticleEntry(id: "ch19_whatif", filename: "ch19_whatif.html",
            title: "What If? — Chapter 19", chapterFolder: chapter19Folder, estimatedMinutes: 7),

        // Mini Projects (hands-on activities) — Ch.2-19 generated
        // 2026-05-26 by scripts/generate_miniproject_articles.py from
        // chapter.miniProjects JSON (2 entries per chapter; 36 total).
        "ch02_miniproject": ArticleEntry(id: "ch02_miniproject", filename: "ch02_miniproject.html", title: "Mini Projects — Chapter 2", chapterFolder: chapter2Folder, estimatedMinutes: 60),
        "ch03_miniproject": ArticleEntry(id: "ch03_miniproject", filename: "ch03_miniproject.html", title: "Mini Projects — Chapter 3", chapterFolder: chapter3Folder, estimatedMinutes: 60),
        "ch04_miniproject": ArticleEntry(id: "ch04_miniproject", filename: "ch04_miniproject.html", title: "Mini Projects — Chapter 4", chapterFolder: chapter4Folder, estimatedMinutes: 60),
        "ch05_miniproject": ArticleEntry(id: "ch05_miniproject", filename: "ch05_miniproject.html", title: "Mini Projects — Chapter 5", chapterFolder: chapter5Folder, estimatedMinutes: 60),
        "ch06_miniproject": ArticleEntry(id: "ch06_miniproject", filename: "ch06_miniproject.html", title: "Mini Projects — Chapter 6", chapterFolder: chapter6Folder, estimatedMinutes: 60),
        "ch07_miniproject": ArticleEntry(id: "ch07_miniproject", filename: "ch07_miniproject.html", title: "Mini Projects — Chapter 7", chapterFolder: chapter7Folder, estimatedMinutes: 60),
        "ch08_miniproject": ArticleEntry(id: "ch08_miniproject", filename: "ch08_miniproject.html", title: "Mini Projects — Chapter 8", chapterFolder: chapter8Folder, estimatedMinutes: 60),
        "ch09_miniproject": ArticleEntry(id: "ch09_miniproject", filename: "ch09_miniproject.html", title: "Mini Projects — Chapter 9", chapterFolder: chapter9Folder, estimatedMinutes: 60),
        "ch10_miniproject": ArticleEntry(id: "ch10_miniproject", filename: "ch10_miniproject.html", title: "Mini Projects — Chapter 10", chapterFolder: chapter10Folder, estimatedMinutes: 60),
        "ch11_miniproject": ArticleEntry(id: "ch11_miniproject", filename: "ch11_miniproject.html", title: "Mini Projects — Chapter 11", chapterFolder: chapter11Folder, estimatedMinutes: 60),
        "ch12_miniproject": ArticleEntry(id: "ch12_miniproject", filename: "ch12_miniproject.html", title: "Mini Projects — Chapter 12", chapterFolder: chapter12Folder, estimatedMinutes: 60),
        "ch13_miniproject": ArticleEntry(id: "ch13_miniproject", filename: "ch13_miniproject.html", title: "Mini Projects — Chapter 13", chapterFolder: chapter13Folder, estimatedMinutes: 60),
        "ch14_miniproject": ArticleEntry(id: "ch14_miniproject", filename: "ch14_miniproject.html", title: "Mini Projects — Chapter 14", chapterFolder: chapter14Folder, estimatedMinutes: 60),
        "ch15_miniproject": ArticleEntry(id: "ch15_miniproject", filename: "ch15_miniproject.html", title: "Mini Projects — Chapter 15", chapterFolder: chapter15Folder, estimatedMinutes: 60),
        "ch16_miniproject": ArticleEntry(id: "ch16_miniproject", filename: "ch16_miniproject.html", title: "Mini Projects — Chapter 16", chapterFolder: chapter16Folder, estimatedMinutes: 60),
        "ch17_miniproject": ArticleEntry(id: "ch17_miniproject", filename: "ch17_miniproject.html", title: "Mini Projects — Chapter 17", chapterFolder: chapter17Folder, estimatedMinutes: 60),
        "ch18_miniproject": ArticleEntry(id: "ch18_miniproject", filename: "ch18_miniproject.html", title: "Mini Projects — Chapter 18", chapterFolder: chapter18Folder, estimatedMinutes: 60),
        "ch19_miniproject": ArticleEntry(id: "ch19_miniproject", filename: "ch19_miniproject.html", title: "Mini Projects — Chapter 19", chapterFolder: chapter19Folder, estimatedMinutes: 60),

        // Self-Check (5-question revision quiz) — Ch.2-19 generated
        // 2026-05-26 by scripts/generate_selfcheck_articles.py
        // sampling chapter.topics[].questions (5 representatives).
        "ch02_selfcheck": ArticleEntry(id: "ch02_selfcheck", filename: "ch02_selfcheck.html", title: "Self-Check — Chapter 2", chapterFolder: chapter2Folder, estimatedMinutes: 7),
        "ch03_selfcheck": ArticleEntry(id: "ch03_selfcheck", filename: "ch03_selfcheck.html", title: "Self-Check — Chapter 3", chapterFolder: chapter3Folder, estimatedMinutes: 7),
        "ch04_selfcheck": ArticleEntry(id: "ch04_selfcheck", filename: "ch04_selfcheck.html", title: "Self-Check — Chapter 4", chapterFolder: chapter4Folder, estimatedMinutes: 7),
        "ch05_selfcheck": ArticleEntry(id: "ch05_selfcheck", filename: "ch05_selfcheck.html", title: "Self-Check — Chapter 5", chapterFolder: chapter5Folder, estimatedMinutes: 7),
        "ch06_selfcheck": ArticleEntry(id: "ch06_selfcheck", filename: "ch06_selfcheck.html", title: "Self-Check — Chapter 6", chapterFolder: chapter6Folder, estimatedMinutes: 7),
        "ch07_selfcheck": ArticleEntry(id: "ch07_selfcheck", filename: "ch07_selfcheck.html", title: "Self-Check — Chapter 7", chapterFolder: chapter7Folder, estimatedMinutes: 7),
        "ch08_selfcheck": ArticleEntry(id: "ch08_selfcheck", filename: "ch08_selfcheck.html", title: "Self-Check — Chapter 8", chapterFolder: chapter8Folder, estimatedMinutes: 7),
        "ch09_selfcheck": ArticleEntry(id: "ch09_selfcheck", filename: "ch09_selfcheck.html", title: "Self-Check — Chapter 9", chapterFolder: chapter9Folder, estimatedMinutes: 7),
        "ch10_selfcheck": ArticleEntry(id: "ch10_selfcheck", filename: "ch10_selfcheck.html", title: "Self-Check — Chapter 10", chapterFolder: chapter10Folder, estimatedMinutes: 7),
        "ch11_selfcheck": ArticleEntry(id: "ch11_selfcheck", filename: "ch11_selfcheck.html", title: "Self-Check — Chapter 11", chapterFolder: chapter11Folder, estimatedMinutes: 7),
        "ch12_selfcheck": ArticleEntry(id: "ch12_selfcheck", filename: "ch12_selfcheck.html", title: "Self-Check — Chapter 12", chapterFolder: chapter12Folder, estimatedMinutes: 7),
        "ch13_selfcheck": ArticleEntry(id: "ch13_selfcheck", filename: "ch13_selfcheck.html", title: "Self-Check — Chapter 13", chapterFolder: chapter13Folder, estimatedMinutes: 7),
        "ch14_selfcheck": ArticleEntry(id: "ch14_selfcheck", filename: "ch14_selfcheck.html", title: "Self-Check — Chapter 14", chapterFolder: chapter14Folder, estimatedMinutes: 7),
        "ch15_selfcheck": ArticleEntry(id: "ch15_selfcheck", filename: "ch15_selfcheck.html", title: "Self-Check — Chapter 15", chapterFolder: chapter15Folder, estimatedMinutes: 7),
        "ch16_selfcheck": ArticleEntry(id: "ch16_selfcheck", filename: "ch16_selfcheck.html", title: "Self-Check — Chapter 16", chapterFolder: chapter16Folder, estimatedMinutes: 7),
        "ch17_selfcheck": ArticleEntry(id: "ch17_selfcheck", filename: "ch17_selfcheck.html", title: "Self-Check — Chapter 17", chapterFolder: chapter17Folder, estimatedMinutes: 7),
        "ch18_selfcheck": ArticleEntry(id: "ch18_selfcheck", filename: "ch18_selfcheck.html", title: "Self-Check — Chapter 18", chapterFolder: chapter18Folder, estimatedMinutes: 7),
        "ch19_selfcheck": ArticleEntry(id: "ch19_selfcheck", filename: "ch19_selfcheck.html", title: "Self-Check — Chapter 19", chapterFolder: chapter19Folder, estimatedMinutes: 7),

        // Story Mode (narrative scenes from real life) — Ch.2-19
        // generated 2026-05-26 by scripts/generate_storymode_articles.py
        // weaving chapter.realWorldExamples into vignettes.
        "ch02_storymode": ArticleEntry(id: "ch02_storymode", filename: "ch02_storymode.html", title: "Story Mode — Chapter 2", chapterFolder: chapter2Folder, estimatedMinutes: 10),
        "ch03_storymode": ArticleEntry(id: "ch03_storymode", filename: "ch03_storymode.html", title: "Story Mode — Chapter 3", chapterFolder: chapter3Folder, estimatedMinutes: 10),
        "ch04_storymode": ArticleEntry(id: "ch04_storymode", filename: "ch04_storymode.html", title: "Story Mode — Chapter 4", chapterFolder: chapter4Folder, estimatedMinutes: 10),
        "ch05_storymode": ArticleEntry(id: "ch05_storymode", filename: "ch05_storymode.html", title: "Story Mode — Chapter 5", chapterFolder: chapter5Folder, estimatedMinutes: 10),
        "ch06_storymode": ArticleEntry(id: "ch06_storymode", filename: "ch06_storymode.html", title: "Story Mode — Chapter 6", chapterFolder: chapter6Folder, estimatedMinutes: 10),
        "ch07_storymode": ArticleEntry(id: "ch07_storymode", filename: "ch07_storymode.html", title: "Story Mode — Chapter 7", chapterFolder: chapter7Folder, estimatedMinutes: 10),
        "ch08_storymode": ArticleEntry(id: "ch08_storymode", filename: "ch08_storymode.html", title: "Story Mode — Chapter 8", chapterFolder: chapter8Folder, estimatedMinutes: 10),
        "ch09_storymode": ArticleEntry(id: "ch09_storymode", filename: "ch09_storymode.html", title: "Story Mode — Chapter 9", chapterFolder: chapter9Folder, estimatedMinutes: 10),
        "ch10_storymode": ArticleEntry(id: "ch10_storymode", filename: "ch10_storymode.html", title: "Story Mode — Chapter 10", chapterFolder: chapter10Folder, estimatedMinutes: 10),
        "ch11_storymode": ArticleEntry(id: "ch11_storymode", filename: "ch11_storymode.html", title: "Story Mode — Chapter 11", chapterFolder: chapter11Folder, estimatedMinutes: 10),
        "ch12_storymode": ArticleEntry(id: "ch12_storymode", filename: "ch12_storymode.html", title: "Story Mode — Chapter 12", chapterFolder: chapter12Folder, estimatedMinutes: 10),
        "ch13_storymode": ArticleEntry(id: "ch13_storymode", filename: "ch13_storymode.html", title: "Story Mode — Chapter 13", chapterFolder: chapter13Folder, estimatedMinutes: 10),
        "ch14_storymode": ArticleEntry(id: "ch14_storymode", filename: "ch14_storymode.html", title: "Story Mode — Chapter 14", chapterFolder: chapter14Folder, estimatedMinutes: 10),
        "ch15_storymode": ArticleEntry(id: "ch15_storymode", filename: "ch15_storymode.html", title: "Story Mode — Chapter 15", chapterFolder: chapter15Folder, estimatedMinutes: 10),
        "ch16_storymode": ArticleEntry(id: "ch16_storymode", filename: "ch16_storymode.html", title: "Story Mode — Chapter 16", chapterFolder: chapter16Folder, estimatedMinutes: 10),
        "ch17_storymode": ArticleEntry(id: "ch17_storymode", filename: "ch17_storymode.html", title: "Story Mode — Chapter 17", chapterFolder: chapter17Folder, estimatedMinutes: 10),
        "ch18_storymode": ArticleEntry(id: "ch18_storymode", filename: "ch18_storymode.html", title: "Story Mode — Chapter 18", chapterFolder: chapter18Folder, estimatedMinutes: 10),
        "ch19_storymode": ArticleEntry(id: "ch19_storymode", filename: "ch19_storymode.html", title: "Story Mode — Chapter 19", chapterFolder: chapter19Folder, estimatedMinutes: 10),
    ]
}
