#!/usr/bin/env python3
"""P1-D — add `bossQuestions: [Question]` arrays to every NEP Sanskrit chapter.

The Sanskrit pack (`sanskrit_class7.json`) shipped with zero bossQuestions.
Boss questions are the high-difficulty pool the v6 adaptive journey (Phase 3)
escalates into and a feeder for the Olympiad ladder (Phase 5); with none
present, the adaptive difficulty ceiling for Sanskrit was just the `ncertQA`/
topic sets. This script adds 6 textbook-faithful boss questions per NEP chapter
(`sch01`–`sch15`, 90 total), each:

  * id in the canonical collision-free shape `bossquiz_schNN_qII` (the `sch`
    namespace token keeps Sanskrit ids distinct from Science `ch`, Maths `mch`
    and Social Science `ssch` — enforced by scripts/check_quiz_id_format.py and
    the SubjectRegistry global question index),
  * difficulty 3..5 (boss tier; difficulty>=3 requires non-empty solutionSteps),
  * a 4-option MCQ with the answer present among them,
  * worked `solutionSteps`, >=1 `commonMistakes` note, >=1 re-drill `variation`,
  * `pageRefs` inside the chapter's real NCERT page range,
  * `source: "boss_quiz"`, `needsHumanReview: false`.

The legacy `ch01` vocabulary deck is the documented carve-out (CLAUDE.md): it is
SKIPPED here — adding `bossquiz_ch01_*` ids would collide with Science's `ch01`
boss ids, and ch01 is exempt from the NEP parity ratchets. The mirror test
(`SanskritBossQuestionsTests`) exempts it likewise.

Content is grounded in the pack's own concept `explanations` (Devanagari/IAST
checked against the NEP Sanskrit Grade-7 text). Additive only. Re-runnable
(idempotent: overwrites the bossQuestions key). Writes the canonical format
`json.dumps(d, ensure_ascii=False, indent=2) + "\n"` so verify_pack_roundtrip.py
stays byte-for-byte green (Devanagari survives with ensure_ascii=False).
"""
import json
from pathlib import Path

PACK = Path(__file__).resolve().parent.parent / "desktopAhaan/Subjects/Packs/sanskrit_class7.json"

PER_CHAPTER = 6
LEGACY_DECK = "ch01"  # carve-out: skipped (its bossquiz_ch01_* would collide with Science)


def v(prompt, answer, steps):
    return {"prompt": prompt, "answer": answer, "solutionSteps": steps}


def q(prompt, options, answer, steps, mistakes, variations, difficulty, pages):
    assert answer in options, f"answer {answer!r} not in options {options}"
    assert 3 <= difficulty <= 5, f"boss difficulty must be 3..5, got {difficulty}"
    assert steps, "difficulty>=3 requires non-empty solutionSteps"
    assert mistakes, "boss question must carry at least one commonMistakes note"
    assert variations, "boss question must carry at least one variation"
    return {
        "prompt": prompt,
        "questionType": "mcq",
        "options": options,
        "answer": answer,
        "solutionSteps": steps,
        "commonMistakes": mistakes,
        "variations": variations,
        "difficulty": difficulty,
        "pageRefs": pages,
        "needsHumanReview": False,
        "source": "boss_quiz",
    }


BOSS = {
    # ───────────────── sch01 — वन्दे भारतमातरम् (Vande Mataram) ──────────
    "sch01": [
        q("What does वन्दे मातरम् most nearly mean?",
          ["I bow to the Mother (the Motherland)", "Victory to the Mother",
           "O Mother, come to me", "The Mother is great"],
          "I bow to the Mother (the Motherland)",
          ["वन्दे is from the root वन्द्, 'to salute / bow with respect'.",
           "मातरम् is 'the Mother' (here, the Motherland) in the accusative.",
           "So वन्दे मातरम् = 'I bow to / I praise the Mother'."],
          ["'Victory to the Mother' would be जय मातरम् — वन्दे means bowing in reverence, not shouting victory."],
          [v("What does the single word वन्दे mean?", "I bow / I salute",
             ["वन्दे is 1st-person singular of वन्द् ('to salute').",
              "It means 'I bow' or 'I salute'."])],
          3, [7, 8]),
        q("Who composed वन्दे मातरम्?",
          ["Bankim Chandra Chattopadhyay", "Rabindranath Tagore",
           "Subramania Bharati", "Bharatendu Harishchandra"],
          "Bankim Chandra Chattopadhyay",
          ["The chapter names the poet बङ्किमचन्द्रः चट्टोपाध्यायः.",
           "He set वन्दे मातरम् within one of his उपन्यास (novels).",
           "So the composer is Bankim Chandra Chattopadhyay."],
          ["Rabindranath Tagore composed जन-गण-मन (the national ANTHEM); वन्दे मातरम् (the national SONG) is by Bankim Chandra."],
          [v("The word उपन्यासम्, used for where वन्दे मातरम् appeared, means what?",
             "a novel (a long story-book)",
             ["उपन्यासम् = 'a novel'.",
              "वन्दे मातरम् first appeared inside Bankim Chandra's novel."])],
          4, [7, 8]),
        q("In the hymn, पर्वतराजः ('the king of mountains') is a name for which mountain?",
          ["the Himālaya", "the Vindhya", "the Aravalli", "the Western Ghats"],
          "the Himālaya",
          ["पर्वत = mountain, राजः = king; the compound means 'king of mountains'.",
           "The greatest of India's mountains is the Himālaya.",
           "So पर्वतराजः denotes the Himālaya."],
          ["The Vindhya and Aravalli are smaller ranges — the 'king' of mountains is specifically the Himālaya."],
          [v("रत्नाकरः ('mine of jewels') in the hymn is a name for what?",
             "the ocean / sea",
             ["रत्न = jewel, आकरः = mine/store.",
              "The 'store of jewels' is a poetic name for the ocean."])],
          4, [8, 9]),
        q("रत्नाकरः literally means 'mine of jewels'. In describing the Motherland it stands for…",
          ["the ocean / sea", "a royal treasury", "the Himālaya", "a holy river"],
          "the ocean / sea",
          ["रत्नाकरः = रत्न ('jewel') + आकरः ('mine, store').",
           "The sea, which holds pearls, corals and gems, is poetically the 'mine of jewels'.",
           "So रत्नाकरः means the ocean."],
          ["The literal 'jewel-store' tempts the answer 'treasury', but रत्नाकरः is a fixed poetic kenning for the SEA."],
          [v("सस्यश्यामला describes the land as…", "dark-green, thick with crops",
             ["सस्य = crops, श्यामला = dark-green.",
              "So the land is pictured as densely green with crops."])],
          4, [8, 9]),
        q("In स्वेदबिन्दुभिः सिञ्चन्ति ('they water the land with drops of sweat'), the ending -भिः on स्वेदबिन्दुभिः marks which case?",
          ["तृतीया (instrumental — 'by/with')", "चतुर्थी (dative — 'to/for')",
           "षष्ठी (genitive — 'of')", "सप्तमी (locative — 'in/on')"],
          "तृतीया (instrumental — 'by/with')",
          ["The sense is 'with / by means of sweat-drops' — the means of an action.",
           "The 'by/with' relationship is the instrumental case (तृतीया विभक्ति).",
           "Its plural ending is -भिः, exactly the form here."],
          ["-भिः is the instrumental PLURAL ending; the dative would be -भ्यः and the genitive -आनाम्."],
          [v("Which case expresses 'by means of' in Sanskrit?",
             "तृतीया (instrumental)",
             ["'By / with / by means of' is the instrumental.",
              "That is the तृतीया विभक्ति."])],
          5, [8, 9]),
        q("सस्यश्यामला pictures the Motherland as…",
          ["dark-green, densely covered with crops", "golden with ripe grain",
           "white with mountain snow", "red with blossoming flowers"],
          "dark-green, densely covered with crops",
          ["सस्य means 'crops'; श्यामला means 'dark / dark-green'.",
           "Together: 'dark-green with (abundant) crops'.",
           "So it praises the land's lush, crop-covered greenery."],
          ["श्यामला is 'dark-green', not 'golden' — the image is of thriving green fields, not ripe yellow grain."],
          [v("तीर्थक्षेत्राणि in the hymn means…", "holy places / pilgrimage sites",
             ["तीर्थ = a holy crossing/place, क्षेत्र = a field/region.",
              "Together: places of pilgrimage."])],
          4, [8, 9]),
    ],
    # ───────────────── sch02 — सुभाषितानि (Wise Sayings) ────────────────
    "sch02": [
        q("The subhāṣita जलबिन्दुनिपातेन क्रमशः पूर्यते घटः teaches that…",
          ["small steady efforts add up to a big result",
           "haste makes waste", "a leaking pot is useless", "water is the most precious thing"],
          "small steady efforts add up to a big result",
          ["जलबिन्दुनिपातेन = 'by the falling of (single) water-drops'.",
           "क्रमशः पूर्यते घटः = 'the pot fills up gradually'.",
           "The lesson: little by little, persistent effort completes a great task."],
          ["The verse is not about water itself — the drop-by-drop pot is a METAPHOR for steady effort building knowledge and wealth."],
          [v("The same idea applies to gaining knowledge how?",
             "a little at a time, steadily",
             ["Just as drops fill a pot, study done bit by bit accumulates.",
              "Steady, regular effort is the point."])],
          4, [21, 22]),
        q("The subhāṣita lists five qualities — all beginning with व — that bring a person honour. Which set is correct?",
          ["विद्या, वपुस्, वाणी, वस्त्र, विनय", "विद्या, धन, बल, यश, सुख",
           "वायु, वरुण, वह्नि, वसु, विष्णु", "विवेक, विनय only"],
          "विद्या, वपुस्, वाणी, वस्त्र, विनय",
          ["The 'पञ्च वकाराः' are five honour-bringing qualities whose names all start with व.",
           "They are विद्या (learning), वपुस् (a fine body), वाणी (good speech), वस्त्र (dress), विनय (humility).",
           "Only this set has all five व-words."],
          ["धन, बल, यश do not begin with व, so they cannot be among the 'पञ्च वकाराः' however valuable they are."],
          [v("Which of these IS one of the पञ्च वकाराः?", "विनय (humility)",
             ["विनय ('humility') begins with व and is on the list.",
              "It is one of the five honour-bringing qualities."])],
          5, [21, 22]),
        q("The verse on षड् दोषाः names six faults a person seeking prosperity must give up. Which is one of them?",
          ["procrastination (दीर्घसूत्रता)", "generosity", "curiosity", "study"],
          "procrastination (दीर्घसूत्रता)",
          ["The six faults are निद्रा (sleep), तन्द्रा (drowsiness), भयम् (fear), क्रोध (anger), आलस्य (laziness) and दीर्घसूत्रता (procrastination).",
           "दीर्घसूत्रता — the habit of dragging tasks out — is explicitly one of them.",
           "These are faults to ABANDON, not virtues."],
          ["Generosity, curiosity and study are good qualities — they are the opposite of the six faults to give up."],
          [v("दीर्घसूत्रता (literally 'long-threadedness') names which habit?",
             "procrastination — putting work off",
             ["The 'long thread' idiom means dragging a task out.",
              "It names procrastination."])],
          5, [21, 22]),
        q("According to the शुद्धि subhāṣita, the mind (मनस्) is purified by…",
          ["truth (सत्य)", "water", "knowledge alone", "austerity alone"],
          "truth (सत्य)",
          ["The verse pairs each thing with what cleans it.",
           "The body is cleaned by water, but the MIND is cleaned by truth (सत्य).",
           "(The soul by learning + austerity, the intellect by knowledge.)"],
          ["Water purifies the BODY, not the mind — matching each cleanser to the right thing is the whole point of the verse."],
          [v("In the same verse, what purifies the body (शरीरम्)?",
             "water (जल)",
             ["The body is cleaned by water.",
              "Each item has its own purifier."])],
          4, [22, 23]),
        q("The word सङ्गतिः, stressed in this lesson, means…",
          ["the company one keeps (association)", "a song", "a gathering for battle", "counting"],
          "the company one keeps (association)",
          ["सङ्गतिः comes from सम् + गम् ('to go together').",
           "It means the company or association one keeps.",
           "The lesson warns that one becomes like the company one keeps."],
          ["सङ्गतिः is about COMPANY/association — not a song (गीतम्) nor counting (गणना), which merely sound similar in English glosses."],
          [v("प्रेरकः means…", "one who inspires (a motivator)",
             ["प्रेरकः is from प्र + ईर् ('to set in motion').",
              "It means one who inspires or motivates."])],
          4, [23, 24]),
        q("रिपुः means…",
          ["enemy, foe", "friend", "teacher", "king"],
          "enemy, foe",
          ["रिपुः is a noun meaning 'enemy'.",
           "It is a synonym of शत्रुः.",
           "So रिपुः = foe / enemy."],
          ["रिपुः is the opposite of मित्रम् ('friend') — don't confuse the foe-word with the friend-word."],
          [v("मित्रम् means…", "friend",
             ["मित्रम् is 'friend', the opposite of रिपुः.",
              "So मित्रम् = friend."])],
          3, [23, 24]),
    ],
    # ──────────────── sch03 — मित्राय नमः (Salutation to the Sun) ───────
    "sch03": [
        q("Why is it मित्राय नमः and not मित्रः नमः?",
          ["नमः ('salutation to') governs the dative (चतुर्थी), so मित्र → मित्राय",
           "मित्राय is the plural of मित्रः",
           "मित्राय is a past-tense form",
           "it is only for euphony, with no rule behind it"],
          "नमः ('salutation to') governs the dative (चतुर्थी), so मित्र → मित्राय",
          ["नमः means 'salutation TO' — the 'to' must be shown grammatically.",
           "The word for the one saluted goes into the चतुर्थी विभक्ति (dative).",
           "So मित्र becomes मित्राय: 'salutation to Mitra'."],
          ["मित्रः is the nominative (subject) form; after नमः the noun must be dative (मित्राय), not nominative."],
          [v("After नमः, the noun for the one saluted takes which case?",
             "the dative (चतुर्थी)",
             ["नमः idiomatically takes the dative.",
              "So the saluted one ends in the चतुर्थी form."])],
          5, [29, 30]),
        q("An अकारान्त (a-ending) masculine noun like छात्र forms its dative (चतुर्थी) singular as…",
          ["छात्राय", "छात्रः", "छात्रम्", "छात्रेण"],
          "छात्राय",
          ["The dative singular of अकारान्त masculines adds the ending -आय.",
           "छात्र + आय = छात्राय ('to/for the student').",
           "This is the same pattern as मित्र → मित्राय."],
          ["छात्रम् is the accusative (object) and छात्रेण the instrumental — the dative 'to/for' form is छात्राय."],
          [v("Form the dative of देव (an अकारान्त masculine).",
             "देवाय",
             ["Add -आय to the अकारान्त stem.",
              "देव + आय = देवाय ('to/for God')."])],
          4, [31, 32]),
        q("Which of these is one of the सूर्यस्य द्वादश नामानि (twelve names of the Sun)?",
          ["भास्करः", "चन्द्रः", "इन्द्रः", "वरुणः"],
          "भास्करः",
          ["The twelve sun-names include मित्रः, रविः, सूर्यः, भानुः, आदित्यः, सविता, अर्कः and भास्करः.",
           "भास्करः ('the light-maker') is one of them.",
           "So भास्करः is a correct sun-name."],
          ["चन्द्रः is the MOON, and इन्द्रः/वरुणः are other deities — none is among the twelve names of the Sun."],
          [v("Name another of the Sun's twelve names.", "आदित्यः",
             ["आदित्यः is listed among the twelve sun-names.",
              "So आदित्यः is correct."])],
          4, [30, 31]),
        q("सूर्यनमस्कारः means…",
          ["salutation to the Sun (a sequence of yoga postures)",
           "sunrise", "a sun-shaped lamp", "a solar eclipse"],
          "salutation to the Sun (a sequence of yoga postures)",
          ["सूर्य = the Sun; नमस्कारः = salutation.",
           "Together: 'salutation to the Sun', performed as a set of yoga postures.",
           "Each posture has its own sun-name mantra."],
          ["It is the ACT of saluting the Sun (with postures), not sunrise or an eclipse."],
          [v("स्वस्थम्, a benefit of सूर्यनमस्कार, means…", "healthy",
             ["स्वस्थम् = 'healthy / well'.",
              "सूर्यनमस्कार gives a healthy body and mind."])],
          3, [28, 29]),
        q("The chapter says सूर्यनमस्कार grants तेजः. तेजः means…",
          ["brilliance / radiant energy", "fear", "sleep", "wealth"],
          "brilliance / radiant energy",
          ["तेजः denotes radiant energy, splendour, brilliance.",
           "It is one of the gifts (with प्रज्ञा and वीर्यम्) the Sun-salute confers.",
           "So तेजः = brilliance / radiance."],
          ["तेजः is positive energy/radiance — not fear (भयम्) or sleep (निद्रा)."],
          [v("वीर्यम्, another gift named, means…", "vigour / strength / valour",
             ["वीर्यम् = vigour, strength, valour.",
              "It is another benefit of the Sun-salute."])],
          4, [31, 32]),
        q("The चतुर्थी विभक्ति (dative) most basically expresses which relationship?",
          ["to / for (the recipient or purpose)", "by / with (the means)",
           "from (the origin)", "in / on (the location)"],
          "to / for (the recipient or purpose)",
          ["Each case carries a core meaning.",
           "The dative (चतुर्थी) marks the one TO or FOR whom something is done.",
           "So its core sense is 'to / for'."],
          ["'By/with' is the instrumental (तृतीया) and 'from' is the ablative (पञ्चमी) — the dative is specifically 'to/for'."],
          [v("नमः मित्राय — translate मित्राय.", "'to Mitra'",
             ["मित्राय is the dative of मित्र.",
              "It means 'to/for Mitra'."])],
          5, [31, 32]),
    ],
    # ──────────────── sch04 — शृगालः द्राक्षा च (The Fox and the Grapes) ─
    "sch04": [
        q("When the fox cannot reach the grapes, he calls them आम्लम् ('sour'). What is the fable's moral?",
          ["we belittle what we cannot attain ('sour grapes')",
           "grapes are always sour", "foxes cannot climb", "one should never give up"],
          "we belittle what we cannot attain ('sour grapes')",
          ["The fox jumps again and again but cannot reach the grapes.",
           "Failing, he saves face by declaring them sour.",
           "The moral: people scorn what they cannot get — the 'sour grapes' lesson."],
          ["The grapes were not really sour — आम्लम् is the fox's excuse, so the moral is about face-saving, not about fruit."],
          [v("The fox's claim 'the grapes are sour' is best described as…",
             "an excuse to hide his failure",
             ["He could not reach them, so he pretended not to want them.",
              "It is a face-saving excuse."])],
          4, [42, 43]),
        q("आम्लम् means…",
          ["sour", "sweet", "ripe", "red"],
          "sour",
          ["आम्लम् is the word for the 'sour' taste.",
           "The fox declares the unreachable grapes आम्लम्.",
           "So आम्लम् = sour."],
          ["आम्लम् is 'sour', the opposite of मधुरम् ('sweet')."],
          [v("The opposite of आम्लम् (sour) is…", "मधुरम् (sweet)",
             ["मधुरम् means 'sweet'.",
              "It is the opposite of आम्लम् ('sour')."])],
          3, [40, 41]),
        q("शृगालः, the main character of the story, is a…",
          ["fox / jackal", "crow", "lion", "deer"],
          "fox / jackal",
          ["शृगालः is the Sanskrit word for a fox or jackal.",
           "He is the one who tries to reach the grapes.",
           "So शृगालः = fox / jackal."],
          ["शृगालः is the fox — not the crow (वायसः) or lion (सिंहः) of other fables."],
          [v("द्राक्षालता means…", "a grape-vine / grape creeper",
             ["द्राक्षा = grapes, लता = creeper/vine.",
              "Together: a grape-vine."])],
          3, [40, 41]),
        q("The suffix -तः makes direction words. Which one means 'on the right'?",
          ["दक्षिणतः", "वामतः", "अग्रतः", "पृष्ठतः"],
          "दक्षिणतः",
          ["दक्षिण means 'right (side)'; adding -तः gives 'on the right'.",
           "So दक्षिणतः = 'on the right'.",
           "(The -तः / तसिल् suffix turns a word into a 'from/at that side' adverb.)"],
          ["वामतः = on the LEFT, अग्रतः = in FRONT, पृष्ठतः = BEHIND — only दक्षिणतः means 'on the right'."],
          [v("Which -तः word means 'in front'?", "अग्रतः",
             ["अग्र = front; अग्रतः = 'in front'.",
              "So अग्रतः is correct."])],
          5, [42, 43]),
        q("उत्पतति describes the fox's action. It means…",
          ["he jumps / leaps up", "he lies down", "he runs away", "he falls asleep"],
          "he jumps / leaps up",
          ["उत्पतति = उत् ('up') + पतति ('moves/flies').",
           "So it means 'leaps up, jumps upward'.",
           "The fox उत्पतति again and again to reach the grapes."],
          ["उत् ('up') + पत् gives 'jump UP' — not 'fall down', even though पत् can also mean 'fall'."],
          [v("श्रान्तः, the fox's state after trying, means…", "tired / exhausted",
             ["श्रान्तः = 'tired'.",
              "After leaping repeatedly, the fox is exhausted."])],
          4, [42, 43]),
        q("After failing again and again, the fox is श्रान्तः. श्रान्तः means…",
          ["tired / exhausted", "angry", "thirsty", "happy"],
          "tired / exhausted",
          ["श्रान्तः is a past participle meaning 'tired, exhausted'.",
           "It describes the fox after his repeated jumping.",
           "So श्रान्तः = tired."],
          ["'Thirst' is पिपासा / तृषा — श्रान्तः specifically means 'tired', not 'thirsty', though both fit a weary traveler."],
          [v("पिपासा / तृषा means…", "thirst",
             ["Both पिपासा and तृषा mean 'thirst'.",
              "They name the desire to drink."])],
          4, [40, 41]),
    ],
    # ──────────────── sch05 — सेवा हि परमो धर्मः (Service Is Highest) ────
    "sch05": [
        q("The title सेवा हि परमो धर्मः means…",
          ["service is indeed the highest duty", "service is a difficult duty",
           "service brings great wealth", "duty is harder than service"],
          "service is indeed the highest duty",
          ["सेवा = service; हि = indeed; परमः = highest; धर्मः = duty.",
           "Put together: 'service is indeed the highest duty'.",
           "The chapter ranks selfless service above rank and title."],
          ["हि is an emphatic 'indeed', not 'difficult' — the line praises service, it does not call it hard."],
          [v("परमो धर्मः (from परमः + धर्मः) means…", "the highest duty",
             ["परमः = highest, धर्मः = duty.",
              "Together: the highest duty."])],
          4, [48, 49]),
        q("चिकित्सकः means…",
          ["a physician / doctor", "a soldier", "a teacher", "a cook"],
          "a physician / doctor",
          ["चिकित्सकः comes from चिकित्सा ('medical treatment').",
           "It means one who treats the sick — a physician.",
           "In the lesson the चिकित्सकः embodies selfless service."],
          ["चिकित्सकः is specifically a DOCTOR/physician, not a soldier or teacher."],
          [v("कषायम्, the medicine in the lesson, is…", "a herbal decoction (kāḍhā)",
             ["कषायम् is a herbal decoction.",
              "It is the medicine, not the illness."])],
          3, [50, 51]),
        q("The physician serves यन्त्रवत्. यन्त्रवत् means…",
          ["like a machine (tirelessly)", "unwillingly", "only for money", "very slowly"],
          "like a machine (tirelessly)",
          ["यन्त्र = machine; the suffix -वत् means 'like'.",
           "So यन्त्रवत् = 'like a machine'.",
           "It praises tireless, untiring service."],
          ["The -वत् suffix means 'like' — यन्त्रवत् is 'like a machine (tireless)', not 'made of machinery'."],
          [v("The suffix -वत् (as in यन्त्रवत्) means…", "'like / resembling'",
             ["-वत् forms a 'like X' adverb/adjective.",
              "So यन्त्रवत् = 'like a machine'."])],
          4, [50, 51]),
        q("The chapter ranks सेवा (service) above which of these?",
          ["one's position and academic degree", "truth itself",
           "the gods", "one's own family"],
          "one's position and academic degree",
          ["The lesson contrasts सेवा with उपाधिः (a degree) and पदवी (a position/rank).",
           "It teaches that service (परमो धर्मः) is higher than mere title or rank.",
           "So service is ranked above one's position and degree."],
          ["The chapter's contrast is service vs. rank/title — it does not rank service above truth or the gods."],
          [v("उपाधिः means…", "an academic degree / title",
             ["उपाधिः = a degree or title.",
              "The lesson values service above it."])],
          5, [49, 50]),
        q("उपाधिः means an academic degree; पदवी means…",
          ["a position, designation or rank", "a degree", "a medicine", "a salary"],
          "a position, designation or rank",
          ["पदवी denotes one's position, designation or rank.",
           "It is distinct from उपाधिः (a degree).",
           "So पदवी = a position / rank."],
          ["उपाधिः (degree) and पदवी (rank) are different — पदवी is the post or designation, not the qualification."],
          [v("मानवीयाः means…", "humane (befitting a human)",
             ["मानवीयाः derives from मानव ('human').",
              "It means 'humane'."])],
          4, [51, 52]),
        q("कषायम् in this lesson means…",
          ["a herbal decoction (kāḍhā)", "a bandage", "a fever", "a hospital"],
          "a herbal decoction (kāḍhā)",
          ["कषायम् is a medicinal herbal decoction (kāḍhā).",
           "The serving physician prepares it for the sick.",
           "So कषायम् = a herbal decoction."],
          ["कषायम् is the MEDICINE (the decoction), not the illness (a fever) it treats."],
          [v("The one who prepares कषायम् for the sick is the…",
             "चिकित्सकः (physician)",
             ["The physician (चिकित्सकः) treats the sick.",
              "He prepares the कषायम्."])],
          4, [50, 51]),
    ],
    # ──────────────── sch06 — श्लोकान्त्याक्षरी (Shloka Antyakshari) ─────
    "sch06": [
        q("In श्लोकान्त्याक्षरी, each new shloka must begin with…",
          ["the last letter (अन्त्य अक्षर) of the previous shloka",
           "the first letter of the previous shloka",
           "any letter the player likes", "the poet's name"],
          "the last letter (अन्त्य अक्षर) of the previous shloka",
          ["श्लोक + अन्त्य ('last') + अक्षरी = a game on the LAST letter of shlokas.",
           "Each player must recite a shloka starting with the final letter of the one before.",
           "So the rule is: begin with the previous shloka's last letter."],
          ["It is the LAST letter (अन्त्य), not the first — that is what 'अन्त्याक्षरी' literally names."],
          [v("The word अन्त्य means…", "last / final",
             ["अन्त्य = 'last/final'.",
              "अन्त्याक्षरी = a game on the last letter."])],
          4, [57, 58]),
        q("विद्याहीनाः न शोभन्ते निर्गन्धाः इव किंशुकाः compares people without knowledge to…",
          ["किंशुक flowers — beautiful but without fragrance",
           "fragrant lotuses", "thornless roses", "ripe sweet fruit"],
          "किंशुक flowers — beautiful but without fragrance",
          ["विद्याहीनाः = those lacking knowledge; न शोभन्ते = 'do not shine'.",
           "निर्गन्धाः इव किंशुकाः = 'like scentless किंशुक (palāśa) flowers'.",
           "Though किंशुक blossoms look lovely, they have no fragrance — like a handsome but unlearned person."],
          ["The point is that किंशुक flowers LOOK fine but lack fragrance — knowledge is the 'fragrance' a person needs to truly shine."],
          [v("निर्गन्धाः means…", "without fragrance / scentless",
             ["निर् ('without') + गन्ध ('smell') = scentless.",
              "So निर्गन्धाः = without fragrance."])],
          5, [58, 59]),
        q("विद्या विवादाय धनं मदाय शक्तिः परेषां परिपीडनाय — in a WICKED person, knowledge, wealth and power become…",
          ["quarrel, pride, and oppression of others",
           "peace, charity, and protection", "fame, joy, and victory",
           "study, service, and strength"],
          "quarrel, pride, and oppression of others",
          ["विवादाय = 'for quarrel', मदाय = 'for pride', परिपीडनाय = 'for tormenting others'.",
           "So in the wicked, विद्या→quarrel, धन→pride, शक्ति→oppression.",
           "The same gifts that help a good person harm in the wicked."],
          ["These dative forms (-आय) all mean 'for the sake of (harm)' — the verse shows the SAME gifts turning bad in bad hands."],
          [v("The -आय endings in विवादाय, मदाय, परिपीडनाय mark which case?",
             "the dative (चतुर्थी) — 'for the sake of'",
             ["-आय is the dative singular ending.",
              "Here it means 'for (the purpose of)'."])],
          5, [59, 60]),
        q("खलः means…",
          ["a wicked, evil-minded person", "a farmer", "a king", "a poet"],
          "a wicked, evil-minded person",
          ["खलः denotes a wicked or evil-natured person.",
           "The lesson contrasts the खलः with the good (सज्जन).",
           "So खलः = a wicked person."],
          ["खलः is the WICKED person — the opposite of the सज्जन (good person), not a neutral farmer or king."],
          [v("शीलम् means…", "good character / moral conduct",
             ["शीलम् = good character.",
              "It is the virtue the lesson prizes."])],
          3, [60, 61]),
        q("People without virtue are called भारभूताः, meaning they are…",
          ["a burden on the earth", "leaders of men", "blessed by the gods", "rich and famous"],
          "a burden on the earth",
          ["भार = burden/load; भूताः = 'become / those who are'.",
           "भारभूताः = 'those who have become a burden (on the earth)'.",
           "It is the verse's harsh image for people without knowledge or virtue."],
          ["भार means 'burden' — the phrase calls the virtueless a weight on the world, not leaders or the blessed."],
          [v("भार in भारभूताः means…", "burden / load",
             ["भार = 'burden'.",
              "भारभूताः = those who are a burden."])],
          4, [60, 61]),
        q("यशस्विनी means…",
          ["fame-bearing, renowned (feminine)", "wealthy", "beautiful", "wise"],
          "fame-bearing, renowned (feminine)",
          ["यशस् = 'fame'; the suffix -विन् makes 'possessing'; -ई is the feminine ending.",
           "So यशस्विनी = 'a (woman) possessing fame', i.e. renowned.",
           "It describes someone who has earned fame."],
          ["यशस्विनी is about FAME (यशस्), not wealth (which is लक्ष्मीः) — the root word is 'fame', not 'riches'."],
          [v("लक्ष्मीः means…", "wealth / fortune (also the goddess)",
             ["लक्ष्मीः = wealth/fortune.",
              "It is also the goddess of prosperity."])],
          4, [61, 62]),
    ],
    # ──────────────── sch07 — ईशावास्यम् इदं सर्वम् ─────────────────────
    "sch07": [
        q("ईशावास्यम् इदं सर्वम् means…",
          ["all this (the universe) is pervaded by the Lord",
           "this is the only truth", "God lives in temples", "everything will perish"],
          "all this (the universe) is pervaded by the Lord",
          ["ईश-आवास्यम् = 'to be enveloped/inhabited by the Lord'.",
           "इदं सर्वम् = 'all this' (the whole world).",
           "So: 'all this is pervaded by the Lord'."],
          ["The teaching is that the divine pervades EVERYTHING — not that God is confined to temples."],
          [v("इदं सर्वम् means…", "all this (everything)",
             ["इदम् = 'this', सर्वम् = 'all'.",
              "Together: 'all this / everything'."])],
          4, [66, 67]),
        q("सर्वशक्तिमान् means…",
          ["all-powerful (omnipotent)", "all-knowing", "everywhere at once", "eternal"],
          "all-powerful (omnipotent)",
          ["सर्व = 'all'; शक्ति = 'power'; -मान् = 'possessing'.",
           "So सर्वशक्तिमान् = 'possessing all power' = all-powerful.",
           "It describes the Lord's omnipotence."],
          ["सर्वशक्तिमान् is 'all-POWERFUL' (शक्ति = power) — 'all-knowing' would use ज्ञान, not शक्ति."],
          [v("The suffix -मान् (as in शक्तिमान्) means…", "'possessing / having'",
             ["-मान् makes 'possessing X'.",
              "शक्तिमान् = 'possessing power'."])],
          3, [66, 67]),
        q("यक्षाः, गन्धर्वाः, किन्नराः are…",
          ["classes of semi-divine beings", "kinds of demons / enemies",
           "great sages", "ancient kings"],
          "classes of semi-divine beings",
          ["These three are traditional classes of celestial / semi-divine beings.",
           "गन्धर्वाः are heavenly musicians; यक्षाः and किन्नराः are other semi-divine folk.",
           "So they are semi-divine beings."],
          ["They are SEMI-DIVINE beings, not demons (राक्षसाः) — gandharvas, for instance, are heavenly singers."],
          [v("गन्धर्वाः are best known as…", "heavenly musicians",
             ["गन्धर्वाः are celestial musicians.",
              "They are one class of semi-divine beings."])],
          4, [67, 68]),
        q("दास्यन्ति ('they shall give') is in which tense?",
          ["future", "present", "past", "imperative (command)"],
          "future",
          ["दास्यन्ति carries the future marker (the -स्य- infix of लृट्).",
           "It means 'they SHALL give'.",
           "So it is the future tense, 3rd person plural."],
          ["The present 'they give' would be (य)च्छन्ति/ददति — the -स्य- infix and 'shall' mark दास्यन्ति as FUTURE."],
          [v("ध्यायन्ति ('they meditate') is in which tense?", "present",
             ["ध्यायन्ति has no future infix.",
              "It is the present tense, 'they meditate'."])],
          5, [68, 69]),
        q("ध्यायन्ति means…",
          ["they meditate / contemplate", "they give", "they sing", "they sleep"],
          "they meditate / contemplate",
          ["ध्यायन्ति is the present 3rd-plural of ध्यै ('to meditate').",
           "It means 'they meditate / contemplate'.",
           "The wise ध्यायन्ति upon the divine."],
          ["ध्यायन्ति is 'meditate' (root ध्यै) — not 'give' (दा), even though दास्यन्ति appears nearby."],
          [v("नामकीर्तनम् means…", "singing / chanting the (divine) Name",
             ["नाम = name, कीर्तनम् = praising/chanting.",
              "So it is chanting the divine Name."])],
          4, [68, 69]),
        q("कुलकलङ्कः means…",
          ["a stain / disgrace on one's family", "a family festival",
           "a family deity", "the head of a family"],
          "a stain / disgrace on one's family",
          ["कुल = family; कलङ्कः = stain / blemish.",
           "So कुलकलङ्कः = 'a stain on the family', a disgraceful member.",
           "It is the opposite of one who brings the family honour."],
          ["कलङ्कः means 'stain/blemish' — कुलकलङ्कः is a DISGRACE to the family, not its deity or head."],
          [v("कलङ्कः means…", "a stain / blemish",
             ["कलङ्कः = stain or blemish.",
              "कुलकलङ्कः = a stain on the family."])],
          4, [69, 70]),
    ],
    # ──────────────── sch08 — हितं मनोहारि च दुर्लभं वचः ────────────────
    "sch08": [
        q("हितं मनोहारि च दुर्लभं वचः says that what kind of speech is rare?",
          ["speech that is both useful (हितम्) and pleasing (मनोहारि)",
           "speech that is loud", "speech that is long", "speech kept silent"],
          "speech that is both useful (हितम्) and pleasing (मनोहारि)",
          ["हितम् = beneficial/useful; मनोहारि = 'heart-stealing', pleasing.",
           "दुर्लभं वचः = 'rare is the speech'.",
           "So rare is speech that is BOTH beneficial and pleasing at once."],
          ["The rarity is in combining BOTH qualities — useful speech often stings, pleasing speech is often empty; both together is rare."],
          [v("मनोहारि literally means…", "'heart-stealing' (charming/pleasing)",
             ["मनस् ('mind/heart') + हारि ('stealing').",
              "So मनोहारि = charming, pleasing."])],
          4, [86, 87]),
        q("क्षणशः कणशः विद्यां अर्थं च साधयेत् advises gaining knowledge ___ and wealth ___.",
          ["moment by moment; particle by particle",
           "all at once; very slowly", "by luck; by theft", "from books; from elders"],
          "moment by moment; particle by particle",
          ["क्षणशः = 'moment by moment'; कणशः = 'particle by particle'.",
           "विद्यां ... साधयेत् = 'one should win knowledge'; अर्थं = wealth.",
           "So: gain knowledge moment by moment, wealth particle by particle — both by small steady steps."],
          ["क्षण ('moment', time) pairs with knowledge; कण ('particle', a tiny bit) pairs with wealth — don't swap them."],
          [v("कणशः means…", "particle by particle (bit by bit)",
             ["कण = a particle/grain; -शः = 'by'.",
              "So कणशः = 'particle by particle'."])],
          5, [86, 87]),
        q("विकत्थनम् ('empty boasting') is contrasted with क्रियावान् — a person who…",
          ["acts; a doer", "boasts even more", "stays silent", "is wealthy"],
          "acts; a doer",
          ["विकत्थनम् = empty boasting (mere words).",
           "क्रियावान् = 'one possessing action', a doer.",
           "The lesson prizes action (क्रियावान्) over boasting (विकत्थनम्)."],
          ["क्रियावान् is the opposite of a boaster — it praises DEEDS over talk, not louder talk."],
          [v("क्रियावान् means…", "an active person, a doer",
             ["क्रिया = action; -वान् = 'possessing'.",
              "So क्रियावान् = a person of action."])],
          4, [87, 88]),
        q("सूक्तिः means…",
          ["a good / well-spoken saying", "a song", "a question", "a story"],
          "a good / well-spoken saying",
          ["सु ('well') + उक्ति ('a saying') = सूक्तिः.",
           "It means a well-spoken, wise saying.",
           "It is a synonym of सुभाषितम्."],
          ["सूक्तिः = सु + उक्ति, 'well-spoken' — a wise saying, not a song or story."],
          [v("सूक्तिः is a synonym of which word from Chapter 2?", "सुभाषितम्",
             ["Both mean a wise, well-spoken saying.",
              "So सूक्तिः ≈ सुभाषितम्."])],
          3, [88, 89]),
        q("भाण्डागारः means…",
          ["a storehouse / treasure-trove", "a kitchen", "a bedroom", "a school"],
          "a storehouse / treasure-trove",
          ["भाण्ड ('goods/vessels') + आगारः ('a house/store').",
           "So भाण्डागारः = a storehouse or treasure-trove.",
           "Knowledge is called a भाण्डागार that thieves cannot steal."],
          ["भाण्डागारः is a STOREHOUSE — आगारः means 'house/store', not specifically a kitchen or bedroom."],
          [v("शयनागारम् (from sch12) means…", "a bedroom / sleeping-chamber",
             ["शयन ('sleeping') + आगारम् ('room').",
              "So शयनागारम् = a bedroom."])],
          4, [88, 89]),
        q("कुतूहलम् means…",
          ["curiosity, eager interest", "boredom", "anger", "sleep"],
          "curiosity, eager interest",
          ["कुतूहलम् denotes curiosity or eager interest.",
           "It is the keen wish to learn or see something.",
           "So कुतूहलम् = curiosity."],
          ["कुतूहलम् is positive eager interest — close in sense to जिज्ञासा ('wish to know'), the opposite of boredom."],
          [v("जिज्ञासा (from sch01 and sch09) means…", "the wish / desire to know",
             ["जिज्ञासा = 'desire to know'.",
              "It is curiosity, like कुतूहलम्."])],
          3, [88, 89]),
    ],
    # ──────────────── sch09 — अन्नाद् भवन्ति भूतानि (Gītā 3.14) ──────────
    "sch09": [
        q("अन्नाद् भवन्ति भूतानि is the opening line of verse 3.14 of which text?",
          ["the Bhagavad-gītā", "the Īśopaniṣad", "the Rāmāyaṇa", "the Manusmṛti"],
          "the Bhagavad-gītā",
          ["The chapter states this is the opening line of Gītā 3.14.",
           "It describes the cosmic food-cycle of creation.",
           "So the source is the Bhagavad-gītā."],
          ["Don't confuse it with the Īśopaniṣad line (ईशावास्यम्) of sch07 — this verse is from the Bhagavad-gītā."],
          [v("अन्नाद् भवन्ति भूतानि means…", "from food, (living) beings come into being",
             ["अन्नात् = 'from food'; भूतानि = 'beings'; भवन्ति = 'come to be'.",
              "So: from food, beings arise."])],
          5, [94, 95]),
        q("In अन्नाद् भवन्ति, the form अन्नाद् (from अन्नात्) is in which case, meaning 'from'?",
          ["पञ्चमी (ablative)", "तृतीया (instrumental)", "चतुर्थी (dative)", "षष्ठी (genitive)"],
          "पञ्चमी (ablative)",
          ["The sense 'from food / out of food' marks origin or source.",
           "'From / origin' is the ablative case (पञ्चमी विभक्ति).",
           "The अकारान्त ablative ending is -आत् (अन्न → अन्नात्, here sandhi'd to अन्नाद्)."],
          ["'By/with' would be तृतीया and 'to/for' चतुर्थी — but 'FROM' (origin) is specifically the ablative पञ्चमी."],
          [v("Which case in Sanskrit means 'from' (origin/separation)?",
             "पञ्चमी (ablative)",
             ["'From / out of' is origin.",
              "That is the ablative, पञ्चमी विभक्ति."])],
          5, [94, 95]),
        q("जानीयात् ('one should know') is in which mood, used for advice or duty?",
          ["the optative (विधिलिङ्) — 'should'", "the present", "the past", "the future"],
          "the optative (विधिलिङ्) — 'should'",
          ["The sense 'one SHOULD know' expresses advice or obligation.",
           "Sanskrit marks 'should' with the optative mood, विधिलिङ् (लिङ् लकार).",
           "So जानीयात् is optative."],
          ["'One should know' is not a plain present ('knows') — the 'should' sense requires the optative mood."],
          [v("The Sanskrit mood used for 'should / ought to' is called…",
             "the optative (विधिलिङ्)",
             ["Advice/duty ('should') uses the optative.",
              "It is the विधिलिङ् लकार."])],
          5, [95, 96]),
        q("In this lesson ब्रह्म refers to…",
          ["the all-pervading cosmic source of all", "a priest", "the four Vedas", "a planet"],
          "the all-pervading cosmic source of all",
          ["ब्रह्म (neuter) names the ultimate, all-pervading Cosmic Power.",
           "The verse traces the food-cycle back to ब्रह्म as the source of all.",
           "So ब्रह्म = the all-pervading source of everything."],
          ["ब्रह्म (neuter, the Absolute) is not the same as ब्राह्मणः (a priest) — the words look alike but differ."],
          [v("भूतानि means…", "all living beings / creatures",
             ["भूतानि = 'beings, creatures'.",
              "From food, the भूतानि arise."])],
          4, [94, 95]),
        q("The chapter links the food-cycle to modern रसायनशास्त्रम्, which means…",
          ["chemistry", "astronomy", "biology", "geography"],
          "chemistry",
          ["रसायन = 'chemistry'; शास्त्रम् = 'science/discipline'.",
           "So रसायनशास्त्रम् = the science of chemistry.",
           "The chapter connects the ancient food-cycle to modern chemistry."],
          ["रसायनशास्त्रम् is specifically CHEMISTRY — the study of matter and reactions — not biology or astronomy."],
          [v("उत्पत्तिक्रमम् means…", "the order / sequence of origin",
             ["उत्पत्ति = origin, क्रमम् = order/sequence.",
              "So: the order in which things come to be."])],
          3, [96, 97]),
        q("उत्पत्तिक्रमम् describes…",
          ["the order in which beings come into existence", "a kind of herb",
           "a prayer", "a counting game"],
          "the order in which beings come into existence",
          ["उत्पत्ति = 'coming into being / origin'; क्रमम् = 'order, sequence'.",
           "So उत्पत्तिक्रमम् = the sequence of creation.",
           "The verse lays out this chain: food → beings, rain → food, and so on."],
          ["क्रमम् means 'order/sequence' — उत्पत्तिक्रमम् is about the ORDER of creation, not a herb or prayer."],
          [v("ओषधीनाम् means…", "'of the herbs (medicinal plants)'",
             ["ओषधि = a herb; -ीनाम् = genitive plural ('of').",
              "So ओषधीनाम् = 'of the herbs'."])],
          4, [96, 97]),
    ],
    # ──────────────── sch10 — दशमः कः? (Who Is the Tenth?) ──────────────
    "sch10": [
        q("In दशमः कः?, ten travelers each count only nine. Why does each miss one?",
          ["each forgot to count himself", "the teacher hid one of them",
           "one had truly drowned", "a child wandered off"],
          "each forgot to count himself",
          ["After crossing the river, each man counts the others but leaves HIMSELF out.",
           "So each counts only nine and fears the tenth has drowned.",
           "The teacher shows each is himself the missing tenth."],
          ["No one actually drowned — the 'missing tenth' is the counter himself, whom each forgot to include."],
          [v("The teacher's lesson 'दशमः त्वम् असि' ('you are the tenth') means…",
             "the one you seek is yourself",
             ["Each counter overlooked himself.",
              "So 'you are the tenth' — the sought one was never lost."])],
          5, [104, 105]),
        q("The parable 'Who is the tenth?' is a famous teaching from which tradition, showing that the Self one seeks is already present?",
          ["Vedānta (the Self is never truly lost)", "grammar (vyākaraṇa)",
           "mathematics (gaṇita)", "medicine (āyurveda)"],
          "Vedānta (the Self is never truly lost)",
          ["The chapter presents this as a famous Vedāntic parable.",
           "It teaches that what one frantically searches for — the Self — is already here.",
           "So the tradition is Vedānta."],
          ["Though it involves counting, the parable's POINT is Vedāntic (about the Self), not a maths puzzle."],
          [v("The 'tenth man' you search for, in the parable, stands for…",
             "your own Self",
             ["Each man forgot himself.",
              "The tenth is the Self, never actually missing."])],
          5, [104, 105]),
        q("Which is the correct Sanskrit ordinal for 'tenth'?",
          ["दशमः", "दश", "दशमी", "दशकम्"],
          "दशमः",
          ["दश is the CARDINAL 'ten' (how many).",
           "Adding the ordinal suffix gives दशमः = 'tenth' (which position), masculine.",
           "So the ordinal 'tenth' is दशमः."],
          ["दश means 'ten' (the count); दशमः means 'tenth' (the rank) — the title asks दशमः कः, 'who is the TENTH?'"],
          [v("The Sanskrit ordinal for 'first' is…", "प्रथमः",
             ["प्रथमः = 'first'.",
              "Then द्वितीयः (2nd), तृतीयः (3rd), … दशमः (10th)."])],
          4, [106, 107]),
        q("तीर्त्वा ('having crossed / swum') is which kind of verb form?",
          ["a gerund (क्त्वा, 'having ___ed')", "a future-tense verb",
           "a noun", "an imperative command"],
          "a gerund (क्त्वा, 'having ___ed')",
          ["तीर्त्वा ends in -त्वा, the gerund (absolutive) suffix क्त्वा.",
           "It means 'having crossed', an action done BEFORE the main verb.",
           "So it is a gerund."],
          ["The -त्वा ending marks a gerund ('having ___ed'), not a tense — the men, 'having crossed', then counted."],
          [v("The gerund suffix that means 'having ___ed' is…", "-त्वा (क्त्वा)",
             ["-त्वा forms the gerund/absolutive.",
              "तीर्त्वा = 'having crossed'."])],
          5, [106, 107]),
        q("अगणयत् ('he counted') is in which tense?",
          ["past (imperfect, लङ्)", "present", "future", "optative"],
          "past (imperfect, लङ्)",
          ["अगणयत् begins with the augment अ-, the mark of past tense.",
           "It is the imperfect (लङ् लकार), 3rd-person singular.",
           "So it means 'he counted' in the past."],
          ["The leading अ- augment signals PAST tense — the present 'he counts' would be गणयति, with no अ-."],
          [v("The leading अ- on अगणयत् signals which time?", "the past",
             ["The अ- augment marks past tense.",
              "So अगणयत् = 'he counted' (past)."])],
          4, [106, 107]),
        q("कतमः asks 'which one?' — out of how many?",
          ["out of many (three or more)", "out of exactly two",
           "out of ten only", "out of none"],
          "out of many (three or more)",
          ["Sanskrit distinguishes 'which of two' from 'which of many'.",
           "कतमः asks 'which one of MANY (three or more)?'.",
           "कतरः, by contrast, asks 'which of the TWO?'."],
          ["कतमः (of many) and कतरः (of two) are a precise pair — don't use कतमः when choosing between just two."],
          [v("कतरः asks 'which?' out of how many?", "out of exactly two",
             ["कतरः = 'which of the two'.",
              "कतमः = 'which of many'."])],
          5, [106, 107]),
    ],
    # ──────────────── sch11 — द्वीपोऽण्डमानः (The Andamans) ─────────────
    "sch11": [
        q("सेल्युलर कारागारम्, also called कालापानी, was…",
          ["the colonial prison at Port Blair where freedom-fighters were jailed",
           "a famous Andaman temple", "a coral-reef park", "a tribal village"],
          "the colonial prison at Port Blair where freedom-fighters were jailed",
          ["सेल्युलर कारागारम् = the Cellular Jail, nicknamed कालापानी ('black water').",
           "It stood on Port Blair in the Andamans.",
           "India's freedom-fighters were imprisoned there in the colonial era."],
          ["कालापानी / the Cellular Jail was a PRISON for freedom-fighters — not a temple or a park."],
          [v("कारागारम् means…", "a prison", ["कारागारम् = prison.",
             "The Cellular Jail was such a कारागार."])],
          4, [115, 116]),
        q("स्वातन्त्र्यवीरः सावरकरः is remembered in this chapter for…",
          ["enduring years of terrible suffering in the Cellular Jail",
           "discovering the Andaman Islands", "ruling the Andamans as king",
           "composing the national anthem"],
          "enduring years of terrible suffering in the Cellular Jail",
          ["The chapter calls Savarkar a स्वातन्त्र्यवीरः ('hero of freedom').",
           "He बोरे (सोढवान्) घोरम् कष्टम् — terrible suffering — during years in the Cellular Jail.",
           "So he is remembered for that endurance."],
          ["Savarkar is honoured for ENDURING imprisonment there, not for discovering or ruling the islands."],
          [v("सोढवान् means…", "(he) bore / endured",
             ["सोढवान् is a past active participle of सह् ('to endure').",
              "It means 'he bore / endured'."])],
          4, [116, 117]),
        q("कारागारम् means…",
          ["a prison", "an island", "a fort", "a temple"],
          "a prison",
          ["कारागारम् denotes a prison / jail.",
           "The Cellular Jail is described as a कारागार.",
           "So कारागारम् = prison."],
          ["कारागारम् is a PRISON — not a fort (दुर्गम्) or temple (मन्दिरम्)."],
          [v("द्वीपः means…", "an island", ["द्वीपः = island.",
             "The Andamans are द्वीपाः (islands)."])],
          3, [114, 115]),
        q("The Cellular Jail is described as त्रितलात्मकम् — meaning it is…",
          ["three-storied", "triangular", "very ancient", "underground"],
          "three-storied",
          ["त्रि = 'three'; तल = 'storey/floor'; -आत्मकम् = 'consisting of'.",
           "So त्रितलात्मकम् = 'consisting of three storeys', three-storied.",
           "It describes the jail's structure."],
          ["त्रि is 'three' and तल is 'floor' — the word means three-STORIED, not three-cornered (triangular)."],
          [v("त्रि- means…", "three", ["त्रि is the prefix for 'three'.",
             "त्रितल = three floors."])],
          4, [116, 117]),
        q("सोढवान् ('he bore / endured') is which kind of form?",
          ["a past active participle ('one who has endured')",
           "a present-tense verb", "a future-tense verb", "a place noun"],
          "a past active participle ('one who has endured')",
          ["सोढवान् ends in -वान् (the -तवत् past active participle).",
           "It means 'he has borne / one who endured' — a completed past action by the doer.",
           "So it is a past active participle."],
          ["The -वान् / -तवत् ending marks a PAST ACTIVE participle, describing what the doer has already done."],
          [v("A participle ending in -वान् describes an action that is…",
             "completed in the past (by the doer)",
             ["-वान् (-तवत्) is the past active participle.",
              "It marks a completed past action."])],
          5, [116, 117]),
        q("The chapter names जनजातयः such as जारवा and सेण्टिनली. जनजातिः means…",
          ["a tribal community", "a kind of bird", "a coral reef", "a prison cell"],
          "a tribal community",
          ["जन = 'people'; जाति = 'class/community'.",
           "So जनजातिः = 'a people-community', i.e. a tribe.",
           "जारवा and सेण्टिनली are indigenous जनजातयः of the Andamans."],
          ["जनजातिः literally is 'people-class' = a TRIBE — not a reef or a bird."],
          [v("प्रवालप्रस्तरैः refers to the Andamans' famous…", "coral reefs",
             ["प्रवाल = coral, प्रस्तर = rock/reef.",
              "So प्रवालप्रस्तरैः = 'by/with coral reefs'."])],
          4, [114, 115]),
    ],
    # ──────────────── sch12 — वीराङ्गना पन्नाधाया (Panna Dhai) ──────────
    "sch12": [
        q("Why is पन्नाधाया honoured as a वीराङ्गना (brave woman)?",
          ["she gave up her own son to save the prince",
           "she won a great battle", "she ruled Mewar as queen",
           "she wrote a famous book"],
          "she gave up her own son to save the prince",
          ["Panna Dhai was the धाया (foster-mother) of the Mewar prince.",
           "To save the prince from an assassin's plot, she sacrificed her OWN son (सर्वस्वत्यागः).",
           "For this supreme sacrifice she is honoured as a वीराङ्गना."],
          ["Her bravery was a personal sacrifice as the wet-nurse — not a military victory or a reign."],
          [v("सर्वस्वत्यागः means…", "the sacrifice of one's everything",
             ["सर्वस्वम् = 'one's all', त्यागः = 'sacrifice'.",
              "So: giving up one's everything."])],
          5, [126, 127]),
        q("धाया means…",
          ["a wet-nurse / foster-mother", "a queen", "a soldier", "a sister"],
          "a wet-nurse / foster-mother",
          ["धाया denotes a wet-nurse or foster-mother.",
           "Panna was the धाया who raised the Mewar prince.",
           "So धाया = foster-mother."],
          ["धाया is the foster-MOTHER/wet-nurse role — that, not royalty, is the heart of Panna's story."],
          [v("शयनागारम् means…", "a bedroom / sleeping-chamber",
             ["शयन ('sleeping') + आगारम् ('room').",
              "So शयनागारम् = bedroom."])],
          3, [126, 127]),
        q("षोडशे शतके places Panna Dhai's story in…",
          ["the sixteenth century", "the sixth century", "her sixteenth year", "sixteen days"],
          "the sixteenth century",
          ["षोडश = 'sixteen'; शतक = 'a century'; the -ए ending is the locative ('in').",
           "So षोडशे शतके = 'in the sixteenth century'.",
           "It dates her story to real history."],
          ["षोडश is 'sixteen' and शतक 'century' — the locative phrase means 'in the 16th CENTURY', not the 16th year."],
          [v("The locative ending -ए on षोडशे / शतके means…", "'in / on / at'",
             ["The locative (सप्तमी) means 'in/on/at'.",
              "So षोडशे शतके = 'in the 16th century'."])],
          4, [126, 127]),
        q("सर्वस्वत्यागः means…",
          ["giving up one's all (total sacrifice)", "a great victory",
           "a royal gift", "a long journey"],
          "giving up one's all (total sacrifice)",
          ["सर्वस्वम् = 'one's entire possession / one's all'; त्यागः = 'renunciation, sacrifice'.",
           "So सर्वस्वत्यागः = the sacrifice of everything one has.",
           "Panna's giving of her own son is the supreme example."],
          ["त्यागः means SACRIFICE/renunciation, not a gift received — सर्वस्वत्यागः is giving up everything."],
          [v("त्यागः means…", "sacrifice / renunciation",
             ["त्यागः = giving up, renunciation.",
              "सर्वस्वत्यागः = giving up one's all."])],
          4, [127, 128]),
        q("मारयितुम् ('to kill') is which kind of form?",
          ["an infinitive ('to ___')", "a past-tense verb",
           "a command (imperative)", "a noun"],
          "an infinitive ('to ___')",
          ["मारयितुम् ends in -तुम्, the infinitive suffix.",
           "It means 'to kill' (the causative of मृ, 'to die', → 'to cause to die').",
           "So it is an infinitive, expressing purpose."],
          ["The -तुम् ending marks an INFINITIVE ('to ___'), used for purpose — not a finished past action."],
          [v("The Sanskrit infinitive suffix ('to ___') is…", "-तुम्",
             ["-तुम् forms the infinitive.",
              "मारयितुम् = 'to kill'."])],
          5, [128, 129]),
        q("Panna Dhai's name is said to be written स्वर्णिमाक्षरैः, meaning…",
          ["in golden letters", "in stone", "in sand", "in blood"],
          "in golden letters",
          ["स्वर्णिम = 'golden'; अक्षरैः = 'with/in letters' (instrumental plural).",
           "So स्वर्णिमाक्षरैः = 'in golden letters'.",
           "Her name shines in golden letters in the history of India's brave women."],
          ["The -ऐः ending is instrumental plural ('with/in'), and स्वर्णिम is 'golden' — the phrase praises her lasting fame."],
          [v("छलेन ('by deception') uses which case to mean 'by'?",
             "the instrumental (तृतीया)",
             ["छलेन is the instrumental of छल ('deception').",
              "The 'by/with' sense is the instrumental, तृतीया."])],
          4, [127, 128]),
    ],
    # ──────────────── sch13 — वर्णमात्रा-परिचयः (Vowel Quantities) ──────
    "sch13": [
        q("Sanskrit vowels have three मात्रा (duration) classes. Which set names them correctly?",
          ["ह्रस्व (short), दीर्घ (long), प्लुत (prolonged)",
           "उदात्त, अनुदात्त, स्वरित", "अ, इ, उ", "स्वर, व्यञ्जन, सन्धि"],
          "ह्रस्व (short), दीर्घ (long), प्लुत (prolonged)",
          ["मात्रा is the time a vowel is held.",
           "The three quantity-classes are ह्रस्व (1 mātrā), दीर्घ (2 mātrās), प्लुत (3 mātrās).",
           "So that set is correct."],
          ["उदात्त/अनुदात्त/स्वरित are pitch ACCENTS, not durations — the three QUANTITIES are ह्रस्व, दीर्घ, प्लुत."],
          [v("How many mātrā classes of vowels are there?", "three",
             ["ह्रस्व, दीर्घ and प्लुत.",
              "That is three quantity classes."])],
          4, [141, 142]),
        q("अ is ह्रस्व (one mātrā). Its दीर्घ (two-mātrā) counterpart is…",
          ["आ", "इ", "ए", "अः"],
          "आ",
          ["The दीर्घ vowel is the long version of the same sound.",
           "The long form of the short अ is आ.",
           "So अ (short) ↔ आ (long)."],
          ["इ is a DIFFERENT vowel (its own short/long pair is इ/ई) — the long of अ is specifically आ."],
          [v("The दीर्घ (long) counterpart of इ is…", "ई",
             ["इ (short) lengthens to ई (long).",
              "So the दीर्घ of इ is ई."])],
          4, [141, 142]),
        q("A प्लुत vowel lasts how many mātrās — used, for example, when calling out from far away?",
          ["three", "one", "two", "four"],
          "three",
          ["ह्रस्व = 1 mātrā, दीर्घ = 2 mātrās.",
           "प्लुत is the prolonged vowel, held for 3 mātrās.",
           "It appears in long-distance calls, e.g. 'ओ३म्' or 'आगच्छ३'."],
          ["प्लुत is the LONGEST (3 mātrās) — students often mix it up with दीर्घ (only 2)."],
          [v("Rank the three by length, shortest first.",
             "ह्रस्व (1) < दीर्घ (2) < प्लुत (3)",
             ["ह्रस्व is 1 mātrā, दीर्घ 2, प्लुत 3.",
              "So shortest to longest: ह्रस्व, दीर्घ, प्लुत."])],
          5, [141, 142]),
        q("कुक्कुटः रौति means 'the rooster crows'. How do you say 'the roosters (plural) crow'?",
          ["कुक्कुटाः रुवन्ति", "कुक्कुटः रुवन्ति", "कुक्कुटाः रौति", "कुक्कुटौ रौति"],
          "कुक्कुटाः रुवन्ति",
          ["A plural subject needs a plural verb (subject–verb agreement).",
           "The plural of कुक्कुटः is कुक्कुटाः; the plural of रौति is रुवन्ति.",
           "So 'the roosters crow' = कुक्कुटाः रुवन्ति."],
          ["The verb must agree in number: रौति is SINGULAR, so कुक्कुटाः (plural) must take रुवन्ति, not रौति."],
          [v("रौति is singular ('it crows'); its plural ('they crow') is…", "रुवन्ति",
             ["रौति (sing.) → रुवन्ति (plural).",
              "So 'they crow' = रुवन्ति."])],
          5, [144, 145]),
        q("Which Sanskrit word means 'peacock'?",
          ["शिखी", "वायसः", "कपोतः", "नकुलः"],
          "शिखी",
          ["शिखी (literally 'the crested one') is a name for the peacock.",
           "So शिखी = peacock.",
           "(मयूरः is another word for it.)"],
          ["वायसः = crow, कपोतः = pigeon, नकुलः = mongoose — only शिखी means peacock."],
          [v("वायसः means…", "crow", ["वायसः = crow.",
             "It is not the peacock (शिखी)."])],
          4, [144, 145]),
        q("नकुलः means…",
          ["mongoose", "mouse", "peacock", "crow"],
          "mongoose",
          ["नकुलः is the Sanskrit word for the mongoose.",
           "So नकुलः = mongoose.",
           "It is famous as the snake's natural foe."],
          ["मूषकः is the MOUSE — don't confuse it with नकुलः (mongoose), the mouse-hunter."],
          [v("मूषकः means…", "mouse", ["मूषकः = mouse.",
             "The नकुलः (mongoose) is its hunter."])],
          3, [144, 145]),
    ],
    # ──────────────── sch14 — शब्दरूपाणि (Noun Declension) ──────────────
    "sch14": [
        q("How many विभक्ति (cases) does Sanskrit have, besides the vocative?",
          ["seven", "five", "three", "ten"],
          "seven",
          ["Sanskrit nouns decline through seven cases (विभक्ति): प्रथमा … सप्तमी.",
           "The सम्बोधन (vocative, for calling) is counted separately.",
           "So there are seven cases proper."],
          ["The vocative is listed apart — the cases proper number SEVEN, not eight."],
          [v("The seven cases run from प्रथमा to…", "सप्तमी",
             ["They are numbered प्रथमा (1st) … सप्तमी (7th).",
              "So the last is सप्तमी."])],
          4, [147, 148]),
        q("The nominative (प्रथमा) plural of देव is…",
          ["देवाः", "देवः", "देवौ", "देवान्"],
          "देवाः",
          ["देवः is the nominative SINGULAR; देवौ is the DUAL.",
           "The nominative plural of an अकारान्त masculine adds -आः: देव → देवाः.",
           "So 'the gods' (subject) = देवाः."],
          ["देवान् is the ACCUSATIVE plural (object 'the gods'); the nominative (subject) plural is देवाः."],
          [v("The nominative singular of देव is…", "देवः",
             ["The nominative singular ending is -ः.",
              "So देव → देवः."])],
          5, [148, 149]),
        q("The प्रथमा (nominative) marks the subject; the द्वितीया (accusative) marks the…",
          ["object", "means", "origin", "location"],
          "object",
          ["The nominative (प्रथमा) names the doer/subject.",
           "The accusative (द्वितीया) names the object — what the action falls upon.",
           "So द्वितीया marks the object."],
          ["'Means' is तृतीया, 'origin' पञ्चमी, 'location' सप्तमी — द्वितीया is specifically the OBJECT."],
          [v("In रामः ग्रामं गच्छति, which word is in the द्वितीया (object) case?",
             "ग्रामम् (the village)",
             ["रामः is the subject (nominative).",
              "ग्रामम्, the goal/object, is accusative (द्वितीया)."])],
          4, [149, 150]),
        q("Which case means 'by / with' (the means or instrument of an action)?",
          ["तृतीया (instrumental)", "पञ्चमी (ablative)", "षष्ठी (genitive)", "सप्तमी (locative)"],
          "तृतीया (instrumental)",
          ["The 'by / with / by means of' relationship is the instrumental.",
           "That is the तृतीया विभक्ति.",
           "Example: हस्तेन ('with the hand')."],
          ["पञ्चमी (ablative) means 'FROM' (origin), not 'by/with' — the instrument is तृतीया."],
          [v("The पञ्चमी (ablative) case means…", "'from' (origin / separation)",
             ["पञ्चमी marks origin or separation.",
              "It means 'from'."])],
          5, [149, 150]),
        q("The सप्तमी (locative) case answers which question?",
          ["where? (in / on / at)", "of whom? (possession)",
           "to / for whom?", "from where?"],
          "where? (in / on / at)",
          ["Each case answers a question.",
           "The locative (सप्तमी) tells WHERE — in, on, or at a place.",
           "Example: ग्रामे ('in the village')."],
          ["'Of whom' (possession) is षष्ठी (genitive) — the locative (सप्तमी) is 'in/on/at', answering WHERE."],
          [v("The षष्ठी (genitive) case means…", "'of' (possession)",
             ["षष्ठी marks possession, 'of'.",
              "Example: रामस्य ('of Rama')."])],
          4, [149, 150]),
        q("हे देव! ('O God!') uses which form?",
          ["the vocative (सम्बोधन)", "the nominative", "the dative", "the accusative"],
          "the vocative (सम्बोधन)",
          ["Calling out to or addressing someone uses the सम्बोधन (vocative).",
           "हे देव! ('O God!') is a direct address.",
           "So it is the vocative form."],
          ["The vocative (सम्बोधन, देव!) is for ADDRESSING — distinct from the nominative देवः, which names the subject."],
          [v("The case form used to call or address someone is the…",
             "vocative (सम्बोधन)",
             ["Addressing someone uses the vocative.",
              "हे देव! is in that form."])],
          4, [150, 151]),
    ],
    # ──────────────── sch15 — धातुरूपाणि (Verb Conjugation) ─────────────
    "sch15": [
        q("धातुः means…",
          ["a verb root", "a noun", "a case ending", "a vowel"],
          "a verb root",
          ["धातुः is the basic verb root from which all verb forms are built.",
           "For example पठ् ('to read') is a धातु.",
           "So धातुः = verb root."],
          ["धातुः is a VERB root — nouns decline (शब्दरूप), but धातु is the building-block of verbs (धातुरूप)."],
          [v("पठ्, the root behind पठति, is an example of a…", "धातु (verb root)",
             ["पठ् is the verb root.",
              "From it comes पठति ('he reads')."])],
          3, [153, 154]),
        q("Sanskrit's tenses and moods are organised into how many लकार ('L-tense/moods')?",
          ["ten", "seven", "three", "six"],
          "ten",
          ["Each tense or mood has its own लकार (named लट्, लङ्, लोट्, लृट् …).",
           "There are ten लकाराः in all.",
           "So the answer is ten."],
          ["There are TEN lakāras — not seven; लट् (present), लङ् (past), लृट् (future), लोट् (imperative) are just four of them."],
          [v("The present-tense लकार is called…", "लट्",
             ["लट् लकार is the present tense.",
              "पठति is in लट्."])],
          5, [153, 154]),
        q("परस्मैपदम् means 'word for another'; आत्मनेपदम् means…",
          ["'word for oneself'", "'word for the past'",
           "'word for the future'", "'word for two people'"],
          "'word for oneself'",
          ["पद here means a class of verb endings.",
           "परस्मैपदम् = 'for another'; आत्मनेपदम् = आत्मने ('for oneself') + पद.",
           "So आत्मनेपदम् = 'word for oneself'."],
          ["आत्मने means 'for oneself' — the contrast is परस्मै ('for another') vs आत्मने ('for oneself'), not about tense."],
          [v("भाष् → भाषते is an example of which pada?", "आत्मनेपद",
             ["भाषते uses आत्मनेपद endings (-ते).",
              "So it is आत्मनेपद."])],
          4, [153, 154]),
        q("पठति is 'he reads' (singular). How do you say 'they (many) read'?",
          ["पठन्ति", "पठतः", "पठसि", "पठामि"],
          "पठन्ति",
          ["पठति is singular; पठतः is dual ('the two read').",
           "The plural ('they all read') is पठन्ति.",
           "So 'they read' = पठन्ति."],
          ["पठतः is the DUAL ('they two read') — the plural ('they all read') is पठन्ति."],
          [v("पठतः means…", "'they two read' (dual)",
             ["पठतः is the dual form.",
              "It means 'the two of them read'."])],
          5, [155, 156]),
        q("The plural 'they are' from the root अस् ('to be') is…",
          ["सन्ति", "अस्ति", "स्तः", "असि"],
          "सन्ति",
          ["अस्ति = 'he/she/it is' (singular); स्तः = 'the two are' (dual).",
           "The plural 'they are' is सन्ति.",
           "So 'they are' = सन्ति."],
          ["अस्ति is SINGULAR ('he is') and स्तः is dual — the plural 'they are' is सन्ति."],
          [v("अस्ति means…", "'he / she / it is' (singular)",
             ["अस्ति is the singular of अस्.",
              "It means 'he/she/it is'."])],
          5, [155, 156]),
        q("In Sanskrit's own naming, the प्रथमपुरुष ('first person') actually corresponds to which English person?",
          ["the third person (he / she / it)", "the first person (I)",
           "the second person (you)", "none — it is the plural"],
          "the third person (he / she / it)",
          ["Sanskrit numbers its 'persons' in the reverse of English.",
           "प्रथमपुरुष (Sanskrit 'first') = English THIRD person (he/she/it).",
           "उत्तमपुरुष (Sanskrit 'last/best') = English first person (I)."],
          ["The naming is reversed: Sanskrit's प्रथमपुरुष is English's THIRD person — a classic trap."],
          [v("The उत्तमपुरुष in Sanskrit corresponds to which English person?",
             "the first person (I / we)",
             ["उत्तमपुरुष = English first person.",
              "So it means 'I / we'."])],
          5, [154, 155]),
    ],
}


def main():
    pack = json.loads(PACK.read_text(encoding="utf-8"))
    chapter_ids = {ch["id"] for ch in pack["chapters"]}
    for cid in BOSS:
        if cid not in chapter_ids:
            raise SystemExit(f"BOSS references unknown chapter {cid}")
        if cid == LEGACY_DECK:
            raise SystemExit(f"refusing to author boss questions on legacy deck {cid}")

    seen_ids = set()
    total = 0
    touched = 0
    for ch in pack["chapters"]:
        if ch["id"] == LEGACY_DECK:
            continue  # carve-out: skip the legacy vocabulary deck
        items = BOSS.get(ch["id"])
        if not items:
            raise SystemExit(f"No bossQuestions authored for {ch['id']}")
        if len(items) < PER_CHAPTER:
            raise SystemExit(f"{ch['id']} has only {len(items)} boss questions (<{PER_CHAPTER})")
        built = []
        for i, it in enumerate(items):
            qid = f"bossquiz_{ch['id']}_q{i:02d}"  # sch01 → bossquiz_sch01_q00
            if qid in seen_ids:
                raise SystemExit(f"Duplicate boss id {qid}")
            seen_ids.add(qid)
            q_obj = {"id": qid}
            q_obj.update(it)
            built.append(q_obj)
        ch["bossQuestions"] = built
        total += len(built)
        touched += 1

    PACK.write_text(json.dumps(pack, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Injected {total} bossQuestions across {touched} NEP Sanskrit chapters "
          f"({PER_CHAPTER}/chapter); legacy {LEGACY_DECK} deck skipped.")


if __name__ == "__main__":
    main()
