#!/usr/bin/env python3
"""P1-C — add `bossQuestions: [Question]` arrays to every Maths chapter.

The Maths pack (`maths_class7.json`, NEP Ganita Prakash Grade 7) shipped with
zero bossQuestions. Boss questions are the high-difficulty pool the v6 adaptive
journey (Phase 3) escalates into and a feeder for the Olympiad ladder (Phase 5);
with none present, the adaptive difficulty ceiling for Maths was just the
`ncertQA`/topic sets. This script adds 6 PDF-faithful boss questions per chapter
(90 total), each:

  * id in the canonical collision-free shape `bossquiz_mchNN_qII`
    (namespace token `mch` keeps Maths ids distinct from Science's
    `bossquiz_chNN_qII` — enforced by scripts/check_quiz_id_format.py and the
    SubjectRegistry global question index),
  * difficulty 3..5 (boss tier; difficulty>=3 requires non-empty solutionSteps,
    enforced by scripts/check_pack_schema.py::check_question),
  * mcq with 4 options and the answer present among them,
  * worked `solutionSteps`, >=1 `commonMistakes` note, and >=1 `variations`
    entry (prompt/answer/solutionSteps) so the kid can re-drill the idea,
  * `pageRefs` inside the chapter's real NCERT page range,
  * `source: "boss_quiz"`, `needsHumanReview: false`.

Additive only. Re-runnable (idempotent: overwrites the bossQuestions key). Writes
the canonical format `json.dumps(d, ensure_ascii=False, indent=2) + "\n"` so
verify_pack_roundtrip.py stays byte-for-byte green.
"""
import json
from pathlib import Path

PACK = Path(__file__).resolve().parent.parent / "desktopAhaan/Subjects/Packs/maths_class7.json"

PER_CHAPTER = 6


def v(prompt, answer, steps):
    """A QuestionVariation literal."""
    return {"prompt": prompt, "answer": answer, "solutionSteps": steps}


def q(prompt, options, answer, steps, mistakes, variations, difficulty, pages):
    """A boss Question literal (ids assigned in main, per-chapter)."""
    assert answer in options, f"answer {answer!r} not in options {options}"
    assert 3 <= difficulty <= 5, f"boss difficulty must be 3..5, got {difficulty}"
    assert steps, "difficulty>=3 requires non-empty solutionSteps"
    assert mistakes, "boss question must carry at least one commonMistakes note"
    assert variations, "boss question must carry at least one variation"
    return {
        "prompt": prompt,
        "questionType": "mcq",
        "options": options,
        "answer": answer,
        "solutionSteps": steps,
        "commonMistakes": mistakes,
        "variations": variations,
        "difficulty": difficulty,
        "pageRefs": pages,
        "needsHumanReview": False,
        "source": "boss_quiz",
    }


BOSS = {
    # ───────────────────────── ch01 — Large Numbers Around Us ─────────────
    "ch01": [
        q("Write 'three crore five lakh seven thousand two hundred' in figures using the Indian system.",
          ["3,05,07,200", "30,57,200", "3,50,07,200", "3,05,70,200"],
          "3,05,07,200",
          ["Three crore = 3,00,00,000; five lakh = 5,00,000; seven thousand = 7,000; two hundred = 200.",
           "Add the place values: 3,00,00,000 + 5,00,000 + 7,000 + 200 = 3,05,07,200.",
           "Group right-to-left in the Indian 3-2-2-2 pattern to place the commas."],
          ["Writing 3,50,07,200 puts 50 lakh instead of 5 lakh — read each named group separately before combining.",
           "Dropping a zero gives 30,57,200, which is only thirty lakh — count the place of every word."],
          [v("Write 'two crore ten lakh forty thousand five' in figures (Indian system).",
             "2,10,40,005",
             ["2 crore = 2,00,00,000; 10 lakh = 10,00,000; 40 thousand = 40,000; five = 5.",
              "Sum: 2,00,00,000 + 10,00,000 + 40,000 + 5 = 2,10,40,005."])],
          3, [3, 4]),
        q("The number 9,07,06,005 is written in the Indian system. How is the SAME number grouped in the International system?",
          ["90,706,005", "9,070,6005", "907,06,005", "90,76,005"],
          "90,706,005",
          ["Read the Indian number: 9 crore, 7 lakh, 6 thousand, 5 = 90,000,000 + 700,000 + 6,000 + 5.",
           "That total is 90,706,005.",
           "Regroup right-to-left in 3s for the International system: 90,706,005."],
          ["The digits don't change between systems — only the comma positions do. Re-grouping in 3s, not re-reading the value, is all that's needed."],
          [v("Group 5,04,03,002 (Indian) in the International system.",
             "50,403,002",
             ["Value = 5 crore 4 lakh 3 thousand 2 = 50,403,002.",
              "Comma every 3 digits from the right: 50,403,002."])],
          4, [10, 11]),
        q("What is the smallest 8-digit number, and the largest number that comes just before it?",
          ["1,00,00,000 and 99,99,999", "10,00,000 and 9,99,999",
           "1,00,00,000 and 9,99,999", "10,00,00,000 and 99,99,999"],
          "1,00,00,000 and 99,99,999",
          ["The smallest 8-digit number is 1 followed by seven zeros: 1,00,00,000 (one crore).",
           "The number one less is the largest 7-digit number: 99,99,999.",
           "Adding 1 to the largest n-digit number always rolls over to the smallest (n+1)-digit number."],
          ["Confusing one crore (8 digits) with ten lakh (7 digits, 10,00,000) — count the zeros: one crore has seven."],
          [v("What is the smallest 6-digit number and the number just before it?",
             "1,00,000 and 99,999",
             ["Smallest 6-digit number = 1,00,000 (one lakh).",
              "One less is the largest 5-digit number, 99,999."])],
          3, [2, 3]),
        q("A factory made 4,87,650 toys. A report rounds this to the nearest ten-thousand. What value does it print?",
          ["4,90,000", "4,80,000", "4,88,000", "5,00,000"],
          "4,90,000",
          ["To round to the nearest ten-thousand, look at the thousands digit of 4,87,650 — it is 7.",
           "Since 7 is 5 or more, round the ten-thousands place up: 8 ten-thousands becomes 9.",
           "Result: 4,90,000."],
          ["Rounding DOWN to 4,80,000 ignores that 87 thousand is closer to 90 thousand than to 80 thousand.",
           "Rounding to the nearest thousand (4,88,000) answers a different question — read the required precision."],
          [v("Round 2,34,500 to the nearest ten-thousand.",
             "2,30,000",
             ["Thousands digit is 4 (less than 5), so round down.",
              "3 ten-thousands stays 3: 2,30,000."])],
          4, [13, 14]),
        q("Without multiplying it out exactly, how many digits does the product 8,000 × 7,000 have?",
          ["8", "7", "6", "9"],
          "8",
          ["Write each as a single digit times a power of ten: 8,000 = 8 × 10^3 and 7,000 = 7 × 10^3.",
           "Multiply: (8 × 7) × 10^(3+3) = 56 × 10^6 = 56,000,000.",
           "56 contributes 2 digits and 10^6 adds 6 zeros: 2 + 6 = 8 digits."],
          ["Just adding the zero-counts (3 + 3 = 6) forgets that 8 × 7 = 56 itself carries an extra digit, so the answer is 8 digits, not 7."],
          [v("How many digits does 50 × 4,000 have?",
             "6",
             ["50 × 4,000 = 200,000 = 2 × 10^5.",
              "That is 2 followed by five zeros — 6 digits."])],
          4, [18, 19]),
        q("Ahaan's pulse is about 75 beats per minute. Roughly how many times does his heart beat in one full day?",
          ["about 1,00,000", "about 10,000", "about 10,00,000", "about 4,500"],
          "about 1,00,000",
          ["Beats per hour ≈ 75 × 60 = 4,500.",
           "Beats per day ≈ 4,500 × 24 = 1,08,000.",
           "Rounded to the nearest convenient large number, that is about one lakh (1,00,000)."],
          ["Stopping at 75 × 60 = 4,500 gives beats per HOUR, not per day — the estimate still needs the × 24 step."],
          [v("If he breathes about 18 times a minute, roughly how many breaths in a day?",
             "about 26,000",
             ["Per hour ≈ 18 × 60 = 1,080.",
              "Per day ≈ 1,080 × 24 = 25,920 ≈ 26,000."])],
          5, [20, 21]),
    ],
    # ───────────────────────── ch02 — Arithmetic Expressions ─────────────
    "ch02": [
        q("Evaluate 30 − 5 × 4 + 2.",
          ["12", "102", "100", "22"],
          "12",
          ["Order of operations: do the multiplication first. 5 × 4 = 20.",
           "Now evaluate left to right: 30 − 20 + 2.",
           "30 − 20 = 10, then 10 + 2 = 12."],
          ["Working strictly left to right (30 − 5 = 25, × 4 = 100, + 2 = 102) breaks the rule that × is done before + and −."],
          [v("Evaluate 40 − 3 × 6 + 5.",
             "27",
             ["3 × 6 = 18 first.",
              "40 − 18 + 5 = 22 + 5 = 27."])],
          3, [26, 27]),
        q("Which is greater: 23 × 99, or 23 × 100 − 23?",
          ["They are equal", "23 × 99", "23 × 100 − 23", "Cannot be decided"],
          "They are equal",
          ["By the distributive property, 23 × 100 − 23 = 23 × (100 − 1) = 23 × 99.",
           "So both expressions name the same number.",
           "No multiplication is needed — recognising the distributive pattern decides it."],
          ["Computing both sides risks an arithmetic slip; the point is to SEE that 100 − 1 = 99 makes them identical."],
          [v("Which is greater: 47 × 100 − 47, or 47 × 98?",
             "47 × 100 − 47 is greater",
             ["47 × 100 − 47 = 47 × 99.",
              "47 × 99 > 47 × 98, so the first is greater by 47."])],
          4, [30, 31]),
        q("Simplify 50 − (18 − 6 + 4).",
          ["34", "30", "22", "42"],
          "34",
          ["First evaluate inside the bracket: 18 − 6 + 4 = 16.",
           "Then 50 − 16 = 34.",
           "Equivalently, remove the bracket after the minus by flipping every sign: 50 − 18 + 6 − 4 = 34."],
          ["A common slip is 50 − 18 − 6 + 4 = 30 — when a minus sits in front of a bracket, EVERY sign inside must flip, not just the first."],
          [v("Simplify 80 − (25 − 10 + 5).",
             "60",
             ["Inside: 25 − 10 + 5 = 20.",
              "80 − 20 = 60."])],
          4, [33, 34]),
        q("Use the distributive property to compute 102 × 45 mentally.",
          ["4590", "4545", "4950", "459"],
          "4590",
          ["Split 102 as 100 + 2.",
           "102 × 45 = 100 × 45 + 2 × 45 = 4500 + 90.",
           "4500 + 90 = 4590."],
          ["Forgetting the 2 × 45 = 90 piece and just writing 4500 (or 4545) loses part of the product."],
          [v("Compute 99 × 36 by splitting 99 as 100 − 1.",
             "3564",
             ["99 × 36 = 100 × 36 − 1 × 36 = 3600 − 36.",
              "3600 − 36 = 3564."])],
          4, [35, 36]),
        q("Which regrouping makes 25 × 17 × 4 easiest to do mentally, and what is the product?",
          ["(25 × 4) × 17 = 1700", "(25 × 17) × 4 = 1700", "(17 × 4) × 25 = 680", "25 × (17 × 4) = 425"],
          "(25 × 4) × 17 = 1700",
          ["Multiplication is associative, so the factors may be grouped any way.",
           "Pairing 25 × 4 = 100 first turns the rest into 100 × 17 = 1700, an easy mental step.",
           "The product is 1700."],
          ["The product is the same whatever the grouping — only the EASE differs. Options giving 680 or 425 are arithmetic errors, not just slower groupings."],
          [v("Group 2 × 39 × 50 to compute it mentally.",
             "3900",
             ["Pair 2 × 50 = 100 first.",
              "100 × 39 = 3900."])],
          3, [28, 29]),
        q("Evaluate 6 + 2 × (15 − 3 × 4) ÷ 2.",
          ["9", "12", "6", "15"],
          "9",
          ["Brackets first; inside, do × before −: 3 × 4 = 12, so 15 − 12 = 3.",
           "Now 6 + 2 × 3 ÷ 2. Do × and ÷ left to right: 2 × 3 = 6, then 6 ÷ 2 = 3.",
           "Finally 6 + 3 = 9."],
          ["Doing the ÷ before the × inside (or adding the 6 too early) scrambles the order — resolve the bracket completely, then × and ÷ left to right, then +."],
          [v("Evaluate 10 + 3 × (8 − 2 × 3) ÷ 2.",
             "13",
             ["Inside: 2 × 3 = 6, 8 − 6 = 2.",
              "3 × 2 = 6, 6 ÷ 2 = 3, then 10 + 3 = 13."])],
          5, [32, 33]),
    ],
    # ───────────────────────── ch03 — A Peek Beyond the Point ────────────
    "ch03": [
        q("In the number 47.305, what is the value of the digit 3?",
          ["0.3", "0.03", "3", "0.003"],
          "0.3",
          ["The first place after the decimal point is the tenths place.",
           "The digit 3 sits in the tenths place, so its value is 3 tenths.",
           "3 tenths = 3/10 = 0.3."],
          ["Reading the 3 as 0.03 confuses tenths with hundredths — the FIRST place after the point is tenths."],
          [v("In 9.207, what is the value of the digit 7?",
             "0.007",
             ["7 is in the third place after the point, the thousandths place.",
              "Its value is 7/1000 = 0.007."])],
          3, [52, 53]),
        q("Arrange in increasing order: 0.5, 0.45, 0.405, 0.054.",
          ["0.054, 0.405, 0.45, 0.5", "0.5, 0.45, 0.405, 0.054",
           "0.054, 0.45, 0.405, 0.5", "0.405, 0.45, 0.5, 0.054"],
          "0.054, 0.405, 0.45, 0.5",
          ["Compare tenths first: 0.054 has 0 tenths (smallest); the others have 4 or 5 tenths.",
           "Among 4-tenths numbers, compare hundredths: 0.405 (0 hundredths) < 0.45 (5 hundredths).",
           "0.5 has 5 tenths, the largest. Order: 0.054, 0.405, 0.45, 0.5."],
          ["Treating 'more digits = bigger' wrongly ranks 0.405 above 0.5 — compare place by place from the tenths, not by length."],
          [v("Arrange 0.7, 0.07, 0.77, 0.707 in increasing order.",
             "0.07, 0.7, 0.707, 0.77",
             ["Tenths: 0.07 has 0 tenths (smallest).",
              "Among 7-tenths: 0.7 = 0.700 < 0.707 < 0.77."])],
          4, [62, 63]),
        q("Add 12.7 + 3.45 + 0.8.",
          ["16.95", "16.15", "25.5", "15.95"],
          "16.95",
          ["Line up the decimal points and pad to equal places: 12.70 + 3.45 + 0.80.",
           "Add: 12.70 + 3.45 = 16.15.",
           "16.15 + 0.80 = 16.95."],
          ["Adding without aligning the points (e.g. lining up the right-hand digits) mixes tenths with hundredths and gives a wrong total."],
          [v("Add 5.6 + 0.75 + 13.2.",
             "19.55",
             ["Align: 5.60 + 0.75 + 13.20.",
              "5.60 + 0.75 = 6.35; 6.35 + 13.20 = 19.55."])],
          3, [73, 74]),
        q("A ribbon is 2.5 m long. Pieces of 0.85 m and 1.2 m are cut off. How much ribbon remains?",
          ["0.45 m", "0.55 m", "1.45 m", "0.35 m"],
          "0.45 m",
          ["Total cut = 0.85 + 1.20 = 2.05 m.",
           "Remaining = 2.50 − 2.05.",
           "2.50 − 2.05 = 0.45 m."],
          ["Subtracting only one piece (2.5 − 1.2 = 1.3, or 2.5 − 0.85) forgets that BOTH pieces are removed."],
          [v("From a 5 m rope, lengths 1.75 m and 2.4 m are cut. How much is left?",
             "0.85 m",
             ["Cut = 1.75 + 2.40 = 4.15 m.",
              "5.00 − 4.15 = 0.85 m."])],
          4, [72, 73]),
        q("Which fraction is equal to the decimal 0.08?",
          ["2/25", "8/10", "4/5", "1/8"],
          "2/25",
          ["0.08 means 8 hundredths = 8/100.",
           "Simplify 8/100 by dividing top and bottom by 4: 2/25.",
           "So 0.08 = 2/25."],
          ["Reading 0.08 as 8 tenths gives 8/10 — but the 8 sits in the hundredths place, so the denominator is 100, not 10."],
          [v("Which fraction equals 0.25?",
             "1/4",
             ["0.25 = 25/100.",
              "Divide by 25: 25/100 = 1/4."])],
          4, [50, 51]),
        q("A number is '4 ones, 0 tenths, 7 hundredths, 2 thousandths'. Add 0.5 to it. What is the result?",
          ["4.572", "9.072", "4.122", "4.077"],
          "4.572",
          ["Build the number place by place: 4 + 0.0 + 0.07 + 0.002 = 4.072.",
           "Add 0.5 (5 tenths): align as 4.072 + 0.500.",
           "4.072 + 0.500 = 4.572."],
          ["Adding 0.5 into the wrong column (e.g. making it 4.077 or 4.122) ignores that 0.5 is 5 TENTHS and must land in the tenths place."],
          [v("Build '6 ones, 3 tenths, 0 hundredths, 9 thousandths' and add 0.04.",
             "6.349",
             ["The number is 6.309.",
              "6.309 + 0.040 = 6.349."])],
          5, [54, 55]),
    ],
    # ───────────────────── ch04 — Expressions Using Letter-Numbers ───────
    "ch04": [
        q("If x = 4, find the value of 3x + 7.",
          ["19", "12", "21", "14"],
          "19",
          ["Substitute x = 4: 3 × 4 + 7.",
           "3 × 4 = 12 (do the multiplication first).",
           "12 + 7 = 19."],
          ["Reading 3x as 3 followed by 4 (giving 34) or adding before multiplying (3 × 11) both misuse the order of operations."],
          [v("If y = 6, find 2y − 5.",
             "7",
             ["2 × 6 = 12.",
              "12 − 5 = 7."])],
          3, [85, 86]),
        q("Simplify 5a + 3b − 2a + 7b − b.",
          ["3a + 9b", "3a + 11b", "12ab", "3a + 9"],
          "3a + 9b",
          ["Collect the a-terms: 5a − 2a = 3a.",
           "Collect the b-terms: 3b + 7b − b = 9b.",
           "Unlike terms can't be merged, so the simplified expression is 3a + 9b."],
          ["Merging a-terms with b-terms into '12ab' is wrong — only LIKE terms (same letter) may be added together.",
           "Dropping the letter from 9b to get '3a + 9' loses what is being counted."],
          [v("Simplify 4m + 2n − m + 5n.",
             "3m + 7n",
             ["m-terms: 4m − m = 3m.",
              "n-terms: 2n + 5n = 7n. Result 3m + 7n."])],
          4, [90, 91]),
        q("A matchstick pattern uses 3n + 1 sticks for the n-th figure. How many sticks does the 10th figure need?",
          ["31", "30", "34", "301"],
          "31",
          ["Substitute n = 10 into 3n + 1.",
           "3 × 10 = 30.",
           "30 + 1 = 31 sticks."],
          ["Writing 301 reads '3n' as the digits 3 and 0 side by side — 3n means 3 multiplied by n."],
          [v("Using 2n + 3, how many sticks for the 8th figure?",
             "19",
             ["2 × 8 = 16.",
              "16 + 3 = 19."])],
          4, [88, 89]),
        q("If p = 3 and q = 5, evaluate 2pq − p².",
          ["21", "39", "24", "51"],
          "21",
          ["2pq means 2 × p × q = 2 × 3 × 5 = 30.",
           "p² means p × p = 3 × 3 = 9.",
           "30 − 9 = 21."],
          ["Reading p² as 2p (giving 6) is a classic slip — a square multiplies the number by itself, it does not double it."],
          [v("If a = 2 and b = 4, evaluate 3ab − b².",
             "8",
             ["3ab = 3 × 2 × 4 = 24.",
              "b² = 16, so 24 − 16 = 8."])],
          4, [86, 87]),
        q("The sum of any three consecutive whole numbers (n, n+1, n+2) is always divisible by which number?",
          ["3", "2", "6", "4"],
          "3",
          ["Add the three: n + (n + 1) + (n + 2) = 3n + 3.",
           "Factor out 3: 3n + 3 = 3(n + 1).",
           "A multiple of 3 is always divisible by 3, whatever n is."],
          ["Checking one example (like 1 + 2 + 3 = 6) and concluding 'divisible by 6' over-generalises — 2 + 3 + 4 = 9 is not divisible by 6, but 9 IS divisible by 3."],
          [v("The sum of two consecutive odd numbers (2n+1 and 2n+3) is always divisible by what?",
             "4",
             ["(2n+1) + (2n+3) = 4n + 4 = 4(n + 1).",
              "So the sum is always a multiple of 4."])],
          5, [91, 92]),
        q("A rectangle has length (x + 5) and width x. Write its perimeter as a simplified expression.",
          ["4x + 10", "2x + 5", "4x + 5", "x² + 5x"],
          "4x + 10",
          ["Perimeter = 2 × (length + width) = 2 × ((x + 5) + x).",
           "Inside the bracket: x + 5 + x = 2x + 5.",
           "Multiply by 2: 2(2x + 5) = 4x + 10."],
          ["Writing x² + 5x computes the AREA, not the perimeter; perimeter adds the side lengths, it does not multiply them."],
          [v("A square has side (y + 2). Write its perimeter simplified.",
             "4y + 8",
             ["Perimeter of a square = 4 × side = 4(y + 2).",
              "4(y + 2) = 4y + 8."])],
          4, [89, 90]),
    ],
    # ─────────────────── ch05 — Parallel and Intersecting Lines ──────────
    "ch05": [
        q("Two lines cross. One of the four angles is 35°. What are the angle vertically opposite it and the angle next to it (its linear pair)?",
          ["35° and 145°", "35° and 35°", "145° and 145°", "55° and 145°"],
          "35° and 145°",
          ["Vertically opposite angles are equal, so the opposite angle is also 35°.",
           "A linear pair sits on a straight line and sums to 180°.",
           "So the adjacent angle is 180° − 35° = 145°."],
          ["Assuming the adjacent angle is also 35° forgets that neighbouring angles on a straight line are supplementary (add to 180°)."],
          [v("One of four angles where two lines cross is 110°. Find its vertically opposite and adjacent angles.",
             "110° and 70°",
             ["Vertically opposite = 110°.",
              "Adjacent = 180° − 110° = 70°."])],
          3, [108, 109]),
        q("Two angles form a linear pair. One is 4 times the other. Find the larger angle.",
          ["144°", "36°", "120°", "150°"],
          "144°",
          ["Let the smaller angle be x; the larger is 4x. A linear pair adds to 180°.",
           "x + 4x = 180°, so 5x = 180° and x = 36°.",
           "The larger angle is 4x = 4 × 36° = 144°."],
          ["Giving 36° answers for the SMALLER angle — the question asks for the larger, which is 4x."],
          [v("Two angles of a linear pair are in the ratio 2 : 3. Find both angles.",
             "72° and 108°",
             ["2x + 3x = 180°, so 5x = 180°, x = 36°.",
              "Angles are 72° and 108°."])],
          3, [109, 110]),
        q("A transversal cuts two parallel lines. One of a pair of co-interior (allied) angles is 110°. Find the other.",
          ["70°", "110°", "90°", "250°"],
          "70°",
          ["Co-interior (allied) angles between two parallel lines are supplementary — they add to 180°.",
           "So the other angle = 180° − 110°.",
           "180° − 110° = 70°."],
          ["Treating co-interior angles as EQUAL (answering 110°) confuses them with alternate or corresponding angles; co-interior angles add to 180°."],
          [v("Co-interior angles between parallels: one is 125°. Find the other.",
             "55°",
             ["They sum to 180°.",
              "180° − 125° = 55°."])],
          4, [121, 122]),
        q("Two parallel lines are cut by a transversal. A pair of alternate interior angles measure (2x + 10)° and (3x − 20)°. Find x.",
          ["30", "6", "38", "10"],
          "30",
          ["Alternate interior angles between parallel lines are equal.",
           "Set them equal: 2x + 10 = 3x − 20.",
           "Solve: 10 + 20 = 3x − 2x, so x = 30."],
          ["Setting the two expressions to sum to 180° treats them as co-interior angles — but ALTERNATE interior angles are equal, not supplementary."],
          [v("Corresponding angles on parallels are (4x − 5)° and (3x + 15)°. Find x.",
             "20",
             ["Corresponding angles are equal: 4x − 5 = 3x + 15.",
              "x = 20."])],
          4, [114, 115]),
        q("Two parallel lines are cut by a transversal, making just two distinct angle measures. If one of them is 72°, what are the two measures?",
          ["72° and 108°", "72° only", "72° and 18°", "72° and 90°"],
          "72° and 108°",
          ["A transversal across two parallel lines makes eight angles, but only two different sizes appear.",
           "Every angle is either equal to 72° (vertically opposite / corresponding / alternate) or supplementary to it.",
           "The supplement is 180° − 72° = 108°, so the two measures are 72° and 108°."],
          ["Pairing 72° with 18° uses the complement (sums to 90°) instead of the supplement; the partner angle here lies on a straight line and sums to 180°."],
          [v("On parallels cut by a transversal one angle is 115°. Give the two distinct measures.",
             "115° and 65°",
             ["The supplement is 180° − 115° = 65°.",
              "So the measures are 115° and 65°."])],
          5, [110, 111]),
        q("Line a is perpendicular to line b, and line b is parallel to line c. What is the angle between line a and line c?",
          ["90°", "0°", "45°", "180°"],
          "90°",
          ["a ⟂ b means a meets b at 90°.",
           "b ∥ c means c runs in the same direction as b.",
           "A line perpendicular to one of two parallel lines is perpendicular to the other, so a meets c at 90°."],
          ["Thinking a and c are parallel (0°) confuses the relationships — a is perpendicular to b, and c is parallel to b, so a stays perpendicular to c."],
          [v("If p ⟂ q and q ⟂ r, what is the relationship between p and r?",
             "p is parallel to r",
             ["p and r are both perpendicular to q.",
              "Two lines perpendicular to the same line are parallel to each other."])],
          3, [112, 113]),
    ],
    # ───────────────────────── ch06 — Number Play ────────────────────────
    "ch06": [
        q("Can the sum of five odd numbers ever equal 30?",
          ["No — five odd numbers always add to an odd number",
           "Yes, for example 2 + 4 + 6 + 8 + 10",
           "Yes, 1 + 3 + 5 + 7 + 14",
           "Only if one of them is zero"],
          "No — five odd numbers always add to an odd number",
          ["Odd + odd = even, and even + odd = odd; tracking parity, the sum of an ODD count of odd numbers is odd.",
           "Five is an odd count, so five odd numbers always sum to an odd number.",
           "30 is even, so it can never be such a sum."],
          ["Trying to 'find an example' wastes effort — the parity argument proves it is impossible without testing any case. (2+4+6+8+10 uses even numbers, not odd.)"],
          [v("Can three odd numbers add up to 20?",
             "No — three odds always sum to an odd number, but 20 is even",
             ["An odd count (three) of odd numbers gives an odd total.",
              "20 is even, so it is impossible."])],
          3, [134, 135]),
        q("In the Virahāṅka–Fibonacci sequence 1, 1, 2, 3, 5, 8, 13, …, what is the 9th term?",
          ["34", "21", "55", "13"],
          "34",
          ["Each term is the sum of the two before it.",
           "Continue: …8 (6th), 13 (7th), 8 + 13 = 21 (8th).",
           "Next: 13 + 21 = 34, the 9th term."],
          ["Mis-counting the position (calling 21 the 9th term) is the usual slip — list the terms with their position numbers as you go."],
          [v("What is the 7th term of 2, 2, 4, 6, 10, … (same add-the-previous-two rule)?",
             "26",
             ["6th term = 10 + 6 = 16.",
              "7th term = 16 + 10 = 26."])],
          4, [138, 139]),
        q("In the cryptarithm AB + BA = 132, where A and B are digits, find A + B.",
          ["12", "11", "6", "13"],
          "12",
          ["AB means 10A + B, and BA means 10B + A.",
           "Their sum is 11A + 11B = 11(A + B).",
           "So 11(A + B) = 132, giving A + B = 132 ÷ 11 = 12."],
          ["Trying to find A and B separately is unnecessary — the sum of a two-digit number and its reverse is always 11 times the digit-sum."],
          [v("If CD + DC = 99, find C + D.",
             "9",
             ["CD + DC = 11(C + D) = 99.",
              "C + D = 99 ÷ 11 = 9."])],
          5, [142, 143]),
        q("Which of these numbers is divisible by 9: 234, 343, 512, 700?",
          ["234", "343", "512", "700"],
          "234",
          ["A number is divisible by 9 exactly when the sum of its digits is divisible by 9.",
           "Digit sums: 234 → 2+3+4 = 9 ✓; 343 → 10; 512 → 8; 700 → 7.",
           "Only 234 has a digit sum that is a multiple of 9."],
          ["Checking divisibility by 9 by looking only at the last digit (as you would for 2, 5 or 10) doesn't work — you must add ALL the digits."],
          [v("Which is divisible by 3: 124, 232, 411, 505?",
             "411",
             ["Digit sums: 124→7, 232→7, 411→6 ✓, 505→10.",
              "Only 411 has a digit sum divisible by 3."])],
          4, [126, 127]),
        q("Ahaan says he wrote 7 whole numbers that add to an EVEN total, and exactly 3 of them are odd. Is that possible?",
          ["No — an odd count of odd numbers makes the total odd",
           "Yes, if the even numbers are large enough",
           "Yes, if one of them is zero",
           "Only if all 7 numbers are odd"],
          "No — an odd count of odd numbers makes the total odd",
          ["The even numbers contribute an even amount no matter their size.",
           "Three odd numbers contribute odd + odd + odd = odd.",
           "even + odd = odd, so the total must be odd — it cannot be even."],
          ["Believing big even numbers can 'fix' the parity is wrong — only the COUNT of odd addends decides whether the sum is odd or even."],
          [v("Is it possible for 4 numbers, exactly one of them odd, to add to an even total?",
             "No — one odd addend makes the sum odd",
             ["Three evens give an even amount.",
              "Adding one odd makes the total odd, so an even total is impossible."])],
          4, [136, 137]),
        q("Using the rule 1 + 1 + 2 + 3 + … + Fₙ = Fₙ₊₂ − 1, find 1 + 1 + 2 + 3 + 5 + 8 + 13 + 21.",
          ["54", "55", "53", "88"],
          "54",
          ["The sum runs over the first 8 Fibonacci terms (up to F₈ = 21).",
           "By the rule, this equals F₁₀ − 1.",
           "The sequence is 1,1,2,3,5,8,13,21,34,55, so F₁₀ = 55 and the sum is 55 − 1 = 54."],
          ["Forgetting the '− 1' and answering 55 (which is F₁₀ itself) misuses the identity; the running sum is always ONE LESS than F₁₀."],
          [v("Find 1 + 1 + 2 + 3 + 5 using the same rule.",
             "12",
             ["This is the first 5 terms (up to F₅ = 5), so it equals F₇ − 1.",
              "F₇ = 13, so the sum is 13 − 1 = 12."])],
          4, [139, 140]),
    ],
    # ──────────────── ch07 — A Tale of Three Intersecting Lines ──────────
    "ch07": [
        q("Can a triangle have sides 5 cm, 8 cm and 13 cm?",
          ["No — 5 + 8 = 13 is not greater than 13",
           "Yes, the sides are all different",
           "Yes, because 8 + 13 > 5",
           "No — the sides are too long"],
          "No — 5 + 8 = 13 is not greater than 13",
          ["The triangle inequality says any two sides together must be GREATER than the third.",
           "Here 5 + 8 = 13, which equals (not exceeds) the third side.",
           "The two short sides would lie flat along the long one, so no triangle closes."],
          ["Checking only the easy pair (8 + 13 > 5) and stopping misses the binding case — you must check the TWO SHORTEST sides against the longest."],
          [v("Can a triangle have sides 4 cm, 5 cm and 10 cm?",
             "No — 4 + 5 = 9 is less than 10",
             ["The two shortest sides sum to 9.",
              "9 < 10, so the triangle cannot close."])],
          3, [150, 151]),
        q("Two sides of a triangle measure 7 cm and 10 cm. What range must the third side x lie in?",
          ["3 < x < 17", "7 < x < 10", "x < 17", "3 ≤ x ≤ 17"],
          "3 < x < 17",
          ["The third side must be less than the sum of the other two: x < 7 + 10 = 17.",
           "It must also be more than their difference: x > 10 − 7 = 3.",
           "So 3 < x < 17 (strict inequalities — equality gives a flat, degenerate triangle)."],
          ["Using ≤ instead of < wrongly allows x = 3 or x = 17, which collapse the triangle into a straight line."],
          [v("Two sides are 6 cm and 6 cm. Give the range for the third side x.",
             "0 < x < 12",
             ["x < 6 + 6 = 12 and x > 6 − 6 = 0.",
              "So 0 < x < 12."])],
          5, [152, 153]),
        q("Two angles of a triangle are 48° and 67°. Find the third angle.",
          ["65°", "115°", "75°", "55°"],
          "65°",
          ["The three angles of any triangle add to 180°.",
           "48° + 67° = 115°.",
           "Third angle = 180° − 115° = 65°."],
          ["Stopping at 48° + 67° = 115° reports the sum of the first two, not the missing third angle."],
          [v("Two angles of a triangle are 90° and 35°. Find the third.",
             "55°",
             ["90° + 35° = 125°.",
              "180° − 125° = 55°."])],
          3, [154, 155]),
        q("A triangle has angles 90°, 45° and 45°. Classify it by its sides AND by its angles.",
          ["Right-angled and isosceles", "Acute and scalene",
           "Right-angled and scalene", "Obtuse and isosceles"],
          "Right-angled and isosceles",
          ["One angle is exactly 90°, so by angles it is right-angled.",
           "Two angles are equal (45° each), so the sides facing them are equal — by sides it is isosceles.",
           "Hence it is a right-angled isosceles triangle."],
          ["Calling it scalene ignores the two equal 45° angles, which force two equal sides."],
          [v("Classify a triangle with angles 70°, 70°, 40° by its sides and angles.",
             "Acute and isosceles",
             ["All angles are below 90°, so it is acute.",
              "Two equal angles (70°) make it isosceles."])],
          4, [168, 169]),
        q("An exterior angle of a triangle measures 120°. One of the two angles NOT next to it is 70°. Find the other.",
          ["50°", "60°", "70°", "110°"],
          "50°",
          ["The interior angle at that vertex = 180° − 120° = 60° (linear pair).",
           "The three interior angles add to 180°, so the other two sum to 180° − 60° = 120°.",
           "Given one is 70°, the other = 120° − 70° = 50°."],
          ["Treating 120° as an interior angle (and subtracting 70° from it) forgets it is the EXTERIOR angle, so its interior partner is 60°, not 120°."],
          [v("An exterior angle is 100°; one remote interior angle is 30°. Find the other remote interior angle.",
             "70°",
             ["The two remote interior angles add to the exterior angle: 100°.",
              "100° − 30° = 70°."])],
          4, [156, 157]),
        q("In a right-angled triangle, which two of the lines act as altitudes without being drawn separately?",
          ["The two legs (the sides meeting at the right angle)",
           "The hypotenuse and one leg",
           "All three medians",
           "None — altitudes must always be drawn inside"],
          "The two legs (the sides meeting at the right angle)",
          ["An altitude is a perpendicular from a vertex to the opposite side.",
           "In a right-angled triangle the two legs are already perpendicular to each other.",
           "So each leg is the altitude from one acute vertex to the opposite leg — two of the three altitudes are the legs themselves."],
          ["Assuming every altitude must be a fresh line inside the triangle misses that a right-angle's two legs already serve as altitudes."],
          [v("In a right-angled triangle, where do all three altitudes meet?",
             "At the right-angle vertex",
             ["Two altitudes are the legs, which meet at the right angle.",
              "The third altitude (from the right angle to the hypotenuse) also passes through that vertex, so all three meet there."])],
          4, [160, 161]),
    ],
    # ───────────────────────── ch08 — Working with Fractions ─────────────
    "ch08": [
        q("Find 3/4 × 20.",
          ["15", "60", "5", "80"],
          "15",
          ["Multiplying a fraction by a whole number: 3/4 × 20 = (3 × 20)/4.",
           "= 60/4.",
           "60 ÷ 4 = 15."],
          ["Multiplying only the numerator and forgetting to divide by 4 gives 60 — the denominator still divides the result."],
          [v("Find 2/5 × 35.",
             "14",
             ["(2 × 35)/5 = 70/5.",
              "70 ÷ 5 = 14."])],
          3, [175, 176]),
        q("What is 2/3 of 3/5?",
          ["2/5", "5/8", "6/8", "2/15"],
          "2/5",
          ["'Of' means multiply: 2/3 × 3/5.",
           "Multiply across: (2 × 3)/(3 × 5) = 6/15.",
           "Simplify 6/15 by dividing by 3: 2/5."],
          ["Adding the fractions instead of multiplying ('of' = ×, not +) gives a wrong, larger answer like 5/8."],
          [v("What is 3/4 of 8/9?",
             "2/3",
             ["3/4 × 8/9 = 24/36.",
              "24/36 = 2/3 after dividing by 12."])],
          4, [180, 181]),
        q("Compute 5/6 ÷ 2/3.",
          ["5/4", "10/18", "5/9", "4/5"],
          "5/4",
          ["Dividing by a fraction means multiplying by its reciprocal.",
           "5/6 ÷ 2/3 = 5/6 × 3/2 = 15/12.",
           "Simplify 15/12 by dividing by 3: 5/4 (which is 1¼)."],
          ["Multiplying straight across (5/6 × 2/3 = 10/18) skips the 'flip the divisor' step that division requires."],
          [v("Compute 3/8 ÷ 1/4.",
             "3/2",
             ["3/8 × 4/1 = 12/8.",
              "12/8 = 3/2."])],
          4, [186, 187]),
        q("A recipe needs 1½ cups of flour per cake. How many cups are needed for 2⅔ cakes?",
          ["4", "4⅙", "3", "4½"],
          "4",
          ["Write the mixed numbers as improper fractions: 1½ = 3/2 and 2⅔ = 8/3.",
           "Multiply: 3/2 × 8/3 = 24/6.",
           "24 ÷ 6 = 4 cups."],
          ["Multiplying only the whole-number parts (1 × 2 = 2) ignores the fractional cups; convert to improper fractions first."],
          [v("Each box weighs 2¼ kg. What do 1⅓ boxes weigh?",
             "3 kg",
             ["2¼ = 9/4 and 1⅓ = 4/3.",
              "9/4 × 4/3 = 36/12 = 3 kg."])],
          5, [182, 183]),
        q("Ahaan spends 1/3 of his money on a book, then 1/4 of what remains on a pen. What fraction of his original money is left?",
          ["1/2", "5/12", "1/4", "2/3"],
          "1/2",
          ["After the book, the remaining money is 1 − 1/3 = 2/3.",
           "The pen costs 1/4 OF that remainder: 1/4 × 2/3 = 1/6.",
           "Money left = 2/3 − 1/6 = 4/6 − 1/6 = 3/6 = 1/2."],
          ["Taking 1/4 of the ORIGINAL money (instead of of the remainder) is the classic error — the second fraction acts on what is left, 2/3, not on the whole."],
          [v("She gives away 1/2 her sweets, then eats 1/3 of the rest. What fraction of all the sweets is left?",
             "1/3",
             ["After giving away half, 1/2 remains.",
              "She eats 1/3 of 1/2 = 1/6, leaving 1/2 − 1/6 = 1/3."])],
          5, [184, 185]),
        q("Dividing by which number gives the same result as multiplying by 4/5?",
          ["5/4", "4/5", "5", "20"],
          "5/4",
          ["Dividing by a number n is the same as multiplying by its reciprocal 1/n.",
           "So multiplying by 4/5 must match dividing by the reciprocal of 4/5.",
           "The reciprocal of 4/5 is 5/4, so dividing by 5/4 = multiplying by 4/5."],
          ["Answering 4/5 confuses the operation — dividing by 4/5 is the same as MULTIPLYING by 5/4, the opposite of what's asked."],
          [v("Multiplying by 2/3 is the same as dividing by what?",
             "3/2",
             ["Dividing by 3/2 = multiplying by its reciprocal 2/3.",
              "So the answer is 3/2."])],
          4, [186, 187]),
    ],
    # ───────────────────────── ch09 — Geometric Twins ────────────────────
    "ch09": [
        q("Two triangles have all three pairs of corresponding sides equal. Which congruence rule applies?",
          ["SSS", "SAS", "ASA", "RHS"],
          "SSS",
          ["The three matching pieces given are all sides.",
           "Side-Side-Side (SSS) says three equal pairs of sides fix a triangle completely.",
           "So the triangles are congruent by SSS."],
          ["Choosing SAS or ASA assumes an angle is given; here only the three sides are stated, which is exactly the SSS case."],
          [v("Two triangles share two equal sides and the equal angle BETWEEN them. Which rule applies?",
             "SAS",
             ["Two sides and the included angle are equal.",
              "That is the Side-Angle-Side (SAS) criterion."])],
          4, [10, 11]),
        q("Which set of equal parts does NOT guarantee that two triangles are congruent?",
          ["Three pairs of equal angles (AAA)", "SSS", "SAS", "ASA"],
          "Three pairs of equal angles (AAA)",
          ["SSS, SAS and ASA each pin a triangle's size and shape completely.",
           "Equal angles (AAA) fix only the SHAPE — the triangles can still be different sizes (one a scaled copy of the other).",
           "So AAA gives similar, not necessarily congruent, triangles."],
          ["Believing 'same angles means same triangle' confuses congruence (same shape AND size) with similarity (same shape only)."],
          [v("Does knowing two angles and the side BETWEEN them (ASA) guarantee congruence?",
             "Yes",
             ["ASA fixes the triangle uniquely.",
              "Two triangles meeting ASA are congruent."])],
          5, [12, 13]),
        q("How many degrees is each angle of an equilateral triangle?",
          ["60°", "90°", "45°", "180°"],
          "60°",
          ["An equilateral triangle has three equal sides, so all three angles are equal.",
           "The angles add to 180°, so each is 180° ÷ 3.",
           "180° ÷ 3 = 60°."],
          ["Answering 180° gives the SUM of the three angles, not the size of one."],
          [v("Each angle of an equilateral triangle is 60°. What is the sum of any two of them?",
             "120°",
             ["Each angle is 60°.",
              "Two of them: 60° + 60° = 120°."])],
          3, [16, 17]),
        q("An isosceles triangle has an apex (vertex) angle of 40°. Find each base angle.",
          ["70°", "40°", "140°", "100°"],
          "70°",
          ["The two base angles of an isosceles triangle are equal.",
           "They share what's left after the apex: 180° − 40° = 140°.",
           "Split equally: 140° ÷ 2 = 70° each."],
          ["Forgetting to halve and answering 140° gives the COMBINED base angles, not one of them."],
          [v("An isosceles triangle has base angles of 50° each. Find the apex angle.",
             "80°",
             ["Base angles total 50° + 50° = 100°.",
              "Apex = 180° − 100° = 80°."])],
          4, [17, 18]),
        q("In triangle ABC, angle B = angle C = 50°. Which two sides must be equal?",
          ["AB = AC", "AB = BC", "BC = AC", "All three are equal"],
          "AB = AC",
          ["Equal angles face equal sides (the converse of the isosceles theorem).",
           "Angle B faces side AC; angle C faces side AB.",
           "Since angle B = angle C, the sides facing them are equal: AB = AC."],
          ["Pairing the equal angles with the side BETWEEN them (BC) is wrong — a side is matched with the angle OPPOSITE it, not the one between the two equal angles."],
          [v("In triangle PQR, angle P = angle R. Which sides are equal?",
             "PQ = QR",
             ["Angle P faces QR; angle R faces PQ.",
              "Equal angles face equal sides, so QR = PQ."])],
          4, [17, 18]),
        q("Two right-angled triangles have equal hypotenuses and one pair of equal legs. Which rule proves them congruent?",
          ["RHS", "SSS", "ASA", "SAS"],
          "RHS",
          ["Both triangles have a right angle (R), equal hypotenuses (H) and one equal side (S).",
           "That matches the Right angle–Hypotenuse–Side criterion.",
           "So they are congruent by RHS."],
          ["Trying SAS fails: the equal angle (the right angle) is not BETWEEN the hypotenuse and the equal leg, so the special RHS rule is the one that applies."],
          [v("Two right triangles share an equal hypotenuse and an equal acute angle. Which rule fits?",
             "ASA (or AAS)",
             ["The right angle, the acute angle and the hypotenuse give two angles and a side.",
              "That is the ASA/AAS situation, which guarantees congruence."])],
          4, [13, 14]),
    ],
    # ───────────────────────── ch10 — Operations with Integers ───────────
    "ch10": [
        q("Compute (−7) + (+12) + (−5).",
          ["0", "−24", "10", "−10"],
          "0",
          ["Group the negatives: (−7) + (−5) = −12.",
           "Add the positive: −12 + 12.",
           "−12 + 12 = 0."],
          ["Adding the digits and keeping a minus sign (−24) ignores that +12 cancels the negative total."],
          [v("Compute (−9) + (+4) + (+5).",
             "0",
             ["Positives: 4 + 5 = 9.",
              "−9 + 9 = 0."])],
          3, [25, 26]),
        q("Compute (−8) − (−15).",
          ["7", "−23", "−7", "23"],
          "7",
          ["Subtracting a negative means adding its opposite.",
           "(−8) − (−15) = −8 + 15.",
           "−8 + 15 = 7."],
          ["Reading the double minus as a single minus (−8 − 15 = −23) skips the rule that subtracting a negative is addition."],
          [v("Compute (−5) − (−12).",
             "7",
             ["−5 − (−12) = −5 + 12.",
              "= 7."])],
          4, [29, 30]),
        q("Compute (−6) × (−4) × (−2).",
          ["−48", "48", "−12", "12"],
          "−48",
          ["Multiply the first two: (−6) × (−4) = +24 (negative × negative = positive).",
           "Multiply by the third: 24 × (−2) = −48.",
           "Three negative factors give a negative product."],
          ["Stopping after two negatives and keeping it positive (48) forgets the THIRD negative factor flips the sign back."],
          [v("Compute (−2) × (−3) × (−5).",
             "−30",
             ["(−2)×(−3) = 6.",
              "6 × (−5) = −30 (an odd number of negatives → negative)."])],
          4, [40, 41]),
        q("The product of several non-zero integers is negative. What does this tell you about the negative factors?",
          ["There is an odd number of negative factors",
           "There is an even number of negative factors",
           "There is exactly one negative factor",
           "All the factors are negative"],
          "There is an odd number of negative factors",
          ["Each pair of negative factors multiplies to a positive, cancelling its sign.",
           "If the negatives pair up evenly the product is positive; one left over makes it negative.",
           "So a negative product means an ODD number of negative factors."],
          ["Concluding 'exactly one' is too strong — three or five negatives also give a negative product; the rule is about the count being odd, not equal to one."],
          [v("The product of several non-zero integers is positive. What about the negative factors?",
             "There is an even number of them (possibly zero)",
             ["Negatives cancel in pairs.",
              "A positive product means an even count of negative factors."])],
          5, [42, 43]),
        q("A diver is 18 m below sea level (−18 m). She rises 7 m, then descends 12 m. What is her final depth?",
          ["−23 m", "−13 m", "−7 m", "−37 m"],
          "−23 m",
          ["Start at −18. Rising 7 m adds: −18 + 7 = −11.",
           "Descending 12 m subtracts: −11 − 12 = −23.",
           "Her final depth is −23 m (23 m below sea level)."],
          ["Adding the 12 m descent (−11 + 12) instead of subtracting it confuses 'down' with 'up' — descending makes the depth more negative."],
          [v("A lift starts at −2 (basement 2), goes up 5 floors, then down 3. Where is it?",
             "0 (ground floor)",
             ["−2 + 5 = 3.",
              "3 − 3 = 0, the ground floor."])],
          4, [27, 28]),
        q("Evaluate (−3) × (5 − 8) + (−2) × (−4).",
          ["17", "1", "−17", "25"],
          "17",
          ["Brackets first: 5 − 8 = −3.",
           "Now (−3) × (−3) = 9 and (−2) × (−4) = 8.",
           "Add: 9 + 8 = 17."],
          ["Getting the sign of (−3) × (−3) wrong (writing −9) flips the answer — negative times negative is positive."],
          [v("Evaluate (−4) × (2 − 5) + (−3) × (−1).",
             "15",
             ["2 − 5 = −3, so (−4) × (−3) = 12.",
              "(−3) × (−1) = 3; 12 + 3 = 15."])],
          5, [41, 42]),
    ],
    # ───────────────────────── ch11 — Finding Common Ground ──────────────
    "ch11": [
        q("Find the HCF (highest common factor) of 24 and 36.",
          ["12", "6", "72", "4"],
          "12",
          ["Prime-factorise: 24 = 2³ × 3 and 36 = 2² × 3².",
           "Take each shared prime to its LOWEST power: 2² × 3 = 4 × 3.",
           "4 × 3 = 12, the HCF."],
          ["Choosing 72 confuses the HCF (the largest common FACTOR) with the LCM (the smallest common multiple)."],
          [v("Find the HCF of 18 and 30.",
             "6",
             ["18 = 2 × 3², 30 = 2 × 3 × 5.",
              "Shared at lowest power: 2 × 3 = 6."])],
          3, [42, 43]),
        q("Find the LCM (least common multiple) of 12 and 18.",
          ["36", "6", "72", "216"],
          "36",
          ["Prime-factorise: 12 = 2² × 3 and 18 = 2 × 3².",
           "Take each prime to its HIGHEST power: 2² × 3² = 4 × 9.",
           "4 × 9 = 36, the LCM."],
          ["Multiplying the two numbers (12 × 18 = 216) gives a common multiple but not the LEAST one — divide by the HCF (6) to get 36."],
          [v("Find the LCM of 8 and 12.",
             "24",
             ["8 = 2³, 12 = 2² × 3.",
              "Highest powers: 2³ × 3 = 24."])],
          4, [48, 49]),
        q("For two numbers, HCF = 6 and LCM = 72. If one number is 24, find the other.",
          ["18", "12", "36", "8"],
          "18",
          ["For any two numbers, (first) × (second) = HCF × LCM.",
           "So 24 × (other) = 6 × 72 = 432.",
           "Other = 432 ÷ 24 = 18."],
          ["Adding or subtracting HCF and LCM instead of using the product rule (HCF × LCM = product of the numbers) gives a wrong value."],
          [v("HCF = 4, LCM = 48, one number is 16. Find the other.",
             "12",
             ["Product = 4 × 48 = 192.",
              "192 ÷ 16 = 12."])],
          4, [56, 57]),
        q("Which pair of numbers is co-prime (HCF = 1)?",
          ["8 and 15", "8 and 12", "9 and 15", "10 and 25"],
          "8 and 15",
          ["Co-prime numbers share no common factor except 1.",
           "8 = 2³ and 15 = 3 × 5 — no shared prime, so HCF = 1.",
           "The other pairs share a factor (4, 3 and 5 respectively), so they are not co-prime."],
          ["Assuming co-prime means 'both prime' is wrong — 8 and 15 are co-prime even though neither is prime, because they share no common factor."],
          [v("Which pair is co-prime: 14 and 25, or 14 and 21?",
             "14 and 25",
             ["14 = 2 × 7, 25 = 5², share nothing → HCF 1.",
              "14 and 21 share 7, so they are not co-prime."])],
          3, [44, 45]),
        q("Two bells ring at intervals of 18 minutes and 24 minutes. If they ring together at 9:00 am, when do they next ring together?",
          ["10:12 am", "9:42 am", "10:00 am", "11:00 am"],
          "10:12 am",
          ["They coincide again after LCM(18, 24) minutes.",
           "18 = 2 × 3², 24 = 2³ × 3 → LCM = 2³ × 3² = 72 minutes.",
           "72 minutes = 1 hour 12 minutes after 9:00 am, i.e. 10:12 am."],
          ["Using the HCF (6 minutes) instead of the LCM finds a wrong, too-small interval — synchronising cycles is always an LCM question."],
          [v("Two lights flash every 8 s and 12 s, together now. When do they next flash together?",
             "after 24 seconds",
             ["LCM(8, 12) = 24.",
              "They next coincide 24 seconds later."])],
          5, [50, 51]),
        q("What is the longest tape length that can exactly measure 7 m, 3.85 m and 12.95 m?",
          ["35 cm", "5 cm", "7 cm", "70 cm"],
          "35 cm",
          ["Convert to centimetres: 700 cm, 385 cm and 1295 cm.",
           "Factorise: 700 = 2² × 5² × 7, 385 = 5 × 7 × 11, 1295 = 5 × 7 × 37.",
           "Common primes at lowest power: 5 × 7 = 35 cm, the HCF."],
          ["Finding the LARGEST exact measure is an HCF problem, not LCM — the tape must divide all three lengths, so take the highest COMMON factor."],
          [v("Largest tape to exactly measure 6 m and 9 m?",
             "300 cm (3 m)",
             ["600 cm and 900 cm; HCF = 300 cm.",
              "So a 3 m tape measures both exactly."])],
          5, [46, 47]),
    ],
    # ──────────────── ch12 — Another Peek Beyond the Point ───────────────
    "ch12": [
        q("Compute 0.6 × 0.4.",
          ["0.24", "2.4", "0.024", "24"],
          "0.24",
          ["Multiply as whole numbers: 6 × 4 = 24.",
           "Count decimal places in the factors: 0.6 has 1 and 0.4 has 1, so 2 in total.",
           "Place the point 2 digits from the right: 0.24."],
          ["Answering 2.4 uses only one decimal place — the two factors together contribute TWO places, so the product is 0.24."],
          [v("Compute 0.3 × 0.7.",
             "0.21",
             ["3 × 7 = 21, two decimal places total.",
              "Point 2 from the right: 0.21."])],
          3, [68, 69]),
        q("Compute 3.45 × 1000.",
          ["3450", "345", "34500", "3.45000"],
          "3450",
          ["Multiplying by 1000 shifts the decimal point 3 places to the right.",
           "3.45 → 34.5 → 345. → 3450. (filling a zero for the missing place).",
           "The result is 3450."],
          ["Adding three zeros to the end (3.45000) confuses multiplying by 1000 with simply appending zeros — the POINT must move, not the digits stay put."],
          [v("Compute 0.072 × 100.",
             "7.2",
             ["× 100 shifts the point 2 places right.",
              "0.072 → 7.2."])],
          3, [70, 71]),
        q("Compute 4.8 ÷ 0.6.",
          ["8", "0.8", "80", "0.08"],
          "8",
          ["Multiply both numbers by 10 to clear the divisor's decimal: 48 ÷ 6.",
           "48 ÷ 6 = 8.",
           "Since both were scaled the same way, the quotient is unchanged: 8."],
          ["Dividing 4.8 by 6 (giving 0.8) forgets that the divisor is 0.6, not 6 — scale both numbers up by 10 first."],
          [v("Compute 1.5 ÷ 0.3.",
             "5",
             ["Scale by 10: 15 ÷ 3.",
              "= 5."])],
          4, [74, 75]),
        q("A product was computed and gave the digits '900'. If the calculation was 2.5 × 3.6, where does the decimal point go?",
          ["9.00", "90.0", "0.900", "900"],
          "9.00",
          ["Estimate first: 2.5 × 3.6 is about 2.5 × 4 = 10, so the answer is near 9 or 10.",
           "Only 9.00 is in that range; 90 and 0.9 are ten times off.",
           "(Exactly, 2.5 × 3.6 = 9.00.)"],
          ["Just counting decimal places without a sanity-check can misplace the point — estimating that the answer should be 'about 10' confirms 9.00."],
          [v("The digits '144' came from 4.8 × 3. Where does the point go?",
             "14.4",
             ["Estimate: 4.8 × 3 ≈ 15.",
              "So the answer near 15 is 14.4."])],
          5, [80, 81]),
        q("Compute 57.3 ÷ 100.",
          ["0.573", "5.73", "5730", "0.0573"],
          "0.573",
          ["Dividing by 100 shifts the decimal point 2 places to the LEFT.",
           "57.3 → 5.73 → 0.573.",
           "The result is 0.573."],
          ["Shifting the point right (giving 5730) is what MULTIPLYING by 100 does — division moves it the other way."],
          [v("Compute 8.4 ÷ 1000.",
             "0.0084",
             ["× by 1/1000 shifts the point 3 places left.",
              "8.4 → 0.0084."])],
          4, [70, 71]),
        q("Apples cost ₹85.50 per kg. What do 2.4 kg cost?",
          ["₹205.20", "₹2052", "₹20.52", "₹171"],
          "₹205.20",
          ["Multiply as whole numbers: 855 × 24 = 20520.",
           "Count decimal places: 85.5 has 1 and 2.4 has 1, so 2 in total.",
           "Place the point 2 digits from the right: 205.20, so 2.4 kg cost ₹205.20."],
          ["Multiplying only the whole-kilogram price (85.5 × 2 = 171) ignores the extra 0.4 kg; the full 2.4 kg must be used."],
          [v("Rice costs ₹42.50 per kg. Cost of 3.2 kg?",
             "₹136",
             ["42.5 × 3.2: 425 × 32 = 13600, two decimal places → 136.00.",
              "So ₹136."])],
          5, [72, 73]),
    ],
    # ───────────────────────── ch13 — Connecting the Dots ────────────────
    "ch13": [
        q("Find the mean of 12, 15, 18, 11, 14.",
          ["14", "15", "12", "70"],
          "14",
          ["Add all the values: 12 + 15 + 18 + 11 + 14 = 70.",
           "Divide by how many there are: 70 ÷ 5.",
           "70 ÷ 5 = 14, the mean."],
          ["Reporting the total (70) instead of dividing by 5 confuses the SUM with the mean."],
          [v("Find the mean of 6, 9, 12, 13.",
             "10",
             ["Sum = 40.",
              "40 ÷ 4 = 10."])],
          3, [104, 105]),
        q("Find the median of 7, 3, 9, 5, 11, 4.",
          ["6", "5", "7", "5.5"],
          "6",
          ["Sort the data: 3, 4, 5, 7, 9, 11.",
           "With an even count (6 values), the median is the average of the two middle values, 5 and 7.",
           "(5 + 7) ÷ 2 = 6."],
          ["Forgetting to SORT first (and just taking the middle of the unsorted list) gives the wrong median; the median is positional and needs order."],
          [v("Find the median of 8, 2, 5, 10.",
             "6.5",
             ["Sorted: 2, 5, 8, 10.",
              "Middle two are 5 and 8: (5 + 8)/2 = 6.5."])],
          4, [105, 106]),
        q("Find the mode of 4, 7, 4, 9, 7, 4, 2.",
          ["4", "7", "9", "2"],
          "4",
          ["The mode is the most frequently occurring value.",
           "Count: 4 appears 3 times, 7 appears twice, 9 and 2 once each.",
           "4 occurs most often, so the mode is 4."],
          ["Picking 7 (the next-most-common) or the largest value misreads 'mode' — it is the value with the HIGHEST frequency."],
          [v("Find the mode of 5, 5, 8, 8, 8, 1.",
             "8",
             ["8 appears 3 times, more than any other.",
              "So the mode is 8."])],
          3, [104, 105]),
        q("The marks are 45, 78, 33, 90, 60. Find the range.",
          ["57", "90", "45", "33"],
          "57",
          ["The range is the largest value minus the smallest.",
           "Largest = 90, smallest = 33.",
           "90 − 33 = 57."],
          ["Reporting the maximum (90) instead of the difference confuses the range with the largest value."],
          [v("Find the range of 12, 19, 7, 25, 14.",
             "18",
             ["Largest 25, smallest 7.",
              "25 − 7 = 18."])],
          3, [106, 107]),
        q("The mean of five numbers is 20. Four of them are 18, 22, 15 and 25. Find the fifth.",
          ["20", "80", "18", "25"],
          "20",
          ["If the mean of five numbers is 20, their total is 5 × 20 = 100.",
           "The four known numbers add to 18 + 22 + 15 + 25 = 80.",
           "The fifth = 100 − 80 = 20."],
          ["Averaging just the four known numbers ignores the fixed total the mean implies — reconstruct the SUM (100) first, then subtract."],
          [v("The mean of four numbers is 10. Three are 8, 12, 6. Find the fourth.",
             "14",
             ["Total = 4 × 10 = 40.",
              "Known sum = 26, so fourth = 40 − 26 = 14."])],
          5, [105, 106]),
        q("A shopkeeper wants to know which shoe size to stock the most. Which measure of central tendency should he use?",
          ["Mode", "Mean", "Median", "Range"],
          "Mode",
          ["He needs the size that the most customers buy — the most frequent value.",
           "The most frequent value in a data set is the mode.",
           "So he should use the mode."],
          ["The mean shoe size could be a value (like 7.4) that no one actually wears — for 'most common', the mode is the right measure, not the average."],
          [v("Which measure best summarises the 'typical' family income in a town with a few billionaires?",
             "Median",
             ["A few huge incomes drag the mean upward.",
              "The median (middle value) resists those outliers, so it best reflects a typical family."])],
          5, [101, 102]),
    ],
    # ───────────────────────── ch14 — Constructions and Tilings ──────────
    "ch14": [
        q("Regular hexagons tile the plane. How many of them meet at each vertex?",
          ["3", "4", "6", "2"],
          "3",
          ["A regular hexagon's interior angle is 120°.",
           "The shapes around a vertex must fill exactly 360°.",
           "360° ÷ 120° = 3, so three hexagons meet at each vertex."],
          ["Confusing the number of SIDES (6) with the number meeting at a vertex (3) — the count comes from 360° ÷ interior angle."],
          [v("How many squares meet at a vertex when squares tile the plane?",
             "4",
             ["A square's interior angle is 90°.",
              "360° ÷ 90° = 4."])],
          4, [164, 165]),
        q("Which of these regular polygons CANNOT tile the plane by itself?",
          ["Regular pentagon", "Equilateral triangle", "Square", "Regular hexagon"],
          "Regular pentagon",
          ["A regular polygon tiles alone only if its interior angle divides 360° a whole number of times.",
           "Triangle 60° (×6), square 90° (×4), hexagon 120° (×3) all divide 360° exactly.",
           "A regular pentagon's angle is 108°, and 360 ÷ 108 ≈ 3.33 — not a whole number, so pentagons leave gaps."],
          ["Assuming any regular shape can tile is wrong — only the triangle, square and hexagon do, because only their angles divide 360° evenly."],
          [v("Does a regular octagon (interior angle 135°) tile the plane by itself?",
             "No",
             ["360 ÷ 135 ≈ 2.67, not a whole number.",
              "So octagons alone leave gaps and cannot tile."])],
          5, [164, 165]),
        q("Bisecting a 60° angle with only a compass and straightedge produces which angle?",
          ["30°", "45°", "20°", "50°"],
          "30°",
          ["Bisecting means cutting an angle into two equal halves.",
           "Half of 60° is 60° ÷ 2.",
           "60° ÷ 2 = 30°."],
          ["Trying to TRISECT a 60° angle to get 20° is impossible with compass and straightedge — only bisection (halving) is constructible here, giving 30°."],
          [v("Bisecting a right angle gives what angle?",
             "45°",
             ["A right angle is 90°.",
              "Half of 90° is 45°."])],
          3, [158, 159]),
        q("Every point on the perpendicular bisector of segment AB is …",
          ["equidistant from A and B", "closer to A than to B",
           "the midpoint of AB only", "somewhere on segment AB"],
          "equidistant from A and B",
          ["The perpendicular bisector is the set (locus) of all points the same distance from both ends.",
           "That is exactly why the equal-arc construction works — each arc-crossing is an equal radius from A and from B.",
           "So every point on it is equidistant from A and B."],
          ["Thinking only the MIDPOINT is equidistant misses that the WHOLE perpendicular bisector line shares this equal-distance property."],
          [v("To place a flagpole equally far from two trees, where should it go?",
             "Anywhere on the perpendicular bisector of the segment joining the trees",
             ["Points equidistant from two fixed points form the perpendicular bisector.",
              "So the pole goes somewhere on that line."])],
          4, [150, 151]),
        q("At a vertex in a tiling, two regular octagons (interior angle 135°) meet along with one more regular polygon. What is that polygon, and its interior angle?",
          ["A square, 90°", "An octagon, 45°", "A triangle, 60°", "A hexagon, 120°"],
          "A square, 90°",
          ["The angles at a vertex must total 360°.",
           "Two octagons use 2 × 135° = 270°.",
           "The third angle = 360° − 270° = 90°, which is a square."],
          ["Forgetting the 360°-at-a-vertex rule (or using only one octagon's 135°) gives the wrong leftover angle."],
          [v("A square (90°) and two identical regular polygons meet at a vertex. What is each of their angles?",
             "135° each",
             ["360° − 90° = 270° shared by two equal angles.",
              "270° ÷ 2 = 135°, the angle of a regular octagon."])],
          5, [164, 165]),
        q("A tangram's 7 pieces are rearranged from a square into a swan shape. How does the total area change?",
          ["It stays the same", "It doubles", "It halves", "It depends on the shape made"],
          "It stays the same",
          ["The same 7 pieces are used, just moved around.",
           "Rearranging pieces never creates or destroys area — area is conserved.",
           "So the swan has exactly the same total area as the original square."],
          ["Assuming a 'bigger-looking' shape has more area confuses appearance with area — moving pieces keeps the total area fixed."],
          [v("Two figures are made from the SAME set of tangram pieces. Compare their areas.",
             "They are equal",
             ["Both use every piece exactly once.",
              "Conservation of area makes the totals equal."])],
          4, [166, 167]),
    ],
    # ───────────────────────── ch15 — Finding the Unknown ────────────────
    "ch15": [
        q("Solve 3x − 5 = 16.",
          ["7", "21", "11", "3"],
          "7",
          ["Add 5 to both sides to undo the −5: 3x = 21.",
           "Divide both sides by 3 to undo the ×3: x = 21 ÷ 3.",
           "x = 7."],
          ["Dividing by 3 before adding 5 (or only doing one side) breaks the balance — undo the +/− first, then the ×/÷."],
          [v("Solve 4x + 3 = 23.",
             "5",
             ["Subtract 3: 4x = 20.",
              "Divide by 4: x = 5."])],
          3, [178, 179]),
        q("Solve 2(x + 3) = 14.",
          ["4", "7", "5", "8"],
          "4",
          ["Divide both sides by 2: x + 3 = 7. (Or expand: 2x + 6 = 14.)",
           "Subtract 3 from both sides: x = 4.",
           "Check: 2(4 + 3) = 2 × 7 = 14. ✓"],
          ["Distributing the 2 to only the x (writing 2x + 3 = 14) forgets it also multiplies the 3 — the bracket means 2 × (x + 3)."],
          [v("Solve 3(x − 2) = 18.",
             "8",
             ["Divide by 3: x − 2 = 6.",
              "Add 2: x = 8."])],
          4, [180, 181]),
        q("Solve 5x + 2 = 3x + 14.",
          ["6", "8", "2", "16"],
          "6",
          ["Gather the x-terms on one side: subtract 3x from both sides → 2x + 2 = 14.",
           "Subtract 2 from both sides: 2x = 12.",
           "Divide by 2: x = 6."],
          ["Moving the 3x without changing its sign (or subtracting it from only one side) unbalances the equation — do the same operation to BOTH sides."],
          [v("Solve 7x − 4 = 2x + 11.",
             "3",
             ["Subtract 2x: 5x − 4 = 11.",
              "Add 4: 5x = 15, so x = 3."])],
          5, [182, 183]),
        q("Is x = 5 a solution of 4x − 3 = 17?",
          ["Yes", "No, x should be 4", "No, x should be 6", "Cannot be decided"],
          "Yes",
          ["Substitute x = 5 into the left side: 4 × 5 − 3.",
           "= 20 − 3 = 17.",
           "The left side equals the right side (17), so x = 5 IS a solution."],
          ["Skipping the substitution check and guessing is risky — verifying by plugging the value back in is the reliable test of a solution."],
          [v("Is x = 3 a solution of 2x + 5 = 12?",
             "No — it gives 11, not 12",
             ["2 × 3 + 5 = 11.",
              "11 ≠ 12, so x = 3 is not a solution."])],
          4, [186, 187]),
        q("Ahaan is 4 years older than his sister. The sum of their ages is 26. How old is Ahaan?",
          ["15", "11", "13", "22"],
          "15",
          ["Let the sister's age be s; Ahaan's age is s + 4.",
           "Their sum: s + (s + 4) = 26, so 2s + 4 = 26, giving 2s = 22 and s = 11.",
           "Ahaan = s + 4 = 11 + 4 = 15."],
          ["Splitting 26 evenly into 13 and 13 ignores the 4-year gap; set up the equation with s and s + 4 first."],
          [v("Two numbers differ by 6 and add to 30. Find the larger.",
             "18",
             ["Let the smaller be n; n + (n + 6) = 30, so 2n = 24, n = 12.",
              "The larger is 12 + 6 = 18."])],
          5, [184, 185]),
        q("Solve x/3 + 4 = 10.",
          ["18", "6", "42", "2"],
          "18",
          ["Subtract 4 from both sides: x/3 = 6.",
           "Multiply both sides by 3 to undo the division: x = 6 × 3.",
           "x = 18."],
          ["Multiplying only the x by 3 (and not the whole side) or subtracting 4 after multiplying breaks the balance — undo the +4 first, then the ÷3."],
          [v("Solve x/5 − 2 = 3.",
             "25",
             ["Add 2: x/5 = 5.",
              "Multiply by 5: x = 25."])],
          5, [186, 187]),
    ],
}


def main():
    pack = json.loads(PACK.read_text(encoding="utf-8"))

    # Map chapter id → set of its concept ids (sanity context; boss questions
    # are chapter-level, no parent anchor needed, but we keep the chapter set
    # for the lint to confirm we touch only known chapters).
    chapter_ids = {ch["id"] for ch in pack["chapters"]}
    for cid in BOSS:
        if cid not in chapter_ids:
            raise SystemExit(f"BOSS references unknown chapter {cid}")

    seen_ids = set()
    total = 0
    for ch in pack["chapters"]:
        items = BOSS.get(ch["id"])
        if not items:
            raise SystemExit(f"No bossQuestions authored for {ch['id']}")
        if len(items) < PER_CHAPTER:
            raise SystemExit(f"{ch['id']} has only {len(items)} boss questions (<{PER_CHAPTER})")
        ns = "m" + ch["id"]  # ch01 → mch01, the Maths boss-id namespace token
        built = []
        for i, it in enumerate(items):
            qid = f"bossquiz_{ns}_q{i:02d}"
            if qid in seen_ids:
                raise SystemExit(f"Duplicate boss id {qid}")
            seen_ids.add(qid)
            q_obj = {"id": qid}
            q_obj.update(it)
            built.append(q_obj)
        ch["bossQuestions"] = built
        total += len(built)

    PACK.write_text(json.dumps(pack, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Injected {total} bossQuestions across {len(pack['chapters'])} Maths chapters "
          f"({PER_CHAPTER}/chapter).")


if __name__ == "__main__":
    main()
