import XCTest
@testable import desktopAhaan

/// Wiring contract for the "Common Mistakes" card on
/// `ChapterDetailView`. Same shape as
/// `BeyondTheBookRoutingTests` — the surface was added 2026-05-26
/// to bring chapter-level enrichment-article coverage to 19/19
/// chapters (Ch.1 has a bespoke 10-entry article, Ch.2-19 have
/// templated 5-entry articles generated by
/// `scripts/generate_mistakes_articles.py`).
///
/// These tests lock the wiring so a future content edit OR a
/// hardcoded chapter-number off-by-one can't silently mis-route
/// the modal (same failure-mode shape the Beyond ratchet
/// guards against).
final class CommonMistakesRoutingTests: XCTestCase {

    /// Every `_mistakes` entry in `ArticleIndex.entries` must have
    /// matching chapter prefixes on its key, id, filename, and
    /// chapterFolder. An off-by-one (e.g. `key = "ch01_mistakes"`
    /// pointing at `filename = "ch02_mistakes.html"`) fails this
    /// loudly with the offending key.
    func testEveryMistakesEntryIsInternallyConsistent() {
        let keys = ArticleIndex.entries.keys.filter { $0.hasSuffix("_mistakes") && !$0.hasPrefix("mch") && !$0.hasPrefix("sch") }
        XCTAssertFalse(keys.isEmpty,
            "Expected at least one Common-Mistakes entry in ArticleIndex.entries.")
        for key in keys {
            guard let entry = ArticleIndex.entries[key] else {
                XCTFail("Lookup miss for key '\(key)' enumerated from entries.")
                continue
            }
            XCTAssertEqual(entry.id, key,
                "Entry '\(key)' has id '\(entry.id)' — must equal key for the " +
                "ChapterDetailView lookup `entries[\"\\(chapter.id)_mistakes\"]` " +
                "to resolve correctly.")
            XCTAssertEqual(entry.filename, "\(key).html",
                "Entry '\(key)' has filename '\(entry.filename)' — must be " +
                "'\(key).html' so the modal loads the right file.")
            let chPrefix = chapterPrefix(from: key)
            let chNumber = Int(chPrefix.dropFirst(2)) ?? -1
            XCTAssertEqual(entry.chapterFolder, "Articles/Chapter\(chNumber)",
                "Entry '\(key)' has chapterFolder '\(entry.chapterFolder)' — must " +
                "be 'Articles/Chapter\(chNumber)' for the bundle resolution to " +
                "find the file. An off-by-one here is the 2026-05-25-reported " +
                "Beyond bug shape, repeated for Mistakes.")
        }
    }

    /// Every science chapter MUST publish a Common-Mistakes entry
    /// after the 2026-05-26 consistency push — this is the 19/19
    /// coverage assertion. If a future content edit accidentally
    /// removes one, this test fails with the chapter id.
    func testEveryChapterHasMistakesArticleEntry() throws {
        let pack = try loadSciencePack()
        var missing: [String] = []
        for chapter in pack.chapters {
            let key = "\(chapter.id)_mistakes"
            if ArticleIndex.entries[key] == nil {
                missing.append(chapter.id)
            }
        }
        XCTAssertTrue(missing.isEmpty,
            "These chapters are missing a `_mistakes` entry in " +
            "ArticleIndex.entries — the SUPERPROMPT 2026-05-26 brought " +
            "this surface to 19/19; a regression here breaks the " +
            "CommonMistakesCard on the chapter detail screen:\n" +
            missing.map { "  - \($0)" }.joined(separator: "\n"))
    }

    /// Each Mistakes HTML file MUST exist in Bundle.main AND its
    /// title/breadcrumb must contain the correct "Chapter N"
    /// reference. Catches content-author copy-paste errors at
    /// test time.
    func testMistakesHtmlFilesExistAndTitleMatchesChapter() throws {
        let keys = ArticleIndex.entries.keys.filter { $0.hasSuffix("_mistakes") && !$0.hasPrefix("mch") && !$0.hasPrefix("sch") }
        for key in keys {
            guard let entry = ArticleIndex.entries[key] else { continue }
            let name = entry.filename.replacingOccurrences(of: ".html", with: "")
            let url = Bundle.main.url(forResource: name, withExtension: "html",
                                      subdirectory: entry.chapterFolder)
                ?? Bundle.main.url(forResource: name, withExtension: "html")
            guard let resolved = url, let html = try? String(contentsOf: resolved, encoding: .utf8) else {
                XCTFail("Mistakes HTML for '\(key)' not findable in bundle " +
                        "(filename='\(entry.filename)', folder='\(entry.chapterFolder)').")
                continue
            }
            let chPrefix = chapterPrefix(from: key)
            let expectedFragment = "Chapter \(Int(chPrefix.dropFirst(2)) ?? -1)"
            XCTAssertTrue(html.contains(expectedFragment),
                "Mistakes HTML at \(resolved.lastPathComponent) doesn't contain " +
                "'\(expectedFragment)' in title/breadcrumb/h1. The file's content " +
                "might be from the wrong chapter — exactly the failure shape the " +
                "Beyond ratchet (cb39f8d) was added for.")
        }
    }

    /// Defensive — every generated mistakes article must have at
    /// least 3 misconception sections. The generator
    /// `scripts/generate_mistakes_articles.py` already enforces this
    /// (skips chapters with < 3 misconceptions), but pin it here so
    /// a hand-edit that deletes a section can't silently land.
    func testGeneratedMistakesArticlesHaveAtLeastThreeSections() throws {
        let keys = ArticleIndex.entries.keys.filter { $0.hasSuffix("_mistakes") && !$0.hasPrefix("mch") && !$0.hasPrefix("sch") }
        for key in keys {
            // Ch.1's bespoke 10-section article is exempt — it's the
            // anchor reference, not a generated article.
            guard !key.hasPrefix("ch01") else { continue }

            guard let entry = ArticleIndex.entries[key] else { continue }
            let name = entry.filename.replacingOccurrences(of: ".html", with: "")
            let url = Bundle.main.url(forResource: name, withExtension: "html",
                                      subdirectory: entry.chapterFolder)
                ?? Bundle.main.url(forResource: name, withExtension: "html")
            guard let resolved = url, let html = try? String(contentsOf: resolved, encoding: .utf8) else {
                continue  // covered by the existence test above
            }
            // Count <section>...</section> blocks (excluding the .lede
            // and .references containers). Each misconception is a
            // bare <section> per the generator template.
            let sectionCount = html.components(separatedBy: "<section>").count - 1
            XCTAssertGreaterThanOrEqual(sectionCount, 3,
                "Article '\(key)' has only \(sectionCount) <section> block(s) — " +
                "expected ≥ 3 misconception sections per the SUPERPROMPT §10 " +
                "stop-and-ask threshold.")
        }
    }

    // MARK: - Helpers

    /// "ch01_mistakes" → "ch01"
    private func chapterPrefix(from key: String) -> String {
        return String(key.split(separator: "_").first ?? "")
    }

    private func loadSciencePack() throws -> SubjectPack {
        guard let url = Bundle.main.url(forResource: "science_class7", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            throw XCTSkip("science_class7.json missing from test bundle resources.")
        }
        return try JSONDecoder().decode(SubjectPack.self, from: data)
    }
}
