import XCTest
@testable import desktopAhaan

/// Ratchet for the Social Science (`socialscience_class7`) ARTICLES stage.
///
/// Pins the chapter-level read-mode article surface added for the new
/// subject. Social Science ships a tailored 8-type set per chapter
/// (Overview, Vocabulary Deck, NCERT Q&A, Beyond the Book, What If?,
/// Common Mistakes, Mini Project, Timeline), generated by
/// `scripts/generate_socialscience_articles.py` and registered in
/// `ArticleIndex+SocialScienceEntries.swift`.
///
/// Invariants:
///   1. All 8 chip keys resolve to an `ArticleIndex` entry for every one
///      of the 20 chapters — total 8 × 20 = 160.
///   2. Every entry's id carries the `ssch` namespace prefix and its
///      filename/folder agree with the chapter number in the key.
///   3. LEAK GATE: no Social Science article key collides with a Science
///      (`ch*`), Maths (`mch*`) or Sanskrit (`sch*`) key, and every key in
///      `socialScienceEntries` begins with `ssch` so SS articles can never
///      surface under another subject's chapter dispatch.
final class SocialScienceArticleRoutingTests: XCTestCase {

    /// Frozen list — must match the `socialScienceRows[*].suffix` list in
    /// `ChapterDetailView+ExtraReadingRow.swift`. When the row changes,
    /// update this sentinel and the 160 floor below.
    private static let chipSuffixes: [String] = [
        "_overview",
        "_glossary",
        "_ncert_qa",
        "_beyond",
        "_whatif",
        "_mistakes",
        "_miniproject",
        "_timeline",
    ]

    func testChipSuffixSentinelEqualsEight() {
        XCTAssertEqual(Self.chipSuffixes.count, 8,
            "Social Science ExtraReadingRow chip-suffix sentinel — expected 8, got \(Self.chipSuffixes.count).")
    }

    func testPackDecodes() throws {
        let pack = try loadSocialSciencePack()
        XCTAssertEqual(pack.id, "socialscience_class7")
        XCTAssertEqual(pack.chapters.count, 20,
            "Social Science pack should have 20 chapters, got \(pack.chapters.count).")
    }

    func testEveryChapterResolvesAllEightChipKeys() throws {
        let pack = try loadSocialSciencePack()
        var missing: [String] = []
        for chapter in pack.chapters {
            for suffix in Self.chipSuffixes {
                let key = "\(chapter.id)\(suffix)"
                if ArticleIndex.entries[key] == nil {
                    missing.append(key)
                }
            }
        }
        XCTAssertTrue(missing.isEmpty,
            "Social Science article lookup — \(missing.count) missing key(s):\n" +
            missing.map { "  - \($0)" }.joined(separator: "\n"))
    }

    func testChipMatrixSentinelIsOneHundredSixty() throws {
        let pack = try loadSocialSciencePack()
        var present = 0
        for chapter in pack.chapters {
            for suffix in Self.chipSuffixes where ArticleIndex.entries["\(chapter.id)\(suffix)"] != nil {
                present += 1
            }
        }
        XCTAssertEqual(present, 8 * 20, "Expected 160 resolvable SS article keys, got \(present).")
    }

    func testEntryFolderMatchesChapterNumber() throws {
        let pack = try loadSocialSciencePack()
        for chapter in pack.chapters {
            for suffix in Self.chipSuffixes {
                let key = "\(chapter.id)\(suffix)"
                guard let entry = ArticleIndex.entries[key] else { continue }
                XCTAssertEqual(entry.filename, "\(key).html",
                    "Filename mismatch for \(key): \(entry.filename)")
                XCTAssertEqual(entry.chapterFolder, "Articles/SocialScienceChapter\(chapter.number)",
                    "Folder mismatch for \(key): \(entry.chapterFolder)")
            }
        }
    }

    /// LEAK GATE — Social Science keys are disjoint from every other
    /// subject's keys, and all carry the `ssch` prefix.
    func testNoCrossSubjectArticleKeyLeak() {
        for (key, entry) in ArticleIndex.socialScienceEntries {
            XCTAssertTrue(key.hasPrefix("ssch"),
                "Social Science article key \(key) must start with 'ssch'.")
            XCTAssertEqual(key, entry.id, "Entry id/key mismatch for \(key).")
            // No Sanskrit ("sch" but not "ssch"), Maths ("mch"), or Science ("ch") collision.
            XCTAssertFalse(key.hasPrefix("mch"), "SS key \(key) collides with Maths namespace.")
            XCTAssertFalse(key.hasPrefix("ch"), "SS key \(key) collides with Science namespace.")
        }
    }

    private func loadSocialSciencePack() throws -> SubjectPack {
        guard let url = Bundle.main.url(forResource: "socialscience_class7", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            throw XCTSkip("socialscience_class7.json missing from test bundle.")
        }
        return try JSONDecoder().decode(SubjectPack.self, from: data)
    }
}
