import Foundation
import os.log

private let dictLogger = Logger(subsystem: "com.emoha.desktopAhaan", category: "SanskritDictionary")

/// Comprehensive Sanskrit ↔ English ↔ Hindi dictionary for Class 7 level.
/// This is the core offline translation database.
struct DictionaryEntry: Identifiable {
    let id: String
    let english: String
    let hindi: String
    let sanskrit: String
    let transliteration: String
    let grammarNote: String
    let category: String
    let difficulty: DifficultyLevel

    /// Search-friendly: all text combined for matching
    var searchText: String {
        "\(english) \(hindi) \(sanskrit) \(transliteration)".lowercased()
    }
}

final class SanskritDictionary {
    static let shared = SanskritDictionary()

    /// True once the singleton has finished decoding + indexing. Callers
    /// that touch the translator UI on launch can poll this to show a
    /// "loading dictionary…" state instead of synchronously blocking on
    /// the singleton's lazy init. Atomic via `_isReadyLock`.
    ///
    /// Note: Swift's `static let shared` is itself thread-safe and lazy,
    /// so an access on a thread that races the pre-warm Task will still
    /// produce correct results — it will just block briefly. This flag
    /// is purely UX: it lets the UI show a deterministic loading state
    /// instead of an opaque 50-100ms freeze.
    static var isReady: Bool {
        shared._isReadyLock.lock()
        defer { shared._isReadyLock.unlock() }
        return shared._isReady
    }

    /// All entries indexed for fast lookup
    private(set) var entries: [DictionaryEntry] = []
    private var englishIndex: [String: [DictionaryEntry]] = [:]
    private var hindiIndex: [String: [DictionaryEntry]] = [:]
    private var sanskritIndex: [String: [DictionaryEntry]] = [:]
    private var translitIndex: [String: [DictionaryEntry]] = [:]

    private let _isReadyLock = NSLock()
    private var _isReady: Bool = false

    init() {
        // Primary: load from the bundled JSON file generated by
        // ContentPipeline/utils/migrate_sanskrit.py. This is the source of
        // truth and is cheap to ship/update.
        if let bundled = Self.loadFromBundle() {
            entries = bundled
        } else {
            // Fallback: the legacy hard-coded Swift dictionary. Keeps the app
            // working if the bundled JSON is missing or fails to decode (e.g.
            // during local dev before the JSON has been regenerated).
            dictLogger.warning("bundled JSON not loaded; falling back to built-in Swift dictionary.")
            entries = Self.buildFullDictionary()
        }
        buildIndices()
        _isReadyLock.lock()
        _isReady = true
        _isReadyLock.unlock()
    }

    /// Loads the dictionary from `sanskrit_class7_dictionary.json` in the
    /// app bundle. Returns nil on any failure (file missing, decode error,
    /// unknown difficulty value).
    private static func loadFromBundle() -> [DictionaryEntry]? {
        guard let url = Bundle.main.url(forResource: "sanskrit_class7_dictionary", withExtension: "json") else {
            return nil
        }
        do {
            let data = try Data(contentsOf: url)
            let payload = try JSONDecoder().decode(BundledDictionary.self, from: data)
            let mapped: [DictionaryEntry] = payload.entries.compactMap { row in
                let level: DifficultyLevel
                switch row.difficulty.lowercased() {
                case "easy":   level = .easy
                case "medium": level = .medium
                case "hard":   level = .hard
                default:       return nil
                }
                return DictionaryEntry(
                    id: row.id,
                    english: row.english,
                    hindi: row.hindi,
                    sanskrit: row.sanskrit,
                    transliteration: row.transliteration,
                    grammarNote: row.grammarNote,
                    category: row.category,
                    difficulty: level
                )
            }
            dictLogger.info("loaded \(mapped.count, privacy: .public) entries from bundled JSON (v\(payload.version, privacy: .public)).")
            return mapped.isEmpty ? nil : mapped
        } catch {
            dictLogger.error("failed to decode bundled JSON: \(error.localizedDescription, privacy: .public)")
            return nil
        }
    }

    /// Decoding shape for sanskrit_class7_dictionary.json. Kept private and
    /// flat so it never leaks outside this file.
    private struct BundledDictionary: Decodable {
        let version: String
        let generatedAt: String
        let entries: [BundledEntry]
    }

    private struct BundledEntry: Decodable {
        let id: String
        let english: String
        let hindi: String
        let sanskrit: String
        let transliteration: String
        let grammarNote: String
        let category: String
        let difficulty: String   // "easy" | "medium" | "hard"
    }

    private func buildIndices() {
        for entry in entries {
            // Index by individual words (lowercased)
            for word in entry.english.lowercased().components(separatedBy: .whitespaces) where !word.isEmpty {
                englishIndex[word, default: []].append(entry)
            }
            englishIndex[entry.english.lowercased(), default: []].append(entry)

            for word in entry.hindi.components(separatedBy: .whitespaces) where !word.isEmpty {
                hindiIndex[word, default: []].append(entry)
            }
            hindiIndex[entry.hindi, default: []].append(entry)

            for word in entry.sanskrit.components(separatedBy: .whitespaces) where !word.isEmpty {
                sanskritIndex[word, default: []].append(entry)
            }
            sanskritIndex[entry.sanskrit, default: []].append(entry)

            translitIndex[entry.transliteration.lowercased(), default: []].append(entry)
        }
    }

    /// Look up by exact or partial match in the source language
    func lookup(text: String, from source: SupportedLanguage) -> [DictionaryEntry] {
        let query = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let queryLower = query.lowercased()

        // Try exact match first
        var results: [DictionaryEntry] = []

        switch source {
        case .english:
            results = englishIndex[queryLower] ?? []
            if results.isEmpty {
                // Fuzzy: search all entries
                results = entries.filter { $0.english.localizedCaseInsensitiveContains(query) }
            }
        case .hindi:
            results = hindiIndex[query] ?? []
            if results.isEmpty {
                // 2026-06-05 audit: NFC normalize both sides. Devanagari
                // composed (`क्षि` as a single codepoint sequence) vs
                // decomposed (क + ् + ष + ि) byte-mismatches under bare
                // `contains`. Web clipboard pastes often arrive decomposed;
                // hand-typed Hindi is usually composed.
                let normalQuery = query.precomposedStringWithCanonicalMapping
                results = entries.filter {
                    $0.hindi.precomposedStringWithCanonicalMapping.contains(normalQuery)
                }
            }
        case .sanskrit:
            results = sanskritIndex[query] ?? []
            if results.isEmpty {
                // Also try transliteration
                results = translitIndex[queryLower] ?? []
            }
            if results.isEmpty {
                let normalQuery = query.precomposedStringWithCanonicalMapping
                results = entries.filter {
                    $0.sanskrit.precomposedStringWithCanonicalMapping.contains(normalQuery)
                        || $0.transliteration.localizedCaseInsensitiveContains(query)
                }
            }
        }

        return results
    }

    /// Build a TranslationResponse from dictionary matches
    func translate(text: String, from source: SupportedLanguage, to target: SupportedLanguage) -> TranslationResponse? {
        let matches = lookup(text: text, from: source)
        guard let best = matches.first else { return nil }

        let translatedText: String
        let transliteration: String?

        switch target {
        case .english:
            translatedText = best.english
            transliteration = nil
        case .hindi:
            translatedText = best.hindi
            transliteration = nil
        case .sanskrit:
            translatedText = best.sanskrit
            transliteration = best.transliteration
        }

        // Build word-by-word from individual words if input has multiple words
        let inputWords = text.components(separatedBy: .whitespaces).filter { !$0.isEmpty }
        var wordByWord: [WordMeaning] = []

        if inputWords.count > 1 {
            for word in inputWords {
                let wordMatches = lookup(text: word, from: source)
                if let match = wordMatches.first {
                    let targetWord: String
                    switch target {
                    case .english: targetWord = match.english
                    case .hindi: targetWord = match.hindi
                    case .sanskrit: targetWord = match.sanskrit
                    }
                    wordByWord.append(WordMeaning(source: word, target: targetWord, note: match.grammarNote))
                } else {
                    wordByWord.append(WordMeaning(source: word, target: "(not in dictionary)", note: nil))
                }
            }
        } else {
            // Single word: show the mapping
            wordByWord = [WordMeaning(
                source: text,
                target: translatedText,
                note: best.grammarNote
            )]
        }

        // Gather alternatives from other matches
        let alternatives: [String] = matches.dropFirst().prefix(3).map { match in
            switch target {
            case .english: return match.english
            case .hindi: return match.hindi
            case .sanskrit: return "\(match.sanskrit) (\(match.transliteration))"
            }
        }

        // 2026-06-05 audit: NFC normalize before the Devanagari exact-match
        // gate so composed-vs-decomposed Unicode (same word from clipboard
        // paste vs typed) is treated as identical.
        let textNorm = text.precomposedStringWithCanonicalMapping
        let bestHindiNorm = best.hindi.precomposedStringWithCanonicalMapping
        let bestSanskritNorm = best.sanskrit.precomposedStringWithCanonicalMapping
        let confidence: String
        if matches.count >= 1 && text.lowercased() == best.english.lowercased()
            || textNorm == bestHindiNorm
            || textNorm == bestSanskritNorm
            || text.lowercased() == best.transliteration.lowercased() {
            confidence = "Exact match found in the built-in dictionary."
        } else {
            confidence = "Partial match. The translation may not be exact for this phrase. Try simpler words for better results."
        }

        return TranslationResponse(
            sourceLanguage: source.rawValue,
            targetLanguage: target.rawValue,
            originalText: text,
            translatedText: translatedText,
            transliteration: transliteration,
            wordByWord: wordByWord,
            grammarNote: best.grammarNote,
            learningTip: "This word belongs to the \(best.category) category. Practice it with flashcards!",
            difficulty: best.difficulty,
            alternatives: alternatives.isEmpty ? nil : alternatives,
            confidenceNote: confidence
        )
    }

    // MARK: - Full Dictionary Data
    // Covers: NCERT Class 7 Ruchira, common vocabulary, verbs, pronouns, sentences
    static func buildFullDictionary() -> [DictionaryEntry] {
        var all: [DictionaryEntry] = []

        // ── PRONOUNS ──
        all += [
            DictionaryEntry(id: "pr1", english: "I", hindi: "मैं", sanskrit: "अहम्", transliteration: "aham", grammarNote: "First person singular pronoun, nominative case", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr2", english: "you (respectful)", hindi: "आप", sanskrit: "भवान्", transliteration: "bhavān", grammarNote: "Second person respectful pronoun, masculine nominative", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr3", english: "you (respectful, feminine)", hindi: "आप (स्त्री)", sanskrit: "भवती", transliteration: "bhavatī", grammarNote: "Second person respectful pronoun, feminine nominative", category: "Pronouns", difficulty: .medium),
            DictionaryEntry(id: "pr4", english: "he / that", hindi: "वह (पुरुष)", sanskrit: "सः", transliteration: "saḥ", grammarNote: "Third person masculine demonstrative pronoun, nominative singular", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr5", english: "she / that", hindi: "वह (स्त्री)", sanskrit: "सा", transliteration: "sā", grammarNote: "Third person feminine demonstrative pronoun, nominative singular", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr6", english: "that (neuter)", hindi: "वह (नपुंसक)", sanskrit: "तत्", transliteration: "tat", grammarNote: "Third person neuter demonstrative pronoun, nominative singular", category: "Pronouns", difficulty: .medium),
            DictionaryEntry(id: "pr7", english: "we", hindi: "हम", sanskrit: "वयम्", transliteration: "vayam", grammarNote: "First person plural pronoun, nominative", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr8", english: "they (masculine)", hindi: "वे (पुरुष)", sanskrit: "ते", transliteration: "te", grammarNote: "Third person masculine plural pronoun, nominative", category: "Pronouns", difficulty: .medium),
            DictionaryEntry(id: "pr9", english: "this (masculine)", hindi: "यह (पुरुष)", sanskrit: "एषः", transliteration: "eṣaḥ", grammarNote: "Proximal demonstrative pronoun, masculine nominative singular", category: "Pronouns", difficulty: .medium),
            DictionaryEntry(id: "pr10", english: "this (feminine)", hindi: "यह (स्त्री)", sanskrit: "एषा", transliteration: "eṣā", grammarNote: "Proximal demonstrative pronoun, feminine nominative singular", category: "Pronouns", difficulty: .medium),
            DictionaryEntry(id: "pr11", english: "what", hindi: "क्या", sanskrit: "किम्", transliteration: "kim", grammarNote: "Interrogative pronoun, neuter nominative singular", category: "Pronouns", difficulty: .easy),
            DictionaryEntry(id: "pr12", english: "who", hindi: "कौन", sanskrit: "कः", transliteration: "kaḥ", grammarNote: "Interrogative pronoun, masculine nominative singular", category: "Pronouns", difficulty: .easy),
        ]

        // ── GREETINGS & COMMON EXPRESSIONS ──
        all += [
            DictionaryEntry(id: "g1", english: "hello / greetings", hindi: "नमस्ते", sanskrit: "नमस्ते", transliteration: "namaste", grammarNote: "'namah' (bow) + 'te' (to you) — a respectful greeting", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g2", english: "good morning", hindi: "सुप्रभात", sanskrit: "सुप्रभातम्", transliteration: "suprabhātam", grammarNote: "'su' (good) + 'prabhāta' (morning) with neuter ending '-m'", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g3", english: "good evening", hindi: "शुभ संध्या", sanskrit: "शुभसन्ध्या", transliteration: "śubhasandhyā", grammarNote: "'śubha' (auspicious) + 'sandhyā' (evening)", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g4", english: "thank you", hindi: "धन्यवाद", sanskrit: "धन्यवादः", transliteration: "dhanyavādaḥ", grammarNote: "'dhanya' (blessed) + 'vāda' (speech) — masculine nominative with visarga", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g5", english: "welcome", hindi: "स्वागत है", sanskrit: "स्वागतम्", transliteration: "svāgatam", grammarNote: "'su' (good) + 'āgata' (arrived) = welcome; neuter nominative", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g6", english: "please", hindi: "कृपया", sanskrit: "कृपया", transliteration: "kṛpayā", grammarNote: "Instrumental case of 'kṛpā' (grace/kindness)", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g7", english: "excuse me / forgive me", hindi: "क्षमा कीजिए", sanskrit: "क्षम्यताम्", transliteration: "kṣamyatām", grammarNote: "Passive imperative of 'kṣam' (to forgive)", category: "Greetings", difficulty: .medium),
            DictionaryEntry(id: "g8", english: "goodbye / we shall meet again", hindi: "फिर मिलेंगे", sanskrit: "पुनर्मिलामः", transliteration: "punarmilāmaḥ", grammarNote: "'punar' (again) + 'milāmaḥ' (we shall meet) — first person plural future", category: "Greetings", difficulty: .medium),
            DictionaryEntry(id: "g9", english: "how are you?", hindi: "आप कैसे हैं?", sanskrit: "भवान् कथम् अस्ति?", transliteration: "bhavān katham asti?", grammarNote: "'bhavān' = you (respectful), 'katham' = how, 'asti' = is", category: "Greetings", difficulty: .medium),
            DictionaryEntry(id: "g10", english: "I am fine", hindi: "मैं ठीक हूँ", sanskrit: "अहं कुशली अस्मि", transliteration: "ahaṁ kuśalī asmi", grammarNote: "'aham' = I, 'kuśalī' = well/fine (masc.), 'asmi' = am", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g11", english: "yes", hindi: "हाँ", sanskrit: "आम्", transliteration: "ām", grammarNote: "Indeclinable affirmation particle", category: "Greetings", difficulty: .easy),
            DictionaryEntry(id: "g12", english: "no / not", hindi: "नहीं", sanskrit: "न", transliteration: "na", grammarNote: "Indeclinable negation particle — placed before the verb", category: "Greetings", difficulty: .easy),
        ]

        // ── NUMBERS ──
        all += [
            DictionaryEntry(id: "n1", english: "one", hindi: "एक", sanskrit: "एकम्", transliteration: "ekam", grammarNote: "Neuter nominative singular", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n2", english: "two", hindi: "दो", sanskrit: "द्वे", transliteration: "dve", grammarNote: "Dual number — Sanskrit has a special form for 'two'", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n3", english: "three", hindi: "तीन", sanskrit: "त्रीणि", transliteration: "trīṇi", grammarNote: "Neuter nominative plural", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n4", english: "four", hindi: "चार", sanskrit: "चत्वारि", transliteration: "catvāri", grammarNote: "Neuter nominative plural", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n5", english: "five", hindi: "पाँच", sanskrit: "पञ्च", transliteration: "pañca", grammarNote: "Same form for all genders in nominative", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n6", english: "six", hindi: "छह", sanskrit: "षट्", transliteration: "ṣaṭ", grammarNote: "Indeclinable numeral", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n7", english: "seven", hindi: "सात", sanskrit: "सप्त", transliteration: "sapta", grammarNote: "Indeclinable numeral", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n8", english: "eight", hindi: "आठ", sanskrit: "अष्ट", transliteration: "aṣṭa", grammarNote: "Indeclinable numeral", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n9", english: "nine", hindi: "नौ", sanskrit: "नव", transliteration: "nava", grammarNote: "Indeclinable numeral", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n10", english: "ten", hindi: "दस", sanskrit: "दश", transliteration: "daśa", grammarNote: "Indeclinable numeral", category: "Numbers", difficulty: .easy),
            DictionaryEntry(id: "n11", english: "twenty", hindi: "बीस", sanskrit: "विंशतिः", transliteration: "viṁśatiḥ", grammarNote: "Feminine noun", category: "Numbers", difficulty: .medium),
            DictionaryEntry(id: "n12", english: "fifty", hindi: "पचास", sanskrit: "पञ्चाशत्", transliteration: "pañcāśat", grammarNote: "Feminine noun", category: "Numbers", difficulty: .medium),
            DictionaryEntry(id: "n13", english: "hundred", hindi: "सौ", sanskrit: "शतम्", transliteration: "śatam", grammarNote: "Neuter noun", category: "Numbers", difficulty: .easy),
        ]

        // ── FAMILY ──
        all += [
            DictionaryEntry(id: "f1", english: "mother", hindi: "माँ", sanskrit: "माता", transliteration: "mātā", grammarNote: "Feminine noun, ṛ-stem nominative singular", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f2", english: "father", hindi: "पिता", sanskrit: "पिता", transliteration: "pitā", grammarNote: "Masculine noun, ṛ-stem nominative singular", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f3", english: "brother", hindi: "भाई", sanskrit: "भ्राता", transliteration: "bhrātā", grammarNote: "Masculine noun, ṛ-stem", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f4", english: "sister", hindi: "बहन", sanskrit: "भगिनी", transliteration: "bhaginī", grammarNote: "Feminine noun, ī-stem nominative singular", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f5", english: "son", hindi: "बेटा / पुत्र", sanskrit: "पुत्रः", transliteration: "putraḥ", grammarNote: "Masculine noun, a-stem nominative with visarga", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f6", english: "daughter", hindi: "बेटी / पुत्री", sanskrit: "पुत्री", transliteration: "putrī", grammarNote: "Feminine noun, ī-stem", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f7", english: "grandfather", hindi: "दादा / नाना", sanskrit: "पितामहः", transliteration: "pitāmahaḥ", grammarNote: "'pitā' (father) + 'maha' (great) = grandfather", category: "Family", difficulty: .medium),
            DictionaryEntry(id: "f8", english: "grandmother", hindi: "दादी / नानी", sanskrit: "पितामही", transliteration: "pitāmahī", grammarNote: "Feminine form of pitāmaha", category: "Family", difficulty: .medium),
            DictionaryEntry(id: "f9", english: "friend", hindi: "मित्र / दोस्त", sanskrit: "मित्रम्", transliteration: "mitram", grammarNote: "Neuter noun, a-stem nominative singular", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f10", english: "teacher (male)", hindi: "गुरु / शिक्षक", sanskrit: "गुरुः", transliteration: "guruḥ", grammarNote: "Masculine noun, u-stem nominative with visarga", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f11", english: "teacher (female)", hindi: "गुरु / शिक्षिका", sanskrit: "गुर्वी", transliteration: "gurvī", grammarNote: "Feminine form of guru", category: "Family", difficulty: .medium),
            DictionaryEntry(id: "f12", english: "student (male)", hindi: "छात्र / विद्यार्थी", sanskrit: "छात्रः", transliteration: "chātraḥ", grammarNote: "Masculine noun, a-stem nominative with visarga", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f13", english: "student (female)", hindi: "छात्रा", sanskrit: "छात्रा", transliteration: "chātrā", grammarNote: "Feminine noun, ā-stem", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f14", english: "boy / child", hindi: "लड़का / बालक", sanskrit: "बालकः", transliteration: "bālakaḥ", grammarNote: "Masculine noun, a-stem nominative", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f15", english: "girl", hindi: "लड़की / बालिका", sanskrit: "बालिका", transliteration: "bālikā", grammarNote: "Feminine noun, ā-stem nominative", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f16", english: "king", hindi: "राजा", sanskrit: "नृपः", transliteration: "nṛpaḥ", grammarNote: "Masculine noun, a-stem. Also 'rājā' (an-stem)", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f17", english: "man / person", hindi: "आदमी / मनुष्य", sanskrit: "नरः", transliteration: "naraḥ", grammarNote: "Masculine noun, a-stem nominative", category: "Family", difficulty: .easy),
            DictionaryEntry(id: "f18", english: "woman", hindi: "औरत / नारी", sanskrit: "नारी", transliteration: "nārī", grammarNote: "Feminine noun, ī-stem", category: "Family", difficulty: .easy),
        ]

        // ── NATURE & ANIMALS ──
        all += [
            DictionaryEntry(id: "na1", english: "tree", hindi: "पेड़", sanskrit: "वृक्षः", transliteration: "vṛkṣaḥ", grammarNote: "Masculine noun, a-stem nominative", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na2", english: "flower", hindi: "फूल", sanskrit: "पुष्पम्", transliteration: "puṣpam", grammarNote: "Neuter noun, a-stem nominative", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na3", english: "river", hindi: "नदी", sanskrit: "नदी", transliteration: "nadī", grammarNote: "Feminine noun, ī-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na4", english: "mountain", hindi: "पहाड़ / पर्वत", sanskrit: "पर्वतः", transliteration: "parvataḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na5", english: "sun", hindi: "सूर्य", sanskrit: "सूर्यः", transliteration: "sūryaḥ", grammarNote: "Masculine noun, a-stem nominative", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na6", english: "moon", hindi: "चाँद / चन्द्र", sanskrit: "चन्द्रः", transliteration: "candraḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na7", english: "water", hindi: "पानी / जल", sanskrit: "जलम्", transliteration: "jalam", grammarNote: "Neuter noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na8", english: "fire", hindi: "आग / अग्नि", sanskrit: "अग्निः", transliteration: "agniḥ", grammarNote: "Masculine noun, i-stem nominative", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na9", english: "earth / land", hindi: "पृथ्वी / धरती", sanskrit: "पृथ्वी", transliteration: "pṛthvī", grammarNote: "Feminine noun, ī-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na10", english: "sky", hindi: "आकाश / आसमान", sanskrit: "आकाशः", transliteration: "ākāśaḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na11", english: "wind / air", hindi: "हवा / वायु", sanskrit: "वायुः", transliteration: "vāyuḥ", grammarNote: "Masculine noun, u-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na12", english: "fruit", hindi: "फल", sanskrit: "फलम्", transliteration: "phalam", grammarNote: "Neuter noun, a-stem — a very common textbook word", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na13", english: "leaf", hindi: "पत्ता", sanskrit: "पत्रम्", transliteration: "patram", grammarNote: "Neuter noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na14", english: "lotus", hindi: "कमल", sanskrit: "कमलम्", transliteration: "kamalam", grammarNote: "Neuter noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na15", english: "elephant", hindi: "हाथी", sanskrit: "गजः", transliteration: "gajaḥ", grammarNote: "Masculine noun, a-stem — one of the most common NCERT nouns", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na16", english: "horse", hindi: "घोड़ा", sanskrit: "अश्वः", transliteration: "aśvaḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na17", english: "cow", hindi: "गाय", sanskrit: "धेनुः", transliteration: "dhenuḥ", grammarNote: "Feminine noun, u-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na18", english: "bird", hindi: "पक्षी / चिड़िया", sanskrit: "खगः", transliteration: "khagaḥ", grammarNote: "'kha' (sky) + 'ga' (goer) = sky-goer = bird", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na19", english: "lion", hindi: "शेर / सिंह", sanskrit: "सिंहः", transliteration: "siṁhaḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
            DictionaryEntry(id: "na20", english: "deer", hindi: "हिरण", sanskrit: "मृगः", transliteration: "mṛgaḥ", grammarNote: "Masculine noun, a-stem", category: "Nature", difficulty: .easy),
        ]

        // ── CLASSROOM & SCHOOL ──
        all += [
            DictionaryEntry(id: "c1", english: "book", hindi: "किताब / पुस्तक", sanskrit: "पुस्तकम्", transliteration: "pustakam", grammarNote: "Neuter noun, a-stem nominative", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c2", english: "pen", hindi: "कलम", sanskrit: "लेखनी", transliteration: "lekhanī", grammarNote: "Feminine noun, ī-stem — literally 'that which writes'", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c3", english: "school", hindi: "विद्यालय", sanskrit: "विद्यालयः", transliteration: "vidyālayaḥ", grammarNote: "'vidyā' (knowledge) + 'ālaya' (abode) — a compound word", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c4", english: "classroom", hindi: "कक्षा", sanskrit: "कक्षा", transliteration: "kakṣā", grammarNote: "Feminine noun, ā-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c5", english: "knowledge / learning", hindi: "ज्ञान / विद्या", sanskrit: "विद्या", transliteration: "vidyā", grammarNote: "Feminine noun, ā-stem — root 'vid' means 'to know'", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c6", english: "house / home", hindi: "घर", sanskrit: "गृहम्", transliteration: "gṛham", grammarNote: "Neuter noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c7", english: "village", hindi: "गाँव", sanskrit: "ग्रामः", transliteration: "grāmaḥ", grammarNote: "Masculine noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c8", english: "city", hindi: "शहर / नगर", sanskrit: "नगरम्", transliteration: "nagaram", grammarNote: "Neuter noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c9", english: "country", hindi: "देश", sanskrit: "देशः", transliteration: "deśaḥ", grammarNote: "Masculine noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c10", english: "food", hindi: "भोजन / खाना", sanskrit: "भोजनम्", transliteration: "bhojanam", grammarNote: "Neuter noun, a-stem — from root 'bhuj' (to eat/enjoy)", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c11", english: "milk", hindi: "दूध", sanskrit: "दुग्धम्", transliteration: "dugdham", grammarNote: "Neuter noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c12", english: "road / path", hindi: "रास्ता / मार्ग", sanskrit: "मार्गः", transliteration: "mārgaḥ", grammarNote: "Masculine noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c13", english: "garden", hindi: "बगीचा / उद्यान", sanskrit: "उद्यानम्", transliteration: "udyānam", grammarNote: "Neuter noun, a-stem", category: "Classroom", difficulty: .easy),
            DictionaryEntry(id: "c14", english: "temple", hindi: "मंदिर", sanskrit: "मन्दिरम्", transliteration: "mandiram", grammarNote: "Neuter noun, a-stem", category: "Classroom", difficulty: .easy),
        ]

        // ── BODY PARTS ──
        all += [
            DictionaryEntry(id: "b1", english: "eye", hindi: "आँख", sanskrit: "नेत्रम्", transliteration: "netram", grammarNote: "Neuter noun, a-stem", category: "Body", difficulty: .easy),
            DictionaryEntry(id: "b2", english: "hand", hindi: "हाथ", sanskrit: "हस्तः", transliteration: "hastaḥ", grammarNote: "Masculine noun, a-stem", category: "Body", difficulty: .easy),
            DictionaryEntry(id: "b3", english: "foot", hindi: "पैर", sanskrit: "पादः", transliteration: "pādaḥ", grammarNote: "Masculine noun, a-stem", category: "Body", difficulty: .easy),
            DictionaryEntry(id: "b4", english: "head", hindi: "सिर", sanskrit: "शिरः", transliteration: "śiraḥ", grammarNote: "Neuter noun, s-stem", category: "Body", difficulty: .easy),
            DictionaryEntry(id: "b5", english: "mouth / face", hindi: "मुँह / मुख", sanskrit: "मुखम्", transliteration: "mukham", grammarNote: "Neuter noun, a-stem", category: "Body", difficulty: .easy),
            DictionaryEntry(id: "b6", english: "ear", hindi: "कान", sanskrit: "कर्णः", transliteration: "karṇaḥ", grammarNote: "Masculine noun, a-stem", category: "Body", difficulty: .easy),
        ]

        // ── TIME WORDS ──
        all += [
            DictionaryEntry(id: "t1", english: "day", hindi: "दिन", sanskrit: "दिनम्", transliteration: "dinam", grammarNote: "Neuter noun, a-stem", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t2", english: "night", hindi: "रात", sanskrit: "रात्रिः", transliteration: "rātriḥ", grammarNote: "Feminine noun, i-stem", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t3", english: "morning", hindi: "सुबह / प्रातः", sanskrit: "प्रातः", transliteration: "prātaḥ", grammarNote: "Indeclinable — used as an adverb of time", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t4", english: "today", hindi: "आज", sanskrit: "अद्य", transliteration: "adya", grammarNote: "Indeclinable adverb of time", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t5", english: "tomorrow", hindi: "कल (आने वाला)", sanskrit: "श्वः", transliteration: "śvaḥ", grammarNote: "Indeclinable adverb of time", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t6", english: "yesterday", hindi: "कल (बीता हुआ)", sanskrit: "ह्यः", transliteration: "hyaḥ", grammarNote: "Indeclinable adverb of time", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t7", english: "now", hindi: "अब / अभी", sanskrit: "अधुना", transliteration: "adhunā", grammarNote: "Indeclinable adverb", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t8", english: "always", hindi: "हमेशा / सदा", sanskrit: "सदा", transliteration: "sadā", grammarNote: "Indeclinable adverb", category: "Time", difficulty: .easy),
            DictionaryEntry(id: "t9", english: "year", hindi: "साल / वर्ष", sanskrit: "वर्षम्", transliteration: "varṣam", grammarNote: "Neuter noun, a-stem", category: "Time", difficulty: .easy),
        ]

        // ── ADJECTIVES ──
        all += [
            DictionaryEntry(id: "a1", english: "good / beautiful", hindi: "अच्छा / सुन्दर", sanskrit: "सुन्दरम्", transliteration: "sundaram", grammarNote: "Adjective, neuter nominative. Masculine: सुन्दरः, Feminine: सुन्दरी", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a2", english: "big / great", hindi: "बड़ा", sanskrit: "महत्", transliteration: "mahat", grammarNote: "Adjective, t-stem. Nominative: महान् (masc.), महती (fem.)", category: "Adjectives", difficulty: .medium),
            DictionaryEntry(id: "a3", english: "small / little", hindi: "छोटा", sanskrit: "लघु", transliteration: "laghu", grammarNote: "Adjective, u-stem", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a4", english: "new", hindi: "नया", sanskrit: "नवीनम्", transliteration: "navīnam", grammarNote: "Adjective, a-stem neuter", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a5", english: "old", hindi: "पुराना", sanskrit: "प्राचीनम्", transliteration: "prācīnam", grammarNote: "Adjective, a-stem neuter", category: "Adjectives", difficulty: .medium),
            DictionaryEntry(id: "a6", english: "white", hindi: "सफेद", sanskrit: "शुक्लम्", transliteration: "śuklam", grammarNote: "Adjective, a-stem neuter", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a7", english: "black", hindi: "काला", sanskrit: "कृष्णम्", transliteration: "kṛṣṇam", grammarNote: "Adjective, a-stem neuter", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a8", english: "happy", hindi: "खुश / प्रसन्न", sanskrit: "प्रसन्नः", transliteration: "prasannaḥ", grammarNote: "Adjective, a-stem masculine nominative", category: "Adjectives", difficulty: .easy),
            DictionaryEntry(id: "a9", english: "true", hindi: "सच / सत्य", sanskrit: "सत्यम्", transliteration: "satyam", grammarNote: "Adjective/noun, a-stem neuter", category: "Adjectives", difficulty: .easy),
        ]

        // ── COMMON VERBS (present tense, third person singular) ──
        all += [
            DictionaryEntry(id: "v1", english: "goes", hindi: "जाता/जाती है", sanskrit: "गच्छति", transliteration: "gacchati", grammarNote: "'gam' (to go) → present tense, third person singular", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v2", english: "comes", hindi: "आता/आती है", sanskrit: "आगच्छति", transliteration: "āgacchati", grammarNote: "'ā' (towards) + 'gacchati' = comes", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v3", english: "reads / studies", hindi: "पढ़ता/पढ़ती है", sanskrit: "पठति", transliteration: "paṭhati", grammarNote: "'paṭh' (to read) → third person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v4", english: "writes", hindi: "लिखता/लिखती है", sanskrit: "लिखति", transliteration: "likhati", grammarNote: "'likh' (to write) → third person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v5", english: "speaks / says", hindi: "बोलता/बोलती है", sanskrit: "वदति", transliteration: "vadati", grammarNote: "'vad' (to speak) → third person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v6", english: "eats", hindi: "खाता/खाती है", sanskrit: "खादति", transliteration: "khādati", grammarNote: "'khād' (to eat) → third person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v7", english: "drinks", hindi: "पीता/पीती है", sanskrit: "पिबति", transliteration: "pibati", grammarNote: "'pā' (to drink) → present stem 'piba', third person 'pibati'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v8", english: "sees / looks", hindi: "देखता/देखती है", sanskrit: "पश्यति", transliteration: "paśyati", grammarNote: "'dṛś' (to see) → present stem 'paśya'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v9", english: "hears / listens", hindi: "सुनता/सुनती है", sanskrit: "शृणोति", transliteration: "śṛṇoti", grammarNote: "'śru' (to hear) → present tense with 'no' infix", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v10", english: "gives", hindi: "देता/देती है", sanskrit: "यच्छति", transliteration: "yacchati", grammarNote: "'dā' (to give) → present stem 'yaccha'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v11", english: "takes", hindi: "लेता/लेती है", sanskrit: "गृह्णाति", transliteration: "gṛhṇāti", grammarNote: "'grah' (to take) → present with nasal infix", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v12", english: "plays", hindi: "खेलता/खेलती है", sanskrit: "क्रीडति", transliteration: "krīḍati", grammarNote: "'krīḍ' (to play) → third person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v13", english: "sleeps", hindi: "सोता/सोती है", sanskrit: "स्वपिति", transliteration: "svapiti", grammarNote: "'svap' (to sleep) → second conjugation present", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v14", english: "sits", hindi: "बैठता/बैठती है", sanskrit: "उपविशति", transliteration: "upaviśati", grammarNote: "'upa' (near) + 'viś' (to enter) = to sit down", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v15", english: "stands", hindi: "खड़ा होता है", sanskrit: "तिष्ठति", transliteration: "tiṣṭhati", grammarNote: "'sthā' (to stand) → present with reduplication", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v16", english: "runs", hindi: "दौड़ता/दौड़ती है", sanskrit: "धावति", transliteration: "dhāvati", grammarNote: "'dhāv' (to run) → first conjugation present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v17", english: "knows", hindi: "जानता/जानती है", sanskrit: "जानाति", transliteration: "jānāti", grammarNote: "'jñā' (to know) → ninth conjugation present", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "v18", english: "is (exists)", hindi: "है", sanskrit: "अस्ति", transliteration: "asti", grammarNote: "'as' (to be) → third person singular present — the most important verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v19", english: "are (plural)", hindi: "हैं", sanskrit: "सन्ति", transliteration: "santi", grammarNote: "'as' (to be) → third person plural present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "v20", english: "am", hindi: "हूँ", sanskrit: "अस्मि", transliteration: "asmi", grammarNote: "'as' (to be) → first person singular present", category: "Verbs", difficulty: .easy),
        ]

        // ── COMMON SENTENCES (NCERT Ruchira style) ──
        all += [
            DictionaryEntry(id: "s1", english: "The boy goes to school", hindi: "लड़का विद्यालय जाता है", sanskrit: "बालकः विद्यालयं गच्छति", transliteration: "bālakaḥ vidyālayaṁ gacchati", grammarNote: "Subject (nominative) + object (accusative with -m) + verb — standard word order", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s2", english: "The girl reads a book", hindi: "लड़की पुस्तक पढ़ती है", sanskrit: "बालिका पुस्तकं पठति", transliteration: "bālikā pustakaṁ paṭhati", grammarNote: "'bālikā' (girl, nom.) + 'pustakam' (book, acc.) + 'paṭhati' (reads)", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s3", english: "Water is life", hindi: "जल ही जीवन है", sanskrit: "जलम् एव जीवनम्", transliteration: "jalam eva jīvanam", grammarNote: "'eva' = indeed/only — an emphatic particle", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s4", english: "Knowledge is power", hindi: "विद्या बल है", sanskrit: "विद्या बलम् अस्ति", transliteration: "vidyā balam asti", grammarNote: "Subject + predicate + 'asti' — a classical proverb structure", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s5", english: "The sun rises", hindi: "सूर्य उदय होता है", sanskrit: "सूर्यः उदेति", transliteration: "sūryaḥ udeti", grammarNote: "'ud' (up) + 'eti' (goes) = rises", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s6", english: "Trees give fruit", hindi: "पेड़ फल देते हैं", sanskrit: "वृक्षाः फलानि यच्छन्ति", transliteration: "vṛkṣāḥ phalāni yacchanti", grammarNote: "Plural subject + plural object + third person plural verb", category: "Sentences", difficulty: .hard),
            DictionaryEntry(id: "s7", english: "My name is...", hindi: "मेरा नाम...है", sanskrit: "मम नाम...अस्ति", transliteration: "mama nāma...asti", grammarNote: "'mama' (my, genitive) + 'nāma' (name) + 'asti' (is)", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s8", english: "What is your name?", hindi: "आपका नाम क्या है?", sanskrit: "भवतः नाम किम्?", transliteration: "bhavataḥ nāma kim?", grammarNote: "'bhavataḥ' (your, genitive) + 'nāma' (name) + 'kim' (what)", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s9", english: "I understand", hindi: "मैं समझता/समझती हूँ", sanskrit: "अहं अवगच्छामि", transliteration: "ahaṁ avagacchāmi", grammarNote: "'ava' + 'gacchāmi' = to understand, first person singular", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s10", english: "I do not understand", hindi: "मैं नहीं समझता/समझती", sanskrit: "अहं न अवगच्छामि", transliteration: "ahaṁ na avagacchāmi", grammarNote: "'na' negation placed before the verb", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s11", english: "Please sit down", hindi: "कृपया बैठिए", sanskrit: "कृपया उपविशतु", transliteration: "kṛpayā upaviśatu", grammarNote: "'kṛpayā' (please) + imperative third person", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s12", english: "The earth is round", hindi: "पृथ्वी गोल है", sanskrit: "पृथ्वी गोलाकारा अस्ति", transliteration: "pṛthvī golākārā asti", grammarNote: "Adjective agrees in gender with feminine noun", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s13", english: "The elephant walks", hindi: "हाथी चलता है", sanskrit: "गजः चलति", transliteration: "gajaḥ calati", grammarNote: "Simple subject-verb sentence, third person singular", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s14", english: "Children play in the garden", hindi: "बच्चे बगीचे में खेलते हैं", sanskrit: "बालकाः उद्याने क्रीडन्ति", transliteration: "bālakāḥ udyāne krīḍanti", grammarNote: "Plural nom. + locative case (-e) + plural verb (-anti)", category: "Sentences", difficulty: .hard),
            DictionaryEntry(id: "s15", english: "India is my country", hindi: "भारत मेरा देश है", sanskrit: "भारतम् मम देशः अस्ति", transliteration: "bhāratam mama deśaḥ asti", grammarNote: "'mama' (my, genitive) + nominative predicate", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s16", english: "Sanskrit is a beautiful language", hindi: "संस्कृत एक सुंदर भाषा है", sanskrit: "संस्कृतं सुन्दरा भाषा अस्ति", transliteration: "saṁskṛtaṁ sundarā bhāṣā asti", grammarNote: "Adjective 'sundarā' agrees with feminine 'bhāṣā'", category: "Sentences", difficulty: .medium),
            DictionaryEntry(id: "s17", english: "I go to school", hindi: "मैं विद्यालय जाता/जाती हूँ", sanskrit: "अहं विद्यालयं गच्छामि", transliteration: "ahaṁ vidyālayaṁ gacchāmi", grammarNote: "First person singular: 'aham' + accusative + '-āmi' verb ending", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s18", english: "He reads a book", hindi: "वह पुस्तक पढ़ता है", sanskrit: "सः पुस्तकं पठति", transliteration: "saḥ pustakaṁ paṭhati", grammarNote: "'saḥ' (he) + accusative object + third person verb", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s19", english: "She drinks milk", hindi: "वह दूध पीती है", sanskrit: "सा दुग्धं पिबति", transliteration: "sā dugdhaṁ pibati", grammarNote: "'sā' (she) + accusative + third person verb", category: "Sentences", difficulty: .easy),
            DictionaryEntry(id: "s20", english: "We study Sanskrit", hindi: "हम संस्कृत पढ़ते हैं", sanskrit: "वयं संस्कृतं पठामः", transliteration: "vayaṁ saṁskṛtaṁ paṭhāmaḥ", grammarNote: "'vayam' (we) + accusative + first person plural '-āmaḥ'", category: "Sentences", difficulty: .medium),
        ]

        // ── QUESTION WORDS ──
        all += [
            DictionaryEntry(id: "q1", english: "where", hindi: "कहाँ", sanskrit: "कुत्र", transliteration: "kutra", grammarNote: "Interrogative adverb of place", category: "Question Words", difficulty: .easy),
            DictionaryEntry(id: "q2", english: "when", hindi: "कब", sanskrit: "कदा", transliteration: "kadā", grammarNote: "Interrogative adverb of time", category: "Question Words", difficulty: .easy),
            DictionaryEntry(id: "q3", english: "why", hindi: "क्यों", sanskrit: "किमर्थम्", transliteration: "kimartham", grammarNote: "'kim' (what) + 'artham' (for purpose) = why", category: "Question Words", difficulty: .medium),
            DictionaryEntry(id: "q4", english: "how", hindi: "कैसे", sanskrit: "कथम्", transliteration: "katham", grammarNote: "Interrogative adverb of manner", category: "Question Words", difficulty: .easy),
            DictionaryEntry(id: "q5", english: "how many", hindi: "कितने", sanskrit: "कति", transliteration: "kati", grammarNote: "Interrogative numeral — indeclinable", category: "Question Words", difficulty: .medium),
        ]

        // ── POSTPOSITIONS / PARTICLES ──
        all += [
            DictionaryEntry(id: "pp1", english: "and", hindi: "और", sanskrit: "च", transliteration: "ca", grammarNote: "Conjunction — placed AFTER the word it connects (postpositive)", category: "Particles", difficulty: .easy),
            DictionaryEntry(id: "pp2", english: "but / however", hindi: "लेकिन / परन्तु", sanskrit: "परन्तु", transliteration: "parantu", grammarNote: "Adversative conjunction", category: "Particles", difficulty: .easy),
            DictionaryEntry(id: "pp3", english: "also / too", hindi: "भी", sanskrit: "अपि", transliteration: "api", grammarNote: "Indeclinable particle — placed after the word", category: "Particles", difficulty: .easy),
            DictionaryEntry(id: "pp4", english: "with", hindi: "के साथ", sanskrit: "सह", transliteration: "saha", grammarNote: "Postposition — used with instrumental case", category: "Particles", difficulty: .medium),
            DictionaryEntry(id: "pp5", english: "from", hindi: "से", sanskrit: "तः", transliteration: "taḥ", grammarNote: "Ablative suffix — added to stem (e.g., grāmataḥ = from village)", category: "Particles", difficulty: .medium),
            DictionaryEntry(id: "pp6", english: "here", hindi: "यहाँ", sanskrit: "अत्र", transliteration: "atra", grammarNote: "Demonstrative adverb of place", category: "Particles", difficulty: .easy),
            DictionaryEntry(id: "pp7", english: "there", hindi: "वहाँ", sanskrit: "तत्र", transliteration: "tatra", grammarNote: "Demonstrative adverb of place", category: "Particles", difficulty: .easy),
            DictionaryEntry(id: "pp8", english: "very / much", hindi: "बहुत", sanskrit: "अतीव", transliteration: "atīva", grammarNote: "Indeclinable adverb of degree", category: "Particles", difficulty: .easy),
        ]

        // ── EXPANDED VERBS (all persons & base forms) ──
        all += [
            // Base verbs with infinitive forms for common lookup
            DictionaryEntry(id: "ve1", english: "go", hindi: "जाना", sanskrit: "गच्छति", transliteration: "gacchati", grammarNote: "Root 'gam' (धातु); 3rd person singular present. Infinitive: गन्तुम् (gantum)", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve2", english: "come", hindi: "आना", sanskrit: "आगच्छति", transliteration: "āgacchati", grammarNote: "Prefix 'ā' + 'gacchati'. Root 'gam'; 3rd person singular", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve3", english: "read", hindi: "पढ़ना", sanskrit: "पठति", transliteration: "paṭhati", grammarNote: "Root 'paṭh' (धातु); 3rd person singular present. Common Class 1 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve4", english: "write", hindi: "लिखना", sanskrit: "लिखति", transliteration: "likhati", grammarNote: "Root 'likh' (धातु); 3rd person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve5", english: "speak", hindi: "बोलना / कहना", sanskrit: "वदति", transliteration: "vadati", grammarNote: "Root 'vad' (धातु, to speak); 3rd person singular. Also used for 'say', 'tell'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve6", english: "eat", hindi: "खाना", sanskrit: "खादति", transliteration: "khādati", grammarNote: "Root 'khād' (धातु); 3rd person singular. Causative from 'khad'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve7", english: "drink", hindi: "पीना", sanskrit: "पिबति", transliteration: "pibati", grammarNote: "Root 'pā' (धातु); 3rd person singular present. Strong form of present tense", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve8", english: "see", hindi: "देखना", sanskrit: "पश्यति", transliteration: "paśyati", grammarNote: "Root 'paś' (धातु, to see); 3rd person singular. Also: 'look', 'watch'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve9", english: "hear", hindi: "सुनना", sanskrit: "शृणोति", transliteration: "śṛṇoti", grammarNote: "Root 'śru' (धातु); 3rd person singular present. Strong form. Also: 'listen'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve10", english: "give", hindi: "देना", sanskrit: "यच्छति", transliteration: "yacchati", grammarNote: "Root 'yam्/यज्' (धातु); 3rd person singular. Class 6 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve11", english: "take", hindi: "लेना / पकड़ना", sanskrit: "गृह्णाति", transliteration: "gṛhṇāti", grammarNote: "Root 'grah्' (धातु); 3rd person singular. Class 5 verb. Also: 'get', 'grasp'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve12", english: "play", hindi: "खेलना", sanskrit: "क्रीडति", transliteration: "krīḍati", grammarNote: "Root 'krīḍ' (धातु); 3rd person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve13", english: "sleep", hindi: "सोना", sanskrit: "स्वपिति", transliteration: "svapiti", grammarNote: "Root 'svap' (धातु); 3rd person singular present. Class 2 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve14", english: "sit", hindi: "बैठना", sanskrit: "उपविशति", transliteration: "upaviśati", grammarNote: "Prefix 'upa' + root 'viś' (धातु); 3rd person singular. Also: 'sit down'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve15", english: "stand", hindi: "खड़ा होना", sanskrit: "तिष्ठति", transliteration: "tiṣṭhati", grammarNote: "Root 'sthā' (धातु); 3rd person singular. Class 1 verb. Also: 'stand up'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve16", english: "run", hindi: "दौड़ना", sanskrit: "धावति", transliteration: "dhāvati", grammarNote: "Root 'dhāv' (धातु); 3rd person singular present. Class 1 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve17", english: "know", hindi: "जानना / समझना", sanskrit: "जानाति", transliteration: "jānāti", grammarNote: "Root 'jñā' (धातु); 3rd person singular. Class 9 verb. Also: 'understand'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve18", english: "walk", hindi: "चलना", sanskrit: "चलति", transliteration: "calati", grammarNote: "Root 'cal' (धातु); 3rd person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve19", english: "sing", hindi: "गाना", sanskrit: "गायति", transliteration: "gāyati", grammarNote: "Root 'gai' (धातु); 3rd person singular. Causative form", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve20", english: "dance", hindi: "नृत्य करना", sanskrit: "नृत्यति", transliteration: "nṛtyati", grammarNote: "Root 'nṛt्य' (धातु); 3rd person singular present", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve21", english: "cook", hindi: "पकाना", sanskrit: "पचति", transliteration: "pacati", grammarNote: "Root 'pac' (धातु); 3rd person singular. Class 1 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve22", english: "wash", hindi: "धोना", sanskrit: "प्रक्षालयति", transliteration: "prakṣālayati", grammarNote: "Prefix 'pra' + root 'kṣāl' (धातु); 3rd person singular. Causative", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve23", english: "bathe", hindi: "नहाना", sanskrit: "स्नाति", transliteration: "snāti", grammarNote: "Root 'snā' (धातु, to bathe); 3rd person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve24", english: "laugh", hindi: "हँसना / मुस्कुराना", sanskrit: "हसति", transliteration: "hasati", grammarNote: "Root 'has' (धातु, to laugh); 3rd person singular. Also: 'smile'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve25", english: "cry", hindi: "रोना", sanskrit: "रोदिति", transliteration: "roditi", grammarNote: "Root 'rud' (धातु, to weep); 3rd person singular. Also: 'weep'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve26", english: "love", hindi: "प्रेम करना / प्यार करना", sanskrit: "स्निह्यति", transliteration: "snihyati", grammarNote: "Root 'sneh' (धातु); 3rd person singular. Related to 'sneha' (affection)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve27", english: "think", hindi: "सोचना / विचार करना", sanskrit: "चिन्तयति", transliteration: "cintayati", grammarNote: "Root 'cint' (धातु); 3rd person singular. Causative form. Related to 'cintana' (thinking)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve28", english: "want", hindi: "चाहना / इच्छा करना", sanskrit: "इच्छति", transliteration: "icchati", grammarNote: "Root 'iCC' (धातु); 3rd person singular. Also: 'wish', 'desire'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve29", english: "do", hindi: "करना", sanskrit: "करोति", transliteration: "karoti", grammarNote: "Root 'kṛ' (धातु); 3rd person singular. Irregular Class 8 verb. Fundamental verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve30", english: "live", hindi: "रहना / बसना", sanskrit: "वसति", transliteration: "vasati", grammarNote: "Root 'vas' (धातु, to dwell); 3rd person singular present", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve31", english: "die", hindi: "मरना", sanskrit: "म्रियते", transliteration: "mriyate", grammarNote: "Root 'mṛ' (धातु); 3rd person singular middle voice (atmanepadi)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve32", english: "fly", hindi: "उड़ना", sanskrit: "उड्डयते", transliteration: "uḍḍayate", grammarNote: "Root 'uḍ्ड' (धातु); 3rd person singular middle voice", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve33", english: "swim", hindi: "तैरना", sanskrit: "तरति", transliteration: "tarati", grammarNote: "Root 'tar' (धातु, to cross/swim); 3rd person singular", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve34", english: "fall", hindi: "गिरना / पड़ना", sanskrit: "पतति", transliteration: "patati", grammarNote: "Root 'pat' (धातु); 3rd person singular. Also means 'come down'", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve35", english: "rise", hindi: "उठना / जागना", sanskrit: "उत्तिष्ठति", transliteration: "uttiṣṭhati", grammarNote: "Prefix 'ut' + root 'sthā' (धातु); 3rd person singular. Also: 'wake up'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve36", english: "open", hindi: "खोलना", sanskrit: "उद्घाटयति", transliteration: "udghāṭayati", grammarNote: "Prefix 'ud' + root 'ghāṭ' (धातु); 3rd person singular causative", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve37", english: "close", hindi: "बंद करना / बंद होना", sanskrit: "पिदधाति", transliteration: "pidadhāti", grammarNote: "Root 'bandh' (धातु, to bind); 3rd person singular. Also: 'shut'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve38", english: "buy", hindi: "खरीदना", sanskrit: "क्रीणाति", transliteration: "krīṇāti", grammarNote: "Root 'krī' (धातु, to purchase); 3rd person singular Class 9 verb", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve39", english: "sell", hindi: "बेचना", sanskrit: "विक्रीणाति", transliteration: "vikrīṇāti", grammarNote: "Prefix 'vi' + root 'krī' (धातु); 3rd person singular. Class 9 verb", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve40", english: "send", hindi: "भेजना", sanskrit: "प्रेषयति", transliteration: "preṣayati", grammarNote: "Root 'preṣ' (धातु); 3rd person singular. Causative form", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve41", english: "bring", hindi: "लाना", sanskrit: "आनयति", transliteration: "ānayati", grammarNote: "Root 'nī' (धातु, to lead) with prefix 'ā'; 3rd person singular", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve42", english: "carry", hindi: "ढोना / वहन करना", sanskrit: "वहति", transliteration: "vahati", grammarNote: "Root 'vah' (धातु); 3rd person singular. Also: 'bear', 'convey'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve43", english: "teach", hindi: "पढ़ाना / सिखाना", sanskrit: "पाठयति", transliteration: "pāṭhayati", grammarNote: "Root 'paṭh' (धातु) with causative suffix; 3rd person singular. Causative of 'paṭhati'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve44", english: "learn", hindi: "सीखना / सीख लेना", sanskrit: "अधीते", transliteration: "adhīte", grammarNote: "Root 'dhī' (धातु); 3rd person singular middle voice (atmanepadi). Also 'adhyayati'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve45", english: "ask", hindi: "पूछना / सवाल करना", sanskrit: "पृच्छति", transliteration: "pṛcchati", grammarNote: "Root 'prach्' (धातु, to inquire); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve46", english: "answer", hindi: "जवाब देना", sanskrit: "उत्तरं ददाति", transliteration: "uttaraṁ dadāti", grammarNote: "Compound: 'uttara' (answer, accusative) + 'dadāti' (gives). Note: compound verb", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve47", english: "help", hindi: "मदद करना / सहायता करना", sanskrit: "सहायतां करोति", transliteration: "sahāyatāṁ karoti", grammarNote: "Compound: 'sahāyatā' (help, accusative) + 'karoti' (does). Note: compound verb", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve48", english: "wait", hindi: "प्रतीक्षा करना / इंतज़ार करना", sanskrit: "प्रतीक्षते", transliteration: "pratīkṣate", grammarNote: "Root 'īkṣ' (धातु, to look); 3rd person singular middle voice with prefix 'prati'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve49", english: "remember", hindi: "याद करना / स्मरण करना", sanskrit: "स्मरति", transliteration: "smarati", grammarNote: "Root 'smṛ' (धातु); 3rd person singular. Class 1 verb", category: "Verbs", difficulty: .easy),
            DictionaryEntry(id: "ve50", english: "forget", hindi: "भूलना", sanskrit: "विस्मरति", transliteration: "vismarati", grammarNote: "Prefix 'vi' + root 'smṛ' (धातु); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve51", english: "begin", hindi: "शुरू करना / आरंभ करना", sanskrit: "आरभते", transliteration: "ārabhate", grammarNote: "Root 'rabh' (धातु); 3rd person singular middle voice. Also: 'start', 'undertake'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve52", english: "finish", hindi: "पूरा करना / समाप्त करना", sanskrit: "समाप्नोति", transliteration: "samāpnoti", grammarNote: "Prefix 'sam' + root 'ap' (धातु); 3rd person singular. Also: 'complete'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve53", english: "touch", hindi: "छूना / स्पर्श करना", sanskrit: "स्पृशति", transliteration: "spṛśati", grammarNote: "Root 'spṛś' (धातु); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve54", english: "break", hindi: "तोड़ना / भंग करना", sanskrit: "भनक्ति", transliteration: "bhanakti", grammarNote: "Root 'bhañj्' (धातु); 3rd person singular. Also 'bhanakti' or 'bhaṅkti'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve55", english: "burn", hindi: "जलाना / आग लगाना", sanskrit: "दहति", transliteration: "dahati", grammarNote: "Root 'dah' (धातु); 3rd person singular. Class 1 verb", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve56", english: "cut", hindi: "काटना / छेदना", sanskrit: "छिनत्ति", transliteration: "chinatti", grammarNote: "Root 'chid्' (धातु); 3rd person singular. Strong present form", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve57", english: "throw", hindi: "फेंकना / डालना", sanskrit: "क्षिपति", transliteration: "kṣipati", grammarNote: "Root 'kṣip' (धातु); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve58", english: "catch", hindi: "पकड़ना / पकड़ लेना", sanskrit: "धारयति", transliteration: "dhārayati", grammarNote: "Root 'dhṛ' (धातु, to hold/support); 3rd person singular causative. Also: 'hold'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve59", english: "pull", hindi: "खींचना / खींच लेना", sanskrit: "कर्षति", transliteration: "karṣati", grammarNote: "Root 'kṛṣ' (धातु); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve60", english: "push", hindi: "धकेलना / ढकेलना", sanskrit: "नुदति", transliteration: "nudati", grammarNote: "Root 'nud' (धातु); 3rd person singular", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve61", english: "fight", hindi: "लड़ना / युद्ध करना", sanskrit: "युध्यते", transliteration: "yudhyate", grammarNote: "Root 'yudh' (धातु); 3rd person singular middle voice. Also: 'battle'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve62", english: "win", hindi: "जीतना / विजय पाना", sanskrit: "जयति", transliteration: "jayati", grammarNote: "Root 'ji' (धातु, to conquer); 3rd person singular. Also: 'conquer', 'overcome'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve63", english: "lose", hindi: "हारना / पराजित होना", sanskrit: "पराजयते", transliteration: "parājayate", grammarNote: "Prefix 'para' + root 'ji' (धातु) in passive; 3rd person singular. Also: 'be defeated'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve64", english: "call", hindi: "बुलाना / पुकारना", sanskrit: "आह्वयति", transliteration: "āhvayati", grammarNote: "Root 'hve' (धातु); 3rd person singular. Also: 'invite', 'summon'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve65", english: "praise", hindi: "प्रशंसा करना / तारीफ करना", sanskrit: "स्तौति", transliteration: "stauti", grammarNote: "Root 'stṛ' (धातु, to praise); 3rd person singular. Related to 'stuti' (hymn)", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve66", english: "worship", hindi: "पूजा करना / पूजन करना", sanskrit: "पूजयति", transliteration: "pūjayati", grammarNote: "Root 'pūj' (धातु); 3rd person singular causative. Related to 'pūjā' (worship)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve67", english: "protect", hindi: "रक्षा करना / बचाना", sanskrit: "रक्षति", transliteration: "rakṣati", grammarNote: "Root 'rakṣ' (धातु, to guard); 3rd person singular. Also: 'save', 'guard'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve68", english: "destroy", hindi: "नष्ट करना / बर्बाद करना", sanskrit: "नाशयति", transliteration: "nāśayati", grammarNote: "Root 'naś' (धातु); 3rd person singular causative", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve69", english: "build", hindi: "बनाना / निर्माण करना", sanskrit: "निर्माति", transliteration: "nirmāti", grammarNote: "Prefix 'nir' + root 'mā' (धातु, to make); 3rd person singular. Also: 'create', 'construct'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve70", english: "clean", hindi: "साफ़ करना / शुद्ध करना", sanskrit: "शोधयति", transliteration: "śodhayati", grammarNote: "Root 'śodh' (धातु); 3rd person singular causative. Related to 'śuddha' (pure)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve71", english: "count", hindi: "गिनना / गणना करना", sanskrit: "गणयति", transliteration: "gaṇayati", grammarNote: "Root 'gaṇ' (धातु); 3rd person singular. Related to 'gaṇa' (group/number)", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve72", english: "measure", hindi: "नापना / मापना", sanskrit: "मापयति", transliteration: "māpayati", grammarNote: "Root 'mā' (धातु, to measure); 3rd person singular causative", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve73", english: "fear", hindi: "डरना / भय खाना", sanskrit: "बिभेति", transliteration: "bibheti", grammarNote: "Root 'bhī' (धातु); 3rd person singular. Reduplicated strong present. Also: 'be afraid'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve74", english: "hide", hindi: "छिपाना / छुपाना", sanskrit: "गोपयति", transliteration: "gopayati", grammarNote: "Root 'gup' (धातु, to conceal); 3rd person singular causative. Related to 'goptṛ' (protector)", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve75", english: "find", hindi: "खोजना / पाना", sanskrit: "लभते", transliteration: "labhate", grammarNote: "Root 'labh' (धातु); 3rd person singular middle voice. Also: 'obtain', 'get'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve76", english: "search", hindi: "ढूँढना / तलाश करना", sanskrit: "अन्विष्यति", transliteration: "anviṣyati", grammarNote: "Root 'iṣ' (धातु, to seek) with prefix 'anu'; future form. Also: 'seek', 'pursue'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve77", english: "return", hindi: "लौटना / वापस आना", sanskrit: "प्रत्यागच्छति", transliteration: "pratyāgacchati", grammarNote: "Prefix 'prati' + root 'gam' (धातु); 3rd person singular. Also: 'come back', 'go back'", category: "Verbs", difficulty: .hard),
            DictionaryEntry(id: "ve78", english: "cross", hindi: "पार करना / पार जाना", sanskrit: "तरति", transliteration: "tarati", grammarNote: "Root 'tar' (धातु); 3rd person singular. Also means 'swim', 'traverse'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve79", english: "climb", hindi: "चढ़ना", sanskrit: "आरोहति", transliteration: "ārohati", grammarNote: "Prefix 'ā' + root 'ruh' (धातु, to ascend); 3rd person singular. Also: 'ascend', 'mount'", category: "Verbs", difficulty: .medium),
            DictionaryEntry(id: "ve80", english: "descend", hindi: "उतरना", sanskrit: "अवरोहति", transliteration: "avarohati", grammarNote: "Prefix 'ava' + root 'ruh' (धातु); 3rd person singular. Also: 'go down', 'dismount'", category: "Verbs", difficulty: .medium),
        ]

        return all
    }
}
